**WORK LOGS**


RAJKARAN  ---- 15/01/2025 : 19/01/2025 ----- Data Collection, Data Merging

RAJKARAN  ---- 15/01/2025 : 19/01/2025 ----- Data Collection Reworked, Data Merging

RAJKARAN  ---- 20/01/2025 : 25/02/2025 ---- Creating functions for Batch Processing


RAJKARAN  ---- 25/01/2025 : 30/02/2025 ---- Creating Environment for PPO implementation

RAJKARAN  ---- 02/02/2025 : 08/02/2025 ---- Testing the environment using Full data

# **DATA EXTRACTION**

### **INSTALLING REQUIRED LIBRARIES**

In [ ]:
!pip install yfinance
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Collecting yfinance
  Using cached yfinance-0.2.52-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Collecting lxml>=4.9.1 (from yfinance)
  Using cached lxml-5.3.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2024.2)
Collecting frozendict>=2.3.4 (from yfinance)
  Using cached frozendict-2.4.6-py311-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Using cached peewee-3.17.8.tar.gz (948 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.12.3)
Collecting html5lib>=1.1 (from yfinance)
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2024.12.14)
Downloading yfinance-0.2.52-py2.py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 3.1 MB/s eta 0:00:00
Downloading frozendict-2.4.6-py311-none-any.whl (16 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 8.5 MB/s eta 0:00:00
Downloading lxml-5.3.0-cp311-cp311-manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 63.5 MB/s eta 0:00:00
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.8-cp311-cp311-linux_x86_64.whl size=886568 sha256=f5d1cafc5bee60b8b0deb17005141cd2d697001edf7756fb34df03f2e2629f23
  Stored in directory: /root/.cache/pip/wheels/ff/6c/15/506e25bc390de450a7fa53c155cd9b0fbd13ad3e84a9abc183
Successfully built peewee
Installing collected packages: peewee, multitasking, lxml, html5lib, frozendict, yfinance
Successfully installed frozendict-2.4.6 html5lib-1.1 lxml-5.3.0 multitasking-0.0.11 peewee-3.17.8 yfinance-0.2.52
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-sb3uyl4i
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-sb3uyl4i
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit bc12fe7b57c483e8fac666f4cf05cbf62077958a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-0brwa2ek/elegantrl_a9a9b47dbaa94507af7435b173ccd517
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-0brwa2ek/elegantrl_a9a9b47dbaa94507af7435b173ccd517
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 2fa34dd9236498beada8d8443d927970a9de1f7f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: alpaca-trade-api<4,>=3 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (3.2.0)
Collecting ccxt<4,>=3 (from finrl==0.3.6)
  Downloading ccxt-3.1.60-py2.py3-none-any.whl.metadata (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: exchange-calendars<5,>=4 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (4.8)
Collecting jqdatasdk<2,>=1 (from finrl==0.3.6)
  Downloading jqdatasdk-1.9.7-py3-none-any.whl.metadata (5.8 kB)
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.6)
  Downloading pyfolio-0.9.2.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyportfolioopt<2,>=1 (from finrl==0.3.6)
  Downloading pyportfolioopt-1.5.6-py3-none-any.whl.metadata (22 kB)
Collecting ray<3,>=2 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading ray-2.41.0-cp311-cp311-manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: scikit-learn<2,>=1 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (1.6.1)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.4.1)
Collecting stockstats<0.6,>=0.5 (from finrl==0.3.6)
  Downloading stockstats-0.5.4-py2.py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: wrds<4,>=3 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (0.2.52)
INFO: pip is looking at multiple versions of finrl to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'finrl' requires a different Python: 3.11.11 not in '<3.11,>=3.10'

### **INSTALLING FINRL LIBRARIES**

In [ ]:
!pip install finrl
!pip install gymnasium
!pip install stable_baselines3
!pip install tabulate
!pip install alpaca-trade-api
!pip install exchange-calendars
!pip install stockstats
!pip install wrds

import yfinance as yf
import pandas as pd
from tabulate import tabulate
import time
import alpaca_trade_api as tradeapi



import warnings
warnings.filterwarnings('ignore')

import logging
logging.getLogger('matplotlib.font_manager').disabled = True

import torch

import numpy as np
from sklearn.preprocessing import MaxAbsScaler

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
#from finrl.meta.preprocessor.preprocessors import GroupByScaler
#from finrl.meta.env_portfolio_optimization.env_portfolio_optimization import PortfolioOptimizationEnv
#from finrl.agents.portfolio_optimization.models import DRLAgent
#from finrl.agents.portfolio_optimization.architectures import EIIE

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

Requirement already satisfied: finrl in /usr/local/lib/python3.11/dist-packages (0.3.7)
Requirement already satisfied: gymnasium in /usr/local/lib/python3.11/dist-packages (1.0.0)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium) (3.1.1)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium) (0.0.4)
Requirement already satisfied: stable_baselines3 in /usr/local/lib/python3.11/dist-packages (2.4.1)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (1.0.0)
Requirement already satisfied: numpy<2.0,>=1.20 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (1.26.4)
Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (2.5.1+cpu)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (3.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from stable_baselines3) (3.10.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable_baselines3) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable_baselines3) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable_baselines3) (3.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable_baselines3) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable_baselines3) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable_baselines3) (2024.12.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13->stable_baselines3) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.13->stable_baselines3) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (23.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable_baselines3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->stable_baselines3) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->stable_baselines3) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.13->stable_baselines3) (3.0.2)
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Installing collected packages: tabulate
Successfully installed tabulate-0.9.0
Requirement already satisfied: alpaca-trade-api in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.26.4)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (3.11.11)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (23.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.18.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>2->alpaca-trade-api) (2024.12.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)
Requirement already satisfied: exchange-calendars in /usr/local/lib/python3.11/dist-packages (4.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (2.2.2)
Requirement already satisfied: pyluach in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (2.2.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (1.0.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (2025.1)
Requirement already satisfied: korean_lunar_calendar in /usr/local/lib/python3.11/dist-packages (from exchange-calendars) (0.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->exchange-calendars) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->exchange-calendars) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->exchange-calendars) (1.17.0)
Requirement already satisfied: stockstats in /usr/local/lib/python3.11/dist-packages (0.6.3)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.11/dist-packages (from stockstats) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from stockstats) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->stockstats) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->stockstats) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->stockstats) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.2->stockstats) (1.17.0)
Requirement already satisfied: wrds in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: numpy<1.27,>=1.26 in /usr/local/lib/python3.11/dist-packages (from wrds) (1.26.4)
Requirement already satisfied: packaging<23.3 in /usr/local/lib/python3.11/dist-packages (from wrds) (23.2)
Requirement already satisfied: pandas<2.3,>=2.2 in /usr/local/lib/python3.11/dist-packages (from wrds) (2.2.2)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /usr/local/lib/python3.11/dist-packages (from wrds) (2.9.10)
Requirement already satisfied: scipy<1.13,>=1.12 in /usr/local/lib/python3.11/dist-packages (from wrds) (1.12.0)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /usr/local/lib/python3.11/dist-packages (from wrds) (2.0.37)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)

**LIST OF TICKERS FROM CANADIAN STOCK MARKET**

In [ ]:
FIRST_SET_TICKERS = [
    "AAB.TO", "AAUC.TO", "AAV.TO", "ABX.TO", "AC.TO", "ACAA.TO", "ACB.TO", "ACD.TO", "ACQ.TO", "ACX.TO", "ADCO.TO", "ADEN.TO", "ADIV.TO", "ADN.TO", "AEG.TO", "AEM.TO", "AFN.TO", "AG.TO", "AGG.TO", "AGI.TO", "AI.TO", "AIDX.TO", "AIF.TO", "AIGO.TO", "AII.TO", "AIM.TO", "ALA.TO", "ALC.TO", "ALS.TO", "ALYA.TO", "AMAX.TO", "AMC.TO", "AMHE.TO", "AMM.TO", "AMZH.TO", "AND.TO", "ANRG.TO", "AOI.TO", "AOT.TO", "APLI.TO", "APM.TO", "APS.TO", "AQN.TO", "ARA.TO", "ARB.TO", "ARE.TO", "ARG.TO", "ARIS.TO", "ARTI.TO", "ARX.TO", "ASCU.TO", "ASM.TO", "ASND.TO", "ASTL.TO", "ATCU.TO", "ATD.TO", "ATH.TO", "ATRL.TO", "ATS.TO", "ATSX.TO", "ATZ.TO", "AUMN.TO", "AVCN.TO", "AVL.TO", "AVNT.TO", "AW.TO", "AYA.TO", "BABY.TO", "BAM.TO", "BANK.TO", "BASE.TO", "BB.TO", "BBUC.TO", "BCE.TO", "BCHT.TO", "BCT.TO", "BDGI.TO", "BDI.TO", "BDIV.TO", "BDT.TO", "BEPC.TO", "BEPR.TO", "BESG.TO", "BFIN.TO", "BGC.TO", "BGU.TO", "BHC.TO", "BIPC.TO", "BIR.TO", "BITF.TO", "BITI.TO", "BK.TO", "BKCC.TO", "BKCL.TO", "BKI.TO", "BLCO.TO", "BLDP.TO", "BLN.TO", "BLOV.TO", "BLX.TO", "BMAX.TO", "BMO.TO", "BN.TO", "BNC.TO", "BND.TO", "BNE.TO", "BNG.TO", "BNK.TO", "BNKL.TO", "BNS.TO", "BNT.TO", "BOND.TO", "BOS.TO", "BPRF.TO", "BR.TO", "BRAG.TO", "BRE.TO", "BREA.TO", "BRMI.TO", "BRY.TO", "BSKT.TO", "BSX.TO", "BTCC.TO", "BTCQ.TO", "BTCY.TO", "BTE.TO", "BTO.TO", "BU.TO", "BUI.TO", "BXF.TO", "BYD.TO", "BYL.TO", "CACB.TO", "CAE.TO", "CAFR.TO", "CAGG.TO", "CAGS.TO", "CALL.TO", "CANL.TO", "CAPG.TO", "CAPI.TO", "CAPM.TO", "CAPW.TO", "CARB.TO", "CARS.TO", "CAS.TO", "CASH.TO", "CBAL.TO", "CBCX.TO", "CBGR.TO", "CBH.TO", "CBIL.TO", "CBIN.TO", "CBL.TO", "CBND.TO", "CBNK.TO", "CBO.TO", "CBUG.TO", "CCA.TO", "CCBI.TO", "CCEI.TO", "CCM.TO", "CCNS.TO", "CCNV.TO", "CCO.TO", "CCOM.TO", "CCRE.TO", "CDEF.TO", "CDIV.TO", "CDLB.TO", "CDNA.TO", "CDR.TO", "CDZ.TO", "CEF.TO", "CEMI.TO", "CEMX.TO", "CEQT.TO", "CEU.TO", "CEW.TO", "CF.TO", "CFF.TO", "CFLX.TO", "CFP.TO", "CFRT.TO", "CFW.TO", "CFX.TO", "CG.TO", "CGAA.TO", "CGBI.TO", "CGDV.TO", "CGG.TO", "CGHY.TO", "CGI.TO", "CGIN.TO", "CGL.TO", "CGLO.TO", "CGO.TO", "CGR.TO", "CGRA.TO", "CGRE.TO", "CGRN.TO", "CGRO.TO", "CGX.TO", "CGXF.TO", "CGY.TO", "CHPS.TO", "CHR.TO", "CIA.TO", "CIAI.TO", "CIBR.TO", "CIC.TO", "CIEH.TO", "CIEI.TO", "CIEM.TO", "CIF.TO", "CIGI.TO", "CINF.TO", "CINT.TO", "CINV.TO", "CIX.TO", "CJ.TO", "CJT.TO", "CKI.TO", "CLF.TO", "CLG.TO", "CLML.TO", "CLS.TO", "CM.TO", "CMAG.TO", "CMAR.TO", "CMDO.TO", "CMG.TO", "CMGG.TO", "CMNY.TO", "CMOM.TO", "CMR.TO", "CMVX.TO", "CNCC.TO", "CNCL.TO", "CNDX.TO", "CNE.TO", "CNL.TO", "CNQ.TO", "CNR.TO", "CNT.TO", "CNV.TO", "COG.TO", "COMM.TO", "COPP.TO", "COPR.TO", "CORE.TO", "COW.TO", "CP.TO", "CPD.TO", "CPH.TO", "CPLS.TO", "CPX.TO", "CRDL.TO", "CRED.TO", "CRON.TO", "CROP.TO", "CRP.TO", "CRRX.TO", "CRWN.TO", "CS.TO", "CSAV.TO", "CSBI.TO", "CSCI.TO", "CSU.TO", "CTC.TO", "CTS.TO", "CTX.TO", "CU.TO", "CUBD.TO", "CUD.TO", "CUDV.TO", "CUEH.TO", "CUEI.TO", "CURA.TO", "CUTL.TO", "CVD.TO", "CVE.TO", "CVG.TO", "CVLU.TO", "CVO.TO", "CWB.TO", "CWEB.TO", "CWL.TO", "CWW.TO", "CXB.TO", "CXF.TO", "CXI.TO", "CYB.TO", "CYBR.TO", "CYH.TO", "DAMG.TO", "DANC.TO", "DATA.TO", "DAY.TO", "DBM.TO", "DBO.TO", "DCBC.TO", "DCBO.TO", "DCC.TO", "DCG.TO", "DCM.TO", "DCP.TO", "DCS.TO", "DCU.TO", "DF.TO", "DFN.TO", "DFY.TO", "DGR.TO", "DGRC.TO", "DGS.TO", "DIAM.TO", "DISC.TO", "DIV.TO", "DIVS.TO", "DLCG.TO", "DLR.TO", "DMEC.TO", "DMEI.TO", "DMEU.TO", "DML.TO", "DND.TO", "DNG.TO", "DNTL.TO", "DOL.TO", "DOO.TO", "DPM.TO", "DR.TO", "DRCU.TO", "DRFC.TO", "DRFD.TO", "DRFE.TO", "DRFG.TO", "DRFU.TO", "DRM.TO", "DRMC.TO", "DRMD.TO", "DRME.TO", "DRMU.TO", "DRT.TO", "DRX.TO", "DS.TO", "DSAE.TO", "DSG.TO", "DSV.TO", "DTOL.TO", "DXAU.TO", "DXB.TO", "DXBB.TO", "DXBC.TO", "DXBG.TO", "DXBU.TO", "DXC.TO", "DXCB.TO", "DXCO.TO", "DXCP.TO", "DXDB.TO", "DXEM.TO", "DXET.TO", "DXF.TO", "DXG.TO", "DXGE.TO", "DXIF.TO", "DXMO.TO", "DXN.TO", "DXO.TO", "DXP.TO", "DXQ.TO", "DXR.TO", "DXT.TO", "DXU.TO", "DXUS.TO", "DXV.TO", "DXW.TO", "DXZ.TO", "DYA.TO", "E.TO", "EAGR.TO", "EARN.TO", "EBIT.TO", "EBNK.TO", "ECN.TO", "ECO.TO", "ECOR.TO", "EDGE.TO", "EDGF.TO", "EDR.TO", "EDT.TO", "EDV.TO", "EFN.TO", "EFR.TO", "EFX.TO", "EGLX.TO", "EIF.TO", "ELD.TO", "ELEF.TO", "ELF.TO", "ELO.TO", "ELR.TO", "ELVA.TO", "EMA.TO", "EMAX.TO", "ENB.TO", "ENCC.TO", "ENCL.TO", "ENGH.TO", "ENS.TO", "EPRX.TO", "EQB.TO", "EQCC.TO", "EQCL.TO", "EQL.TO", "EQLI.TO", "EQX.TO", "ERD.TO", "ERO.TO", "ESG.TO", "ESGA.TO", "ESGB.TO", "ESGC.TO", "ESGE.TO", "ESGF.TO", "ESGG.TO", "ESGH.TO", "ESGY.TO", "ESI.TO", "ESM.TO", "ESP.TO", "ESPX.TO", "ET.TO", "ETC.TO", "ETG.TO", "ETHH.TO", "ETHI.TO", "ETHQ.TO", "ETHR.TO", "ETHY.TO", "ETP.TO", "ETSX.TO", "EVO.TO", "EVT.TO", "EXE.TO", "EXN.TO", "EXRO.TO", "FAP.TO", "FAR.TO", "FBGO.TO", "FBT.TO", "FBTC.TO", "FC.TO", "FCCD.TO", "FCCQ.TO", "FCCV.TO", "FCEM.TO", "FCGI.TO", "FCID.TO", "FCII.TO", "FCIQ.TO", "FCIV.TO", "FCMI.TO", "FCQH.TO", "FCRR.TO", "FCUD.TO", "FCUH.TO", "FCUQ.TO", "FCUV.TO", "FCVH.TO", "FDL.TO", "FDN.TO", "FDY.TO", "FEC.TO", "FETH.TO", "FF.TO", "FFH.TO", "FFM.TO", "FFN.TO", "FGB.TO", "FGEB.TO", "FGEP.TO", "FGGE.TO", "FGO.TO", "FGOV.TO", "FGRW.TO", "FHG.TO", "FHH.TO", "FHI.TO", "FHIS.TO", "FHQ.TO", "FIE.TO", "FIG.TO", "FIL.TO", "FINC.TO", "FINE.TO", "FINO.TO", "FLCI.TO", "FLCP.TO", "FLGA.TO", "FLI.TO", "FLNT.TO", "FLOW.TO", "FLSD.TO", "FLUS.TO", "FLX.TO", "FM.TO", "FMAX.TO", "FN.TO", "FNV.TO", "FOM.TO", "FOOD.TO", "FORA.TO", "FOUR.TO", "FPR.TO", "FRU.TO", "FRX.TO", "FSB.TO", "FSF.TO", "FSL.TO", "FST.TO", "FSV.TO", "FSY.TO", "FSZ.TO", "FT.TO", "FTG.TO", "FTHI.TO", "FTN.TO", "FTS.TO", "FTT.TO", "FTU.TO", "FURY.TO", "FVI.TO", "FVL.TO", "FXM.TO", "G.TO", "GATO.TO", "GAU.TO", "GBAL.TO", "GBT.TO", "GCBD.TO", "GCFE.TO", "GCG.TO", "GCL.TO", "GCNS.TO", "GCSC.TO", "GCTB.TO", "GCU.TO", "GDC.TO", "GDEP.TO", "GDI.TO", "GDL.TO", "GDPY.TO", "GDV.TO", "GEC.TO", "GEI.TO", "GENM.TO", "GEO.TO", "GEQT.TO", "GFL.TO", "GFP.TO", "GFR.TO", "GGD.TO", "GGRO.TO", "GH.TO", "GIGC.TO", "GIL.TO", "GIQG.TO", "GIQU.TO", "GLCC.TO", "GLDX.TO", "GLO.TO", "GLXY.TO", "GMIN.TO", "GMTN.TO", "GMX.TO", "GOLD.TO", "GOOS.TO", "GPMD.TO", "GRA.TO", "GRC.TO", "GRCC.TO", "GRGD.TO", "GRID.TO", "GRN.TO", "GRNI.TO", "GRO.TO", "GSY.TO", "GTE.TO", "GTWO.TO", "GUD.TO", "GURU.TO", "GVC.TO", "GWO.TO", "GXE.TO", "H.TO", "HAB.TO", "HAC.TO", "HAD.TO", "HAF.TO", "HAI.TO", "HAL.TO", "HAZ.TO", "HBA.TO", "HBAL.TO", "HBB.TO", "HBD.TO", "HBF.TO", "HBGD.TO", "HBIE.TO", "HBIG.TO", "HBIL.TO", "HBKD.TO", "HBKU.TO", "HBLK.TO", "HBM.TO", "HBND.TO", "HBNK.TO", "HBP.TO", "HBU.TO", "HBUG.TO", "HCA.TO", "HCAL.TO", "HCLN.TO", "HCON.TO", "HCRE.TO", "HDGE.TO", "HDIF.TO", "HDIV.TO", "HEB.TO", "HED.TO", "HEQL.TO", "HEQT.TO", "HERO.TO", "HEU.TO", "HEWB.TO", "HFD.TO", "HFG.TO", "HFIN.TO", "HFR.TO", "HFU.TO", "HGD.TO", "HGGG.TO", "HGR.TO", "HGRW.TO", "HGU.TO", "HGY.TO", "HHL.TO", "HHLE.TO", "HIG.TO", "HIND.TO", "HIU.TO", "HIX.TO", "HLF.TO", "HLIF.TO", "HLIT.TO", "HLPR.TO", "HLS.TO", "HMAX.TO", "HMMJ.TO", "HMP.TO", "HND.TO", "HNU.TO", "HOD.TO", "HOU.TO", "HPF.TO", "HPR.TO", "HPYM.TO", "HPYT.TO", "HQD.TO", "HQU.TO", "HRAA.TO", "HRED.TO", "HREU.TO", "HRIF.TO", "HRX.TO", "HSAV.TO", "HSD.TO", "HSH.TO", "HSU.TO", "HTA.TO","HTAE.TO", "HTB.TO", "HUBL.TO", "HUC.TO", "HUG.TO", "HULC.TO", "HUM.TO", "HUN.TO", "HURA.TO", "HUT.TO", "HUTE.TO", "HUTL.TO", "HUTS.TO", "HUV.TO", "HUZ.TO", "HWO.TO", "HWX.TO", "HXCN.TO", "HXD.TO", "HXDM.TO", "HXE.TO", "HXEM.TO", "HXF.TO", "HXH.TO", "HXQ.TO", "HXS.TO", "HXT.TO", "HXU.TO", "HXX.TO", "HYBR.TO", "HYLD.TO", "HZD.TO", "HZU.TO", "IAG.TO", "IAU.TO", "ICAE.TO", "ICE.TO", "ICPB.TO", "ICTE.TO", "IE.TO", "IFA.TO", "IFC.TO", "IFP.TO", "IFRF.TO", "IGAF.TO", "IGB.TO", "IGEO.TO", "IGET.TO", "IGM.TO", "IIAE.TO", "IICE.TO", "III.TO", "IIMF.TO", "IITE.TO", "ILGB.TO", "ILLM.TO", "IMG.TO", "IMO.TO", "IMP.TO", "INAI.TO", "INCM.TO", "INE.TO", "INOC.TO", "IPCO.TO", "IPO.TO", "IQD.TO", "IS.TO", "ISC.TO", "ISCB.TO", "ISO.TO", "ISTE.TO", "ITH.TO", "IUAE.TO", "IUCE.TO", "IUMF.TO", "IUTE.TO", "IVN.TO", "IVQ.TO", "IWBE.TO", "IXTE.TO", "JAG.TO", "JAPN.TO", "JEPI.TO", "JEPQ.TO", "JOY.TO", "JWEL.TO", "K.TO", "KBL.TO", "KEC.TO", "KEI.TO", "KEL.TO", "KEY.TO", "KILO.TO", "KITS.TO", "KLS.TO", "KNGC.TO", "KNGU.TO", "KNGX.TO", "KNT.TO", "KPT.TO", "KRN.TO", "KSI.TO", "KXS.TO", "L.TO", "LAAC.TO", "LABS.TO", "LAC.TO", "LAM.TO", "LB.TO", "LBS.TO", "LCFS.TO", "LCS.TO", "LEAD.TO", "LFE.TO", "LGD.TO", "LGO.TO", "LIF.TO", "LIFE.TO", "LIRC.TO", "LLHE.TO", "LLYH.TO", "LMAX.TO", "LN.TO", "LNF.TO", "LNR.TO", "LPAY.TO", "LSPD.TO", "LSPK.TO", "LUC.TO", "LUG.TO", "LUN.TO", "LYCT.TO", "LYFR.TO", "MAG.TO", "MAL.TO", "MARI.TO", "MART.TO", "MATR.TO", "MBAL.TO", "MBX.TO", "MCAD.TO", "MCB.TO", "MCLC.TO", "MCLV.TO", "MCON.TO", "MCSB.TO", "MCSM.TO", "MDA.TO", "MDI.TO", "MDIV.TO", "MDNA.TO", "MDP.TO", "MDVD.TO", "MEG.TO", "MEQ.TO", "MEQT.TO", "MFC.TO", "MFI.TO", "MFT.TO", "MG.TO", "MGA.TO", "MGAB.TO", "MGB.TO", "MGDV.TO", "MGQE.TO", "MGRW.TO", "MHCD.TO", "MINF.TO", "MINN.TO", "MINT.TO", "MIQE.TO", "MIVG.TO", "MKB.TO", "MKP.TO", "MND.TO", "MNO.TO", "MNS.TO", "MNT.TO", "MNXT.TO", "MNY.TO", "MOGO.TO", "MORE.TO", "MPAY.TO", "MPC.TO", "MPVD.TO", "MPY.TO", "MRC.TO", "MRD.TO", "MRE.TO", "MREL.TO", "MRU.TO", "MSA.TO", "MSCL.TO", "MSFH.TO", "MSHE.TO", "MSV.TO", "MTAV.TO", "MTL.TO", "MTY.TO", "MUB.TO", "MULC.TO", "MULV.TO", "MUMC.TO", "MUSA.TO", "MUX.TO", "MWLV.TO", "MX.TO", "MXG.TO", "NA.TO", "NALT.TO", "NANO.TO", "NCF.TO", "NDIV.TO", "NDM.TO", "NEO.TO", "NEXT.TO", "NFI.TO", "NG.TO", "NGD.TO", "NGDN.TO", "NGEX.TO", "NGPE.TO", "NGT.TO", "NGUP.TO", "NHYB.TO", "NINT.TO", "NOA.TO", "NPI.TO", "NPK.TO", "NPRF.TO", "NPS.TO", "NREA.TO", "NRGY.TO", "NSCB.TO", "NSCC.TO", "NSCE.TO", "NSGE.TO", "NSSB.TO", "NTR.TO", "NUAG.TO", "NUBF.TO", "NUMI.TO", "NUSA.TO", "NVA.TO", "NVDH.TO", "NVHE.TO", "NVO.TO", "NWC.TO", "NXE.TO", "NXF.TO", "NXTG.TO", "OBE.TO", "OGC.TO", "OGD.TO", "OGI.TO", "OLA.TO", "OLY.TO", "ONC.TO", "ONEB.TO", "ONEC.TO", "ONEQ.TO", "ONEX.TO", "OPT.TO", "OR.TO", "ORA.TO", "ORE.TO", "ORV.TO", "OTEX.TO", "OVV.TO", "PAAS.TO", "PABF.TO", "PACF.TO", "PAGF.TO", "PAY.TO", "PAYF.TO", "PAYL.TO", "PAYM.TO", "PAYS.TO", "PBD.TO", "PBH.TO", "PBI.TO", "PBL.TO", "PCOR.TO", "PD.TO", "PDC.TO", "PDF.TO", "PDIV.TO", "PDN.TO", "PDV.TO", "PEA.TO", "PET.TO", "PEY.TO", "PFAA.TO", "PFAE.TO", "PFCB.TO", "PFIA.TO", "PFL.TO", "PFLS.TO", "PFMN.TO", "PFSS.TO", "PGIC.TO", "PHR.TO", "PHX.TO", "PHYS.TO", "PID.TO", "PIF.TO", "PIN.TO", "PINC.TO", "PKI.TO", "PLDI.TO", "PLV.TO", "PME.TO", "PMET.TO", "PMIF.TO", "PMM.TO", "PMNT.TO", "PNE.TO", "PNP.TO", "POU.TO", "POW.TO", "PPL.TO", "PPLN.TO", "PPR.TO", "PPTA.TO", "PR.TO", "PRA.TO", "PRB.TO", "PREF.TO", "PRL.TO", "PRM.TO", "PRN.TO", "PRQ.TO", "PRU.TO", "PRYM.TO", "PSA.TO", "PSB.TO", "PSD.TO", "PSI.TO", "PSK.TO", "PSLV.TO", "PTM.TO", "PWI.TO", "PXC.TO", "PXS.TO", "PXT.TO", "PYF.TO", "PYR.TO", "PZA.TO", "PZW.TO", "QAH.TO", "QASH.TO", "QBB.TO", "QBTC.TO", "QBTL.TO", "QCE.TO", "QCLN.TO", "QCN.TO", "QDX.TO", "QDXB.TO", "QDXH.TO", "QEBH.TO", "QEBL.TO", "QEC.TO", "QEE.TO", "QHY.TO", "QIE.TO", "QINF.TO", "QIPT.TO", "QLB.TO", "QMAX.TO", "QQC.TO", "QQCC.TO", "QQCE.TO", "QQCI.TO", "QQCL.TO", "QQEQ.TO", "QQJE.TO", "QQJR.TO", "QQQL.TO", "QQQT.TO", "QQQX.TO", "QQQY.TO", "QRC.TO", "QRET.TO", "QSB.TO", "QSR.TO", "QTLT.TO", "QTRH.TO", "QUB.TO", "QUIG.TO", "QUS.TO", "QUU.TO", "QXM.TO", "RAAA.TO", "RATE.TO", "RBA.TO", "RBNK.TO", "RBO.TO", "RBOT.TO", "RBY.TO", "RCD.TO", "RCDC.TO", "RCG.TO", "RCH.TO", "RDBH.TO", "REAL.TO", "RGQN.TO", "RGQO.TO", "RGQP.TO", "RGQQ.TO", "RGQR.TO", "RGQS.TO", "RID.TO", "RIDH.TO", "RIFI.TO", "RIIN.TO", "RING.TO", "RIRA.TO", "RIT.TO", "RLB.TO", "RMAX.TO", "ROOT.TO", "RPD.TO", "RPDH.TO", "RPF.TO", "RPSB.TO", "RQN.TO", "RQO.TO", "RQP.TO", "RQQ.TO", "RQR.TO", "RQS.TO", "RS.TO", "RSI.TO", "RTG.TO", "RUBH.TO", "RUBY.TO", "RUD.TO", "RUDB.TO", "RUDC.TO", "RUDH.TO", "RUP.TO", "RUQN.TO", "RUQO.TO", "RUQQ.TO", "RUQR.TO", "RUQS.TO", "RUS.TO", "RUSB.TO", "RVX.TO", "RXD.TO", "RY.TO", "S.TO", "SAFE.TO", "SAM.TO", "SAP.TO", "SAU.TO", "SBC.TO", "SBI.TO", "SBT.TO", "SCR.TO", "SCY.TO", "SDE.TO", "SEA.TO", "SEC.TO", "SES.TO", "SFC.TO", "SFD.TO", "SFI.TO", "SFTC.TO", "SGLD.TO", "SGY.TO", "SHLE.TO", "SHOP.TO", "SIA.TO", "SII.TO", "SIL.TO", "SIS.TO", "SJ.TO", "SKE.TO", "SKYY.TO", "SLF.TO", "SLR.TO", "SLS.TO", "SMAX.TO", "SMC.TO", "SMT.TO", "SOBO.TO", "SOIL.TO", "SOLG.TO", "SOY.TO", "SPAY.TO", "SPB.TO", "SPFD.TO", "SPLT.TO", "SPPP.TO", "SSL.TO", "SSRM.TO", "STC.TO", "STCK.TO", "STEP.TO", "STGO.TO", "STLR.TO", "STN.TO", "STPL.TO", "SU.TO", "SVA.TO", "SVB.TO", "SVI.TO", "SVM.TO", "SVR.TO", "SWP.TO", "SXI.TO", "SXP.TO", "SYLD.TO", "SYZ.TO", "T.TO", "TA.TO", "TAL.TO", "TBAL.TO", "TBCE.TO", "TBCF.TO", "TBCG.TO", "TBIL.TO", "TBL.TO", "TBNK.TO", "TC.TO", "TCBN.TO", "TCLB.TO", "TCLV.TO", "TCON.TO", "TCS.TO", "TCSB.TO", "TCSH.TO", "TCW.TO", "TD.TO", "TDB.TO", "TDOC.TO", "TEC.TO", "TECH.TO", "TECI.TO", "TECX.TO", "TERM.TO", "TF.TO", "TFII.TO", "TFPM.TO", "TGAF.TO", "TGED.TO", "TGFI.TO", "TGGR.TO", "TGO.TO", "TGRE.TO", "TGRO.TO", "TH.TO", "The.TO", "THNC.TO", "THU.TO", "TI.TO", "TIH.TO", "TILV.TO", "TINF.TO", "TIPS.TO", "TIXT.TO", "TKN.TO", "TKO.TO", "TLF.TO", "TLG.TO", "TLO.TO", "TLRY.TO", "TLV.TO", "TMQ.TO", "TNZ.TO", "TOT.TO", "TOU.TO", "TOWR.TO", "TOY.TO", "TPE.TO", "TPRF.TO", "TPU.TO", "TPZ.TO", "TQCD.TO", "TQGD.TO", "TQGM.TO", "TQSM.TO", "TRI.TO", "TRP.TO", "TRVI.TO", "TRVL.TO", "TRX.TO", "TRZ.TO", "TSAT.TO", "TSK.TO", "TSL.TO", "TSND.TO", "TSU.TO", "TTNM.TO", "TTP.TO", "TTTX.TO", "TUED.TO", "TUEX.TO", "TUHY.TO", "TULB.TO", "TULV.TO", "TUSB.TO", "TVE.TO", "TVK.TO", "TWC.TO", "TWM.TO", "TXF.TO", "TXG.TO", "TXP.TO", "UDA.TO", "UDIV.TO", "UMAX.TO", "UMI.TO", "UNC.TO", "UNI.TO", "URB.TO", "URC.TO", "URE.TO", "USA.TO", "USCC.TO", "USCL.TO", "USSL.TO", "USSX.TO", "UTES.TO", "UTIL.TO", "VA.TO", "VAB.TO", "VALT.TO", "VBAL.TO", "VBNK.TO", "VCB.TO", "VCE.TO", "VCIP.TO", "VCM.TO", "VCN.TO", "VCNS.TO", "VDU.TO", "VDY.TO", "VE.TO", "VEE.TO", "VEF.TO", "VEQT.TO", "VET.TO", "VFV.TO", "VGG.TO", "VGH.TO", "VGRO.TO", "VGV.TO", "VGZ.TO", "VHI.TO", "VI.TO", "VIDY.TO", "VIU.TO", "VLB.TO", "VLE.TO", "VLN.TO", "VMO.TO", "VNP.TO", "VOXR.TO", "VQS.TO", "VRE.TO", "VRIF.TO", "VRN.TO", "VRTS.TO", "VSB.TO", "VSC.TO", "VSP.TO", "VUN.TO", "VUS.TO", "VVL.TO", "VVO.TO", "VVSG.TO", "VXC.TO", "VXM.TO", "VZLA.TO", "WCN.TO", "WCP.TO", "WDO.TO", "WEED.TO", "WEF.TO", "WELL.TO", "WFC.TO", "WFG.TO", "WGX.TO", "WILD.TO", "WJX.TO", "WLLW.TO", "WM.TO", "WN.TO", "WNDR.TO", "WOMN.TO", "WPK.TO", "WPM.TO", "WPRT.TO", "WRG.TO", "WRN.TO", "WRX.TO", "WSP.TO", "WSRD.TO", "WSRI.TO", "WTE.TO", "WXM.TO", "X.TO", "XAD.TO", "XAGG.TO", "XAGH.TO", "XAM.TO", "XAU.TO", "XAW.TO", "XBAL.TO", "XBB.TO", "XBM.TO", "XCB.TO", "XCBG.TO", "XCBU.TO", "XCD.TO", "XCG.TO", "XCH.TO", "XCHP.TO", "XCLN.TO", "XCNS.TO", "XCS.TO", "XCSR.TO", "XCV.TO", "XDG.TO", "XDGH.TO", "XDIV.TO", "XDNA.TO", "XDRV.TO", "XDSR.TO", "XDU.TO", "XDUH.TO", "XDV.TO", "XEB.TO", "XEC.TO", "XEF.TO", "XEG.TO", "XEH.TO", "XEI.TO", "XEM.TO", "XEMC.TO", "XEN.TO", "XEQT.TO", "XESG.TO", "XETM.TO", "XEU.TO", "XEXP.TO", "XFH.TO", "XFLB.TO", "XFLI.TO", "XFLX.TO", "XFN.TO", "XFR.TO", "XGB.TO", "XGD.TO", "XGI.TO", "XGRO.TO", "XHAK.TO", "XHB.TO", "XHC.TO", "XHD.TO", "XHU.TO", "XHY.TO", "XIC.TO", "XID.TO", "XIG.TO", "XIGS.TO", "XIN.TO", "XINC.TO", "XIT.TO", "XIU.TO", "XLB.TO", "XLY.TO", "XMA.TO", "XMC.TO", "XMD.TO", "XMH.TO", "XMI.TO", "XML.TO", "XMM.TO", "XMS.TO", "XMTM.TO", "XMU.TO", "XMV.TO", "XMW.TO", "XMY.TO", "XPF.TO", "XQB.TO", "XQLT.TO", "XQQ.TO", "XQQU.TO", "XRB.TO", "XRE.TO", "XSAB.TO", "XSB.TO", "XSC.TO", "XSE.TO", "XSEA.TO", "XSEM.TO", "XSH.TO", "XSHG.TO", "XSHU.TO", "XSI.TO", "XSMC.TO", "XSMH.TO", "XSP.TO", "XSPC.TO", "XST.TO", "XSTB.TO", "XSTH.TO", "XSTP.TO", "XSU.TO", "XSUS.TO", "XTC.TO", "XTD.TO", "XTG.TO", "XTLH.TO", "XTLT.TO", "XTR.TO", "XTRA.TO", "XUH.TO", "XUS.TO", "XUSC.TO", "XUSF.TO", "XUSR.TO", "XUT.TO", "XUU.TO", "XVLU.TO", "XWD.TO", "Y.TO", "YCM.TO", "YGR.TO", "YRB.TO", "ZACE.TO", "ZAG.TO", "ZBAL.TO", "ZBBB.TO", "ZBI.TO", "ZBK.TO", "ZCB.TO", "ZCDB.TO", "ZCH.TO", "ZCLN.TO", "ZCM.TO", "ZCN.TO", "ZCON.TO", "ZCPB.TO", "ZCS.TO", "ZDB.TO", "ZDH.TO", "ZDI.TO", "ZDJ.TO", "ZDM.TO", "ZDV.TO", "ZDY.TO", "ZEA.TO", "ZEAT.TO", "ZEB.TO", "ZEF.TO", "ZEM.TO", "ZEO.TO", "ZEQ.TO", "ZEQT.TO", "ZESG.TO", "ZFC.TO", "ZFH.TO", "ZFL.TO", "ZFM.TO", "ZFN.TO", "ZFS.TO", "ZGB.TO", "ZGD.TO", "ZGI.TO", "ZGLD.TO", "ZGLH.TO", "ZGQ.TO", "ZGRN.TO", "ZGRO.TO", "ZGSB.TO", "ZHP.TO", "ZHU.TO", "ZHY.TO", "ZIC.TO", "ZID.TO", "ZIN.TO", "ZIQ.TO", "ZIU.TO", "ZJG.TO", "ZJK.TO", "ZJPN.TO", "ZLB.TO", "ZLC.TO", "ZLD.TO", "ZLE.TO", "ZLH.TO", "ZLI.TO", "ZLSC.TO", "ZLSU.TO", "ZLU.TO", "ZMBS.TO", "ZMI.TO", "ZMID.TO", "ZMMK.TO", "ZMP.TO", "ZMSB.TO", "ZMT.TO", "ZMU.TO", "ZNQ.TO", "ZPAY.TO", "ZPH.TO", "ZPL.TO", "ZPR.TO", "ZPS.TO", "ZPW.TO", "ZQB.TO", "ZQQ.TO", "ZRE.TO", "ZRR.TO", "ZSB.TO", "ZSDB.TO", "ZSML.TO", "ZSP.TO", "ZST.TO", "ZSU.TO", "ZTIP.TO", "ZUAG.TO", "ZUB.TO", "ZUCM.TO", "ZUD.TO", "ZUE.TO", "ZUGE.TO", "ZUH.TO", "ZUP.TO", "ZUQ.TO", "ZUT.TO", "ZVC.TO", "ZVU.TO", "ZWA.TO", "ZWB.TO", "ZWC.TO", "ZWE.TO", "ZWEN.TO", "ZWG.TO", "ZWH.TO", "ZWHC.TO", "ZWK.TO", "ZWP.TO", "ZWQT.TO", "ZWS.TO", "ZWT.TO", "ZWU.TO", "ZXM.TO", "ZZZD.TO"
]
print(len(FIRST_SET_TICKERS))

1637

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
import yfinance as yf
import pandas as pd
import time

# Function to fetch historical data for a list of tickers
def fetch_all_historical_data(ticker_list, start_date, end_date, requests_per_minute=100):
    data = []
    delay = 60 / requests_per_minute  # Calculate delay to respect rate limits

    for i, ticker in enumerate(ticker_list):
        try:
            print(f"Fetching data for: {ticker}")
            # Download historical data for the ticker
            ticker_data = yf.download(ticker, start=start_date, end=end_date, progress=False)

            # Check if data is empty
            if ticker_data.empty:
                print(f"Warning: No data found for {ticker}")
                continue

            # Add a 'tic' column with the ticker symbol
            ticker_data['tic'] = ticker
            ticker_data.reset_index(inplace=True)  # Reset index to bring 'Date' as a column

            # Select only the required columns
            ticker_data = ticker_data[['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'tic']]

            # Add day of the week
            ticker_data['day'] = pd.to_datetime(ticker_data['Date']).dt.dayofweek

            # Rename columns to lowercase
            ticker_data.columns = ['date', 'close', 'high', 'low', 'open', 'volume', 'tic', 'day']

            # Append to the data list
            data.append(ticker_data)

        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")

        # Delay to respect the request limit
        if i < len(ticker_list) - 1:
            time.sleep(delay)

    # Combine all data into a single DataFrame
    if not data:
        print("Error: No data found for any of the specified tickers.")
        return pd.DataFrame()
    else:
        combined_data = pd.concat(data, ignore_index=True)

        # Sort by 'date' and 'tic'
        sorted_data = combined_data.sort_values(by=['date', 'tic'], ascending=[True, True])
        return sorted_data

# Example usage
ticker_list = FIRST_SET_TICKERS
start_date = "2004-01-01"
end_date = "2024-12-31"

# Fetch historical data
historical_data = fetch_all_historical_data(
    ticker_list=ticker_list,
    start_date=start_date,
    end_date=end_date,
    requests_per_minute=100
)

# Verify the shape and columns
print("DataFrame columns:", historical_data.columns.tolist())
print("DataFrame shape:", historical_data.shape)
print("\nFirst few rows:")
print(historical_data.head())

Fetching data for: AAB.TO
Fetching data for: AAUC.TO
Fetching data for: AAV.TO
Fetching data for: ABX.TO
Fetching data for: AC.TO
Fetching data for: ACAA.TO
Fetching data for: ACB.TO
Fetching data for: ACD.TO
Fetching data for: ACQ.TO
Fetching data for: ACX.TO
Fetching data for: ADCO.TO
Fetching data for: ADEN.TO
Fetching data for: ADIV.TO
Fetching data for: ADN.TO
Fetching data for: AEG.TO
Fetching data for: AEM.TO
Fetching data for: AFN.TO
Fetching data for: AG.TO
Fetching data for: AGG.TO
Fetching data for: AGI.TO
Fetching data for: AI.TO
Fetching data for: AIDX.TO
Fetching data for: AIF.TO
Fetching data for: AIGO.TO
Fetching data for: AII.TO
Fetching data for: AIM.TO
Fetching data for: ALA.TO
Fetching data for: ALC.TO
Fetching data for: ALS.TO
Fetching data for: ALYA.TO
Fetching data for: AMAX.TO
Fetching data for: AMC.TO
Fetching data for: AMHE.TO
Fetching data for: AMM.TO
Fetching data for: AMZH.TO
Fetching data for: AND.TO
Fetching data for: ANRG.TO
Fetching data for: AOI.TO
Fetching data for: AOT.TO
Fetching data for: APLI.TO
Fetching data for: APM.TO

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['APM.TO']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2004-01-01 -> 2024-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 1072933200, endDate = 1735621200")')

Warning: No data found for APM.TO
Fetching data for: APS.TO
Fetching data for: AQN.TO
Fetching data for: ARA.TO
Fetching data for: ARB.TO
Fetching data for: ARE.TO
Fetching data for: ARG.TO
Fetching data for: ARIS.TO
Fetching data for: ARTI.TO
Fetching data for: ARX.TO
Fetching data for: ASCU.TO
Fetching data for: ASM.TO
Fetching data for: ASND.TO
Fetching data for: ASTL.TO
Fetching data for: ATCU.TO
Fetching data for: ATD.TO
Fetching data for: ATH.TO
Fetching data for: ATRL.TO
Fetching data for: ATS.TO
Fetching data for: ATSX.TO
Fetching data for: ATZ.TO
Fetching data for: AUMN.TO
Fetching data for: AVCN.TO
Fetching data for: AVL.TO
Fetching data for: AVNT.TO
Fetching data for: AW.TO
Fetching data for: AYA.TO
Fetching data for: BABY.TO
Fetching data for: BAM.TO
Fetching data for: BANK.TO
Fetching data for: BASE.TO
Fetching data for: BB.TO
Fetching data for: BBUC.TO
Fetching data for: BCE.TO
Fetching data for: BCHT.TO
Fetching data for: BCT.TO
Fetching data for: BDGI.TO
Fetching data for: BDI.TO
Fetching data for: BDIV.TO
Fetching data for: BDT.TO
Fetching data for: BEPC.TO
Fetching data for: BEPR.TO
Fetching data for: BESG.TO
Fetching data for: BFIN.TO
Fetching data for: BGC.TO
Fetching data for: BGU.TO
Fetching data for: BHC.TO
Fetching data for: BIPC.TO
Fetching data for: BIR.TO
Fetching data for: BITF.TO
Fetching data for: BITI.TO
Fetching data for: BK.TO
Fetching data for: BKCC.TO
Fetching data for: BKCL.TO
Fetching data for: BKI.TO
Fetching data for: BLCO.TO
Fetching data for: BLDP.TO
Fetching data for: BLN.TO
Fetching data for: BLOV.TO
Fetching data for: BLX.TO
Fetching data for: BMAX.TO
Fetching data for: BMO.TO
Fetching data for: BN.TO
Fetching data for: BNC.TO
Fetching data for: BND.TO
Fetching data for: BNE.TO
Fetching data for: BNG.TO
Fetching data for: BNK.TO
Fetching data for: BNKL.TO
Fetching data for: BNS.TO
Fetching data for: BNT.TO
Fetching data for: BOND.TO
Fetching data for: BOS.TO
Fetching data for: BPRF.TO
Fetching data for: BR.TO
Fetching data for: BRAG.TO
Fetching data for: BRE.TO
Fetching data for: BREA.TO
Fetching data for: BRMI.TO
Fetching data for: BRY.TO
Fetching data for: BSKT.TO
Fetching data for: BSX.TO
Fetching data for: BTCC.TO
Fetching data for: BTCQ.TO
Fetching data for: BTCY.TO
Fetching data for: BTE.TO
Fetching data for: BTO.TO
Fetching data for: BU.TO
Fetching data for: BUI.TO
Fetching data for: BXF.TO
Fetching data for: BYD.TO
Fetching data for: BYL.TO
Fetching data for: CACB.TO
Fetching data for: CAE.TO
Fetching data for: CAFR.TO
Fetching data for: CAGG.TO
Fetching data for: CAGS.TO
Fetching data for: CALL.TO
Fetching data for: CANL.TO
Fetching data for: CAPG.TO
Fetching data for: CAPI.TO
Fetching data for: CAPM.TO
Fetching data for: CAPW.TO
Fetching data for: CARB.TO
Fetching data for: CARS.TO
Fetching data for: CAS.TO
Fetching data for: CASH.TO
Fetching data for: CBAL.TO
Fetching data for: CBCX.TO
Fetching data for: CBGR.TO
Fetching data for: CBH.TO
Fetching data for: CBIL.TO
Fetching data for: CBIN.TO
Fetching data for: CBL.TO
Fetching data for: CBND.TO
Fetching data for: CBNK.TO
Fetching data for: CBO.TO
Fetching data for: CBUG.TO
Fetching data for: CCA.TO
Fetching data for: CCBI.TO
Fetching data for: CCEI.TO
Fetching data for: CCM.TO
Fetching data for: CCNS.TO
Fetching data for: CCNV.TO
Fetching data for: CCO.TO
Fetching data for: CCOM.TO
Fetching data for: CCRE.TO
Fetching data for: CDEF.TO
Fetching data for: CDIV.TO
Fetching data for: CDLB.TO
Fetching data for: CDNA.TO
Fetching data for: CDR.TO
Fetching data for: CDZ.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'CDZ.TO' reason: 'chart'
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['CDZ.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Warning: No data found for CDZ.TO
Fetching data for: CEF.TO
Fetching data for: CEMI.TO
Fetching data for: CEMX.TO
Fetching data for: CEQT.TO
Fetching data for: CEU.TO
Fetching data for: CEW.TO
Fetching data for: CF.TO
Fetching data for: CFF.TO
Fetching data for: CFLX.TO
Fetching data for: CFP.TO
Fetching data for: CFRT.TO
Fetching data for: CFW.TO
Fetching data for: CFX.TO
Fetching data for: CG.TO
Fetching data for: CGAA.TO
Fetching data for: CGBI.TO
Fetching data for: CGDV.TO
Fetching data for: CGG.TO
Fetching data for: CGHY.TO
Fetching data for: CGI.TO
Fetching data for: CGIN.TO
Fetching data for: CGL.TO
Fetching data for: CGLO.TO
Fetching data for: CGO.TO
Fetching data for: CGR.TO
Fetching data for: CGRA.TO
Fetching data for: CGRE.TO
Fetching data for: CGRN.TO
Fetching data for: CGRO.TO
Fetching data for: CGX.TO
Fetching data for: CGXF.TO
Fetching data for: CGY.TO
Fetching data for: CHPS.TO
Fetching data for: CHR.TO
Fetching data for: CIA.TO
Fetching data for: CIAI.TO
Fetching data for: CIBR.TO
Fetching data for: CIC.TO
Fetching data for: CIEH.TO
Fetching data for: CIEI.TO
Fetching data for: CIEM.TO
Fetching data for: CIF.TO
Fetching data for: CIGI.TO
Fetching data for: CINF.TO
Fetching data for: CINT.TO
Fetching data for: CINV.TO
Fetching data for: CIX.TO
Fetching data for: CJ.TO
Fetching data for: CJT.TO
Fetching data for: CKI.TO
Fetching data for: CLF.TO
Fetching data for: CLG.TO
Fetching data for: CLML.TO
Fetching data for: CLS.TO
Fetching data for: CM.TO
Fetching data for: CMAG.TO
Fetching data for: CMAR.TO
Fetching data for: CMDO.TO
Fetching data for: CMG.TO
Fetching data for: CMGG.TO
Fetching data for: CMNY.TO
Fetching data for: CMOM.TO
Fetching data for: CMR.TO
Fetching data for: CMVX.TO
Fetching data for: CNCC.TO
Fetching data for: CNCL.TO
Fetching data for: CNDX.TO
Fetching data for: CNE.TO
Fetching data for: CNL.TO
Fetching data for: CNQ.TO
Fetching data for: CNR.TO
Fetching data for: CNT.TO
Fetching data for: CNV.TO
Fetching data for: COG.TO
Fetching data for: COMM.TO
Fetching data for: COPP.TO
Fetching data for: COPR.TO
Fetching data for: CORE.TO
Fetching data for: COW.TO
Fetching data for: CP.TO
Fetching data for: CPD.TO
Fetching data for: CPH.TO
Fetching data for: CPLS.TO
Fetching data for: CPX.TO
Fetching data for: CRDL.TO
Fetching data for: CRED.TO
Fetching data for: CRON.TO
Fetching data for: CROP.TO
Fetching data for: CRP.TO
Fetching data for: CRRX.TO
Fetching data for: CRWN.TO
Fetching data for: CS.TO
Fetching data for: CSAV.TO
Fetching data for: CSBI.TO
Fetching data for: CSCI.TO
Fetching data for: CSU.TO
Fetching data for: CTC.TO
Fetching data for: CTS.TO
Fetching data for: CTX.TO
Fetching data for: CU.TO
Fetching data for: CUBD.TO
Fetching data for: CUD.TO
Fetching data for: CUDV.TO
Fetching data for: CUEH.TO
Fetching data for: CUEI.TO
Fetching data for: CURA.TO
Fetching data for: CUTL.TO
Fetching data for: CVD.TO
Fetching data for: CVE.TO
Fetching data for: CVG.TO
Fetching data for: CVLU.TO
Fetching data for: CVO.TO
Fetching data for: CWB.TO
Fetching data for: CWEB.TO
Fetching data for: CWL.TO
Fetching data for: CWW.TO
Fetching data for: CXB.TO
Fetching data for: CXF.TO
Fetching data for: CXI.TO
Fetching data for: CYB.TO
Fetching data for: CYBR.TO
Fetching data for: CYH.TO
Fetching data for: DAMG.TO
Fetching data for: DANC.TO
Fetching data for: DATA.TO
Fetching data for: DAY.TO
Fetching data for: DBM.TO
Fetching data for: DBO.TO
Fetching data for: DCBC.TO
Fetching data for: DCBO.TO
Fetching data for: DCC.TO
Fetching data for: DCG.TO
Fetching data for: DCM.TO
Fetching data for: DCP.TO
Fetching data for: DCS.TO
Fetching data for: DCU.TO
Fetching data for: DF.TO
Fetching data for: DFN.TO
Fetching data for: DFY.TO
Fetching data for: DGR.TO
Fetching data for: DGRC.TO
Fetching data for: DGS.TO
Fetching data for: DIAM.TO
Fetching data for: DISC.TO
Fetching data for: DIV.TO
Fetching data for: DIVS.TO
Fetching data for: DLCG.TO
Fetching data for: DLR.TO
Fetching data for: DMEC.TO
Fetching data for: DMEI.TO
Fetching data for: DMEU.TO
Fetching data for: DML.TO
Fetching data for: DND.TO
Fetching data for: DNG.TO
Fetching data for: DNTL.TO
Fetching data for: DOL.TO
Fetching data for: DOO.TO
Fetching data for: DPM.TO
Fetching data for: DR.TO
Fetching data for: DRCU.TO
Fetching data for: DRFC.TO
Fetching data for: DRFD.TO
Fetching data for: DRFE.TO
Fetching data for: DRFG.TO
Fetching data for: DRFU.TO
Fetching data for: DRM.TO
Fetching data for: DRMC.TO
Fetching data for: DRMD.TO
Fetching data for: DRME.TO
Fetching data for: DRMU.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'DRMU.TO' reason: 'chart'
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['DRMU.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Warning: No data found for DRMU.TO
Fetching data for: DRT.TO
Fetching data for: DRX.TO
Fetching data for: DS.TO
Fetching data for: DSAE.TO
Fetching data for: DSG.TO
Fetching data for: DSV.TO
Fetching data for: DTOL.TO
Fetching data for: DXAU.TO
Fetching data for: DXB.TO
Fetching data for: DXBB.TO
Fetching data for: DXBC.TO
Fetching data for: DXBG.TO
Fetching data for: DXBU.TO
Fetching data for: DXC.TO
Fetching data for: DXCB.TO
Fetching data for: DXCO.TO
Fetching data for: DXCP.TO
Fetching data for: DXDB.TO
Fetching data for: DXEM.TO
Fetching data for: DXET.TO
Fetching data for: DXF.TO
Fetching data for: DXG.TO
Fetching data for: DXGE.TO
Fetching data for: DXIF.TO
Fetching data for: DXMO.TO
Fetching data for: DXN.TO
Fetching data for: DXO.TO
Fetching data for: DXP.TO
Fetching data for: DXQ.TO
Fetching data for: DXR.TO
Fetching data for: DXT.TO
Fetching data for: DXU.TO
Fetching data for: DXUS.TO
Fetching data for: DXV.TO
Fetching data for: DXW.TO
Fetching data for: DXZ.TO
Fetching data for: DYA.TO
Fetching data for: E.TO
Fetching data for: EAGR.TO
Fetching data for: EARN.TO
Fetching data for: EBIT.TO
Fetching data for: EBNK.TO
Fetching data for: ECN.TO
Fetching data for: ECO.TO
Fetching data for: ECOR.TO
Fetching data for: EDGE.TO
Fetching data for: EDGF.TO
Fetching data for: EDR.TO
Fetching data for: EDT.TO
Fetching data for: EDV.TO
Fetching data for: EFN.TO
Fetching data for: EFR.TO
Fetching data for: EFX.TO
Fetching data for: EGLX.TO
Fetching data for: EIF.TO
Fetching data for: ELD.TO
Fetching data for: ELEF.TO
Fetching data for: ELF.TO
Fetching data for: ELO.TO
Fetching data for: ELR.TO
Fetching data for: ELVA.TO
Fetching data for: EMA.TO
Fetching data for: EMAX.TO
Fetching data for: ENB.TO
Fetching data for: ENCC.TO
Fetching data for: ENCL.TO
Fetching data for: ENGH.TO
Fetching data for: ENS.TO
Fetching data for: EPRX.TO
Fetching data for: EQB.TO
Fetching data for: EQCC.TO
Fetching data for: EQCL.TO
Fetching data for: EQL.TO
Fetching data for: EQLI.TO
Fetching data for: EQX.TO
Fetching data for: ERD.TO
Fetching data for: ERO.TO
Fetching data for: ESG.TO
Fetching data for: ESGA.TO
Fetching data for: ESGB.TO
Fetching data for: ESGC.TO
Fetching data for: ESGE.TO
Fetching data for: ESGF.TO
Fetching data for: ESGG.TO
Fetching data for: ESGH.TO
Fetching data for: ESGY.TO
Fetching data for: ESI.TO
Fetching data for: ESM.TO
Fetching data for: ESP.TO
Fetching data for: ESPX.TO
Fetching data for: ET.TO
Fetching data for: ETC.TO
Fetching data for: ETG.TO
Fetching data for: ETHH.TO
Fetching data for: ETHI.TO
Fetching data for: ETHQ.TO
Fetching data for: ETHR.TO
Fetching data for: ETHY.TO
Fetching data for: ETP.TO
Fetching data for: ETSX.TO
Fetching data for: EVO.TO
Fetching data for: EVT.TO
Fetching data for: EXE.TO
Fetching data for: EXN.TO
Fetching data for: EXRO.TO
Fetching data for: FAP.TO
Fetching data for: FAR.TO
Fetching data for: FBGO.TO
Fetching data for: FBT.TO
Fetching data for: FBTC.TO
Fetching data for: FC.TO
Fetching data for: FCCD.TO
Fetching data for: FCCQ.TO
Fetching data for: FCCV.TO
Fetching data for: FCEM.TO
Fetching data for: FCGI.TO
Fetching data for: FCID.TO
Fetching data for: FCII.TO
Fetching data for: FCIQ.TO
Fetching data for: FCIV.TO
Fetching data for: FCMI.TO
Fetching data for: FCQH.TO
Fetching data for: FCRR.TO
Fetching data for: FCUD.TO
Fetching data for: FCUH.TO
Fetching data for: FCUQ.TO
Fetching data for: FCUV.TO
Fetching data for: FCVH.TO
Fetching data for: FDL.TO
Fetching data for: FDN.TO
Fetching data for: FDY.TO
Fetching data for: FEC.TO
Fetching data for: FETH.TO
Fetching data for: FF.TO
Fetching data for: FFH.TO
Fetching data for: FFM.TO
Fetching data for: FFN.TO
Fetching data for: FGB.TO
Fetching data for: FGEB.TO
Fetching data for: FGEP.TO
Fetching data for: FGGE.TO
Fetching data for: FGO.TO
Fetching data for: FGOV.TO
Fetching data for: FGRW.TO
Fetching data for: FHG.TO
Fetching data for: FHH.TO
Fetching data for: FHI.TO
Fetching data for: FHIS.TO
Fetching data for: FHQ.TO
Fetching data for: FIE.TO
Fetching data for: FIG.TO
Fetching data for: FIL.TO
Fetching data for: FINC.TO
Fetching data for: FINE.TO
Fetching data for: FINO.TO
Fetching data for: FLCI.TO
Fetching data for: FLCP.TO
Fetching data for: FLGA.TO
Fetching data for: FLI.TO
Fetching data for: FLNT.TO
Fetching data for: FLOW.TO
Fetching data for: FLSD.TO
Fetching data for: FLUS.TO
Fetching data for: FLX.TO
Fetching data for: FM.TO
Fetching data for: FMAX.TO
Fetching data for: FN.TO
Fetching data for: FNV.TO
Fetching data for: FOM.TO
Fetching data for: FOOD.TO
Fetching data for: FORA.TO
Fetching data for: FOUR.TO
Fetching data for: FPR.TO
Fetching data for: FRU.TO
Fetching data for: FRX.TO
Fetching data for: FSB.TO
Fetching data for: FSF.TO
Fetching data for: FSL.TO
Fetching data for: FST.TO
Fetching data for: FSV.TO
Fetching data for: FSY.TO
Fetching data for: FSZ.TO
Fetching data for: FT.TO
Fetching data for: FTG.TO
Fetching data for: FTHI.TO
Fetching data for: FTN.TO
Fetching data for: FTS.TO
Fetching data for: FTT.TO
Fetching data for: FTU.TO
Fetching data for: FURY.TO
Fetching data for: FVI.TO
Fetching data for: FVL.TO
Fetching data for: FXM.TO
Fetching data for: G.TO
Fetching data for: GATO.TO
Fetching data for: GAU.TO
Fetching data for: GBAL.TO
Fetching data for: GBT.TO
Fetching data for: GCBD.TO
Fetching data for: GCFE.TO
Fetching data for: GCG.TO
Fetching data for: GCL.TO
Fetching data for: GCNS.TO
Fetching data for: GCSC.TO
Fetching data for: GCTB.TO
Fetching data for: GCU.TO
Fetching data for: GDC.TO
Fetching data for: GDEP.TO
Fetching data for: GDI.TO
Fetching data for: GDL.TO
Fetching data for: GDPY.TO
Fetching data for: GDV.TO
Fetching data for: GEC.TO
Fetching data for: GEI.TO
Fetching data for: GENM.TO
Fetching data for: GEO.TO
Fetching data for: GEQT.TO
Fetching data for: GFL.TO
Fetching data for: GFP.TO
Fetching data for: GFR.TO
Fetching data for: GGD.TO
Fetching data for: GGRO.TO
Fetching data for: GH.TO
Fetching data for: GIGC.TO
Fetching data for: GIL.TO
Fetching data for: GIQG.TO
Fetching data for: GIQU.TO
Fetching data for: GLCC.TO
Fetching data for: GLDX.TO
Fetching data for: GLO.TO
Fetching data for: GLXY.TO
Fetching data for: GMIN.TO
Fetching data for: GMTN.TO
Fetching data for: GMX.TO
Fetching data for: GOLD.TO
Fetching data for: GOOS.TO
Fetching data for: GPMD.TO
Fetching data for: GRA.TO
Fetching data for: GRC.TO
Fetching data for: GRCC.TO
Fetching data for: GRGD.TO
Fetching data for: GRID.TO
Fetching data for: GRN.TO
Fetching data for: GRNI.TO
Fetching data for: GRO.TO
Fetching data for: GSY.TO
Fetching data for: GTE.TO
Fetching data for: GTWO.TO
Fetching data for: GUD.TO
Fetching data for: GURU.TO
Fetching data for: GVC.TO
Fetching data for: GWO.TO
Fetching data for: GXE.TO
Fetching data for: H.TO
Fetching data for: HAB.TO
Fetching data for: HAC.TO
Fetching data for: HAD.TO
Fetching data for: HAF.TO
Fetching data for: HAI.TO
Fetching data for: HAL.TO
Fetching data for: HAZ.TO
Fetching data for: HBA.TO
Fetching data for: HBAL.TO
Fetching data for: HBB.TO
Fetching data for: HBD.TO
Fetching data for: HBF.TO
Fetching data for: HBGD.TO
Fetching data for: HBIE.TO
Fetching data for: HBIG.TO
Fetching data for: HBIL.TO
Fetching data for: HBKD.TO
Fetching data for: HBKU.TO
Fetching data for: HBLK.TO
Fetching data for: HBM.TO
Fetching data for: HBND.TO
Fetching data for: HBNK.TO
Fetching data for: HBP.TO
Fetching data for: HBU.TO
Fetching data for: HBUG.TO
Fetching data for: HCA.TO
Fetching data for: HCAL.TO
Fetching data for: HCLN.TO
Fetching data for: HCON.TO
Fetching data for: HCRE.TO
Fetching data for: HDGE.TO
Fetching data for: HDIF.TO
Fetching data for: HDIV.TO
Fetching data for: HEB.TO
Fetching data for: HED.TO
Fetching data for: HEQL.TO
Fetching data for: HEQT.TO
Fetching data for: HERO.TO
Fetching data for: HEU.TO
Fetching data for: HEWB.TO
Fetching data for: HFD.TO
Fetching data for: HFG.TO
Fetching data for: HFIN.TO
Fetching data for: HFR.TO
Fetching data for: HFU.TO
Fetching data for: HGD.TO
Fetching data for: HGGG.TO
Fetching data for: HGR.TO
Fetching data for: HGRW.TO
Fetching data for: HGU.TO
Fetching data for: HGY.TO
Fetching data for: HHL.TO
Fetching data for: HHLE.TO
Fetching data for: HIG.TO
Fetching data for: HIND.TO
Fetching data for: HIU.TO
Fetching data for: HIX.TO
Fetching data for: HLF.TO
Fetching data for: HLIF.TO
Fetching data for: HLIT.TO
Fetching data for: HLPR.TO
Fetching data for: HLS.TO
Fetching data for: HMAX.TO
Fetching data for: HMMJ.TO
Fetching data for: HMP.TO
Fetching data for: HND.TO
Fetching data for: HNU.TO
Fetching data for: HOD.TO
Fetching data for: HOU.TO
Fetching data for: HPF.TO
Fetching data for: HPR.TO
Fetching data for: HPYM.TO
Fetching data for: HPYT.TO
Fetching data for: HQD.TO
Fetching data for: HQU.TO
Fetching data for: HRAA.TO
Fetching data for: HRED.TO
Fetching data for: HREU.TO
Fetching data for: HRIF.TO
Fetching data for: HRX.TO
Fetching data for: HSAV.TO
Fetching data for: HSD.TO
Fetching data for: HSH.TO
Fetching data for: HSU.TO
Fetching data for: HTA.TO
Fetching data for: HTAE.TO
Fetching data for: HTB.TO
Fetching data for: HUBL.TO
Fetching data for: HUC.TO
Fetching data for: HUG.TO
Fetching data for: HULC.TO
Fetching data for: HUM.TO
Fetching data for: HUN.TO
Fetching data for: HURA.TO
Fetching data for: HUT.TO
Fetching data for: HUTE.TO
Fetching data for: HUTL.TO
Fetching data for: HUTS.TO
Fetching data for: HUV.TO
Fetching data for: HUZ.TO
Fetching data for: HWO.TO
Fetching data for: HWX.TO
Fetching data for: HXCN.TO
Fetching data for: HXD.TO
Fetching data for: HXDM.TO
Fetching data for: HXE.TO
Fetching data for: HXEM.TO
Fetching data for: HXF.TO
Fetching data for: HXH.TO
Fetching data for: HXQ.TO
Fetching data for: HXS.TO
Fetching data for: HXT.TO
Fetching data for: HXU.TO
Fetching data for: HXX.TO
Fetching data for: HYBR.TO
Fetching data for: HYLD.TO
Fetching data for: HZD.TO
Fetching data for: HZU.TO
Fetching data for: IAG.TO
Fetching data for: IAU.TO
Fetching data for: ICAE.TO
Fetching data for: ICE.TO
Fetching data for: ICPB.TO
Fetching data for: ICTE.TO
Fetching data for: IE.TO
Fetching data for: IFA.TO
Fetching data for: IFC.TO
Fetching data for: IFP.TO
Fetching data for: IFRF.TO
Fetching data for: IGAF.TO
Fetching data for: IGB.TO
Fetching data for: IGEO.TO
Fetching data for: IGET.TO
Fetching data for: IGM.TO
Fetching data for: IIAE.TO
Fetching data for: IICE.TO
Fetching data for: III.TO
Fetching data for: IIMF.TO
Fetching data for: IITE.TO
Fetching data for: ILGB.TO
Fetching data for: ILLM.TO
Fetching data for: IMG.TO
Fetching data for: IMO.TO
Fetching data for: IMP.TO
Fetching data for: INAI.TO
Fetching data for: INCM.TO
Fetching data for: INE.TO
Fetching data for: INOC.TO
Fetching data for: IPCO.TO
Fetching data for: IPO.TO
Fetching data for: IQD.TO
Fetching data for: IS.TO
Fetching data for: ISC.TO
Fetching data for: ISCB.TO
Fetching data for: ISO.TO
Fetching data for: ISTE.TO
Fetching data for: ITH.TO
Fetching data for: IUAE.TO
Fetching data for: IUCE.TO
Fetching data for: IUMF.TO
Fetching data for: IUTE.TO
Fetching data for: IVN.TO
Fetching data for: IVQ.TO
Fetching data for: IWBE.TO
Fetching data for: IXTE.TO
Fetching data for: JAG.TO
Fetching data for: JAPN.TO
Fetching data for: JEPI.TO
Fetching data for: JEPQ.TO
Fetching data for: JOY.TO
Fetching data for: JWEL.TO
Fetching data for: K.TO
Fetching data for: KBL.TO
Fetching data for: KEC.TO
Fetching data for: KEI.TO
Fetching data for: KEL.TO
Fetching data for: KEY.TO
Fetching data for: KILO.TO
Fetching data for: KITS.TO
Fetching data for: KLS.TO
Fetching data for: KNGC.TO
Fetching data for: KNGU.TO
Fetching data for: KNGX.TO
Fetching data for: KNT.TO
Fetching data for: KPT.TO
Fetching data for: KRN.TO
Fetching data for: KSI.TO
Fetching data for: KXS.TO
Fetching data for: L.TO
Fetching data for: LAAC.TO
Fetching data for: LABS.TO
Fetching data for: LAC.TO
Fetching data for: LAM.TO
Fetching data for: LB.TO
Fetching data for: LBS.TO
Fetching data for: LCFS.TO
Fetching data for: LCS.TO
Fetching data for: LEAD.TO
Fetching data for: LFE.TO
Fetching data for: LGD.TO
Fetching data for: LGO.TO
Fetching data for: LIF.TO
Fetching data for: LIFE.TO
Fetching data for: LIRC.TO
Fetching data for: LLHE.TO
Fetching data for: LLYH.TO
Fetching data for: LMAX.TO
Fetching data for: LN.TO
Fetching data for: LNF.TO
Fetching data for: LNR.TO
Fetching data for: LPAY.TO
Fetching data for: LSPD.TO
Fetching data for: LSPK.TO
Fetching data for: LUC.TO
Fetching data for: LUG.TO
Fetching data for: LUN.TO
Fetching data for: LYCT.TO
Fetching data for: LYFR.TO
Fetching data for: MAG.TO
Fetching data for: MAL.TO
Fetching data for: MARI.TO
Fetching data for: MART.TO
Fetching data for: MATR.TO
Fetching data for: MBAL.TO
Fetching data for: MBX.TO
Fetching data for: MCAD.TO
Fetching data for: MCB.TO
Fetching data for: MCLC.TO
Fetching data for: MCLV.TO
Fetching data for: MCON.TO
Fetching data for: MCSB.TO
Fetching data for: MCSM.TO
Fetching data for: MDA.TO
Fetching data for: MDI.TO
Fetching data for: MDIV.TO
Fetching data for: MDNA.TO
Fetching data for: MDP.TO
Fetching data for: MDVD.TO
Fetching data for: MEG.TO
Fetching data for: MEQ.TO
Fetching data for: MEQT.TO
Fetching data for: MFC.TO
Fetching data for: MFI.TO
Fetching data for: MFT.TO
Fetching data for: MG.TO
Fetching data for: MGA.TO
Fetching data for: MGAB.TO
Fetching data for: MGB.TO
Fetching data for: MGDV.TO
Fetching data for: MGQE.TO
Fetching data for: MGRW.TO
Fetching data for: MHCD.TO
Fetching data for: MINF.TO
Fetching data for: MINN.TO
Fetching data for: MINT.TO
Fetching data for: MIQE.TO
Fetching data for: MIVG.TO
Fetching data for: MKB.TO
Fetching data for: MKP.TO
Fetching data for: MND.TO
Fetching data for: MNO.TO
Fetching data for: MNS.TO
Fetching data for: MNT.TO
Fetching data for: MNXT.TO
Fetching data for: MNY.TO
Fetching data for: MOGO.TO
Fetching data for: MORE.TO
Fetching data for: MPAY.TO
Fetching data for: MPC.TO
Fetching data for: MPVD.TO
Fetching data for: MPY.TO
Fetching data for: MRC.TO
Fetching data for: MRD.TO
Fetching data for: MRE.TO
Fetching data for: MREL.TO
Fetching data for: MRU.TO
Fetching data for: MSA.TO
Fetching data for: MSCL.TO
Fetching data for: MSFH.TO
Fetching data for: MSHE.TO
Fetching data for: MSV.TO
Fetching data for: MTAV.TO
Fetching data for: MTL.TO
Fetching data for: MTY.TO
Fetching data for: MUB.TO
Fetching data for: MULC.TO
Fetching data for: MULV.TO
Fetching data for: MUMC.TO
Fetching data for: MUSA.TO
Fetching data for: MUX.TO
Fetching data for: MWLV.TO
Fetching data for: MX.TO
Fetching data for: MXG.TO
Fetching data for: NA.TO
Fetching data for: NALT.TO
Fetching data for: NANO.TO
Fetching data for: NCF.TO
Fetching data for: NDIV.TO
Fetching data for: NDM.TO
Fetching data for: NEO.TO
Fetching data for: NEXT.TO
Fetching data for: NFI.TO
Fetching data for: NG.TO
Fetching data for: NGD.TO
Fetching data for: NGDN.TO
Fetching data for: NGEX.TO
Fetching data for: NGPE.TO
Fetching data for: NGT.TO
Fetching data for: NGUP.TO
Fetching data for: NHYB.TO
Fetching data for: NINT.TO
Fetching data for: NOA.TO
Fetching data for: NPI.TO
Fetching data for: NPK.TO
Fetching data for: NPRF.TO
Fetching data for: NPS.TO
Fetching data for: NREA.TO
Fetching data for: NRGY.TO
Fetching data for: NSCB.TO
Fetching data for: NSCC.TO
Fetching data for: NSCE.TO
Fetching data for: NSGE.TO
Fetching data for: NSSB.TO
Fetching data for: NTR.TO
Fetching data for: NUAG.TO
Fetching data for: NUBF.TO
Fetching data for: NUMI.TO
Fetching data for: NUSA.TO
Fetching data for: NVA.TO
Fetching data for: NVDH.TO
Fetching data for: NVHE.TO
Fetching data for: NVO.TO
Fetching data for: NWC.TO
Fetching data for: NXE.TO
Fetching data for: NXF.TO
Fetching data for: NXTG.TO
Fetching data for: OBE.TO
Fetching data for: OGC.TO
Fetching data for: OGD.TO
Fetching data for: OGI.TO
Fetching data for: OLA.TO
Fetching data for: OLY.TO
Fetching data for: ONC.TO
Fetching data for: ONEB.TO
Fetching data for: ONEC.TO
Fetching data for: ONEQ.TO
Fetching data for: ONEX.TO
Fetching data for: OPT.TO
Fetching data for: OR.TO
Fetching data for: ORA.TO
Fetching data for: ORE.TO
Fetching data for: ORV.TO
Fetching data for: OTEX.TO
Fetching data for: OVV.TO
Fetching data for: PAAS.TO
Fetching data for: PABF.TO
Fetching data for: PACF.TO
Fetching data for: PAGF.TO
Fetching data for: PAY.TO
Fetching data for: PAYF.TO
Fetching data for: PAYL.TO
Fetching data for: PAYM.TO
Fetching data for: PAYS.TO
Fetching data for: PBD.TO
Fetching data for: PBH.TO
Fetching data for: PBI.TO
Fetching data for: PBL.TO
Fetching data for: PCOR.TO
Fetching data for: PD.TO
Fetching data for: PDC.TO
Fetching data for: PDF.TO
Fetching data for: PDIV.TO
Fetching data for: PDN.TO
Fetching data for: PDV.TO
Fetching data for: PEA.TO
Fetching data for: PET.TO
Fetching data for: PEY.TO
Fetching data for: PFAA.TO
Fetching data for: PFAE.TO
Fetching data for: PFCB.TO
Fetching data for: PFIA.TO
Fetching data for: PFL.TO
Fetching data for: PFLS.TO
Fetching data for: PFMN.TO
Fetching data for: PFSS.TO
Fetching data for: PGIC.TO
Fetching data for: PHR.TO
Fetching data for: PHX.TO
Fetching data for: PHYS.TO
Fetching data for: PID.TO
Fetching data for: PIF.TO
Fetching data for: PIN.TO
Fetching data for: PINC.TO
Fetching data for: PKI.TO
Fetching data for: PLDI.TO
Fetching data for: PLV.TO
Fetching data for: PME.TO
Fetching data for: PMET.TO
Fetching data for: PMIF.TO
Fetching data for: PMM.TO
Fetching data for: PMNT.TO
Fetching data for: PNE.TO
Fetching data for: PNP.TO
Fetching data for: POU.TO
Fetching data for: POW.TO
Fetching data for: PPL.TO
Fetching data for: PPLN.TO
Fetching data for: PPR.TO
Fetching data for: PPTA.TO
Fetching data for: PR.TO
Fetching data for: PRA.TO
Fetching data for: PRB.TO
Fetching data for: PREF.TO
Fetching data for: PRL.TO
Fetching data for: PRM.TO
Fetching data for: PRN.TO
Fetching data for: PRQ.TO
Fetching data for: PRU.TO
Fetching data for: PRYM.TO
Fetching data for: PSA.TO
Fetching data for: PSB.TO
Fetching data for: PSD.TO
Fetching data for: PSI.TO
Fetching data for: PSK.TO
Fetching data for: PSLV.TO
Fetching data for: PTM.TO
Fetching data for: PWI.TO
Fetching data for: PXC.TO
Fetching data for: PXS.TO
Fetching data for: PXT.TO
Fetching data for: PYF.TO
Fetching data for: PYR.TO
Fetching data for: PZA.TO
Fetching data for: PZW.TO
Fetching data for: QAH.TO
Fetching data for: QASH.TO
Fetching data for: QBB.TO
Fetching data for: QBTC.TO
Fetching data for: QBTL.TO
Fetching data for: QCE.TO
Fetching data for: QCLN.TO
Fetching data for: QCN.TO
Fetching data for: QDX.TO
Fetching data for: QDXB.TO
Fetching data for: QDXH.TO
Fetching data for: QEBH.TO
Fetching data for: QEBL.TO
Fetching data for: QEC.TO
Fetching data for: QEE.TO
Fetching data for: QHY.TO
Fetching data for: QIE.TO
Fetching data for: QINF.TO
Fetching data for: QIPT.TO
Fetching data for: QLB.TO
Fetching data for: QMAX.TO
Fetching data for: QQC.TO
Fetching data for: QQCC.TO
Fetching data for: QQCE.TO
Fetching data for: QQCI.TO
Fetching data for: QQCL.TO
Fetching data for: QQEQ.TO
Fetching data for: QQJE.TO
Fetching data for: QQJR.TO
Fetching data for: QQQL.TO
Fetching data for: QQQT.TO
Fetching data for: QQQX.TO
Fetching data for: QQQY.TO
Fetching data for: QRC.TO
Fetching data for: QRET.TO
Fetching data for: QSB.TO
Fetching data for: QSR.TO
Fetching data for: QTLT.TO
Fetching data for: QTRH.TO
Fetching data for: QUB.TO
Fetching data for: QUIG.TO
Fetching data for: QUS.TO
Fetching data for: QUU.TO
Fetching data for: QXM.TO
Fetching data for: RAAA.TO
Fetching data for: RATE.TO
Fetching data for: RBA.TO
Fetching data for: RBNK.TO
Fetching data for: RBO.TO
Fetching data for: RBOT.TO
Fetching data for: RBY.TO
Fetching data for: RCD.TO
Fetching data for: RCDC.TO
Fetching data for: RCG.TO
Fetching data for: RCH.TO
Fetching data for: RDBH.TO
Fetching data for: REAL.TO
Fetching data for: RGQN.TO
Fetching data for: RGQO.TO
Fetching data for: RGQP.TO
Fetching data for: RGQQ.TO
Fetching data for: RGQR.TO
Fetching data for: RGQS.TO
Fetching data for: RID.TO
Fetching data for: RIDH.TO
Fetching data for: RIFI.TO
Fetching data for: RIIN.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'XDGH.TO' reason: 'chart'
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['XDGH.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Warning: No data found for XDGH.TO
Fetching data for: XDIV.TO
Fetching data for: XDNA.TO
Fetching data for: XDRV.TO
Fetching data for: XDSR.TO
Fetching data for: XDU.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'XDU.TO' reason: 'chart'
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['XDU.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Warning: No data found for XDU.TO
Fetching data for: XDUH.TO
Fetching data for: XDV.TO
Fetching data for: XEB.TO
Fetching data for: XEC.TO
Fetching data for: XEF.TO
Fetching data for: XEG.TO
Fetching data for: XEH.TO
Fetching data for: XEI.TO
Fetching data for: XEM.TO
Fetching data for: XEMC.TO
Fetching data for: XEN.TO
Fetching data for: XEQT.TO
Fetching data for: XESG.TO
Fetching data for: XETM.TO
Fetching data for: XEU.TO
Fetching data for: XEXP.TO
Fetching data for: XFH.TO
Fetching data for: XFLB.TO
Fetching data for: XFLI.TO
Fetching data for: XFLX.TO
Fetching data for: XFN.TO
Fetching data for: XFR.TO
Fetching data for: XGB.TO
Fetching data for: XGD.TO
Fetching data for: XGI.TO
Fetching data for: XGRO.TO
Fetching data for: XHAK.TO
Fetching data for: XHB.TO
Fetching data for: XHC.TO
Fetching data for: XHD.TO
Fetching data for: XHU.TO
Fetching data for: XHY.TO
Fetching data for: XIC.TO
Fetching data for: XID.TO
Fetching data for: XIG.TO
Fetching data for: XIGS.TO
Fetching data for: XIN.TO
Fetching data for: XINC.TO
Fetching data for: XIT.TO
Fetching data for: XIU.TO
Fetching data for: XLB.TO
Fetching data for: XLY.TO
Fetching data for: XMA.TO
Fetching data for: XMC.TO
Fetching data for: XMD.TO
Fetching data for: XMH.TO
Fetching data for: XMI.TO
Fetching data for: XML.TO
Fetching data for: XMM.TO
Fetching data for: XMS.TO
Fetching data for: XMTM.TO
Fetching data for: XMU.TO
Fetching data for: XMV.TO
Fetching data for: XMW.TO
Fetching data for: XMY.TO
Fetching data for: XPF.TO
Fetching data for: XQB.TO
Fetching data for: XQLT.TO
Fetching data for: XQQ.TO
Fetching data for: XQQU.TO
Fetching data for: XRB.TO
Fetching data for: XRE.TO
Fetching data for: XSAB.TO
Fetching data for: XSB.TO
Fetching data for: XSC.TO
Fetching data for: XSE.TO
Fetching data for: XSEA.TO
Fetching data for: XSEM.TO
Fetching data for: XSH.TO
Fetching data for: XSHG.TO
Fetching data for: XSHU.TO
Fetching data for: XSI.TO
Fetching data for: XSMC.TO
Fetching data for: XSMH.TO
Fetching data for: XSP.TO
Fetching data for: XSPC.TO
Fetching data for: XST.TO
Fetching data for: XSTB.TO
Fetching data for: XSTH.TO
Fetching data for: XSTP.TO
Fetching data for: XSU.TO
Fetching data for: XSUS.TO
Fetching data for: XTC.TO
Fetching data for: XTD.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'XTD.TO' reason: 'chart'
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['XTD.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Warning: No data found for XTD.TO
Fetching data for: XTG.TO
Fetching data for: XTLH.TO
Fetching data for: XTLT.TO
Fetching data for: XTR.TO
Fetching data for: XTRA.TO
Fetching data for: XUH.TO
Fetching data for: XUS.TO
Fetching data for: XUSC.TO
Fetching data for: XUSF.TO
Fetching data for: XUSR.TO
Fetching data for: XUT.TO
Fetching data for: XUU.TO
Fetching data for: XVLU.TO
Fetching data for: XWD.TO
Fetching data for: Y.TO
Fetching data for: YCM.TO
Fetching data for: YGR.TO
Fetching data for: YRB.TO
Fetching data for: ZACE.TO
Fetching data for: ZAG.TO
Fetching data for: ZBAL.TO
Fetching data for: ZBBB.TO
Fetching data for: ZBI.TO
Fetching data for: ZBK.TO
Fetching data for: ZCB.TO
Fetching data for: ZCDB.TO
Fetching data for: ZCH.TO
Fetching data for: ZCLN.TO
Fetching data for: ZCM.TO
Fetching data for: ZCN.TO
Fetching data for: ZCON.TO
Fetching data for: ZCPB.TO
Fetching data for: ZCS.TO
Fetching data for: ZDB.TO
Fetching data for: ZDH.TO
Fetching data for: ZDI.TO
Fetching data for: ZDJ.TO
Fetching data for: ZDM.TO
Fetching data for: ZDV.TO
Fetching data for: ZDY.TO
Fetching data for: ZEA.TO
Fetching data for: ZEAT.TO
Fetching data for: ZEB.TO
Fetching data for: ZEF.TO
Fetching data for: ZEM.TO
Fetching data for: ZEO.TO
Fetching data for: ZEQ.TO
Fetching data for: ZEQT.TO
Fetching data for: ZESG.TO
Fetching data for: ZFC.TO
Fetching data for: ZFH.TO
Fetching data for: ZFL.TO
Fetching data for: ZFM.TO
Fetching data for: ZFN.TO
Fetching data for: ZFS.TO
Fetching data for: ZGB.TO
Fetching data for: ZGD.TO
Fetching data for: ZGI.TO
Fetching data for: ZGLD.TO
Fetching data for: ZGLH.TO
Fetching data for: ZGQ.TO
Fetching data for: ZGRN.TO
Fetching data for: ZGRO.TO
Fetching data for: ZGSB.TO
Fetching data for: ZHP.TO
Fetching data for: ZHU.TO
Fetching data for: ZHY.TO
Fetching data for: ZIC.TO
Fetching data for: ZID.TO
Fetching data for: ZIN.TO
Fetching data for: ZIQ.TO
Fetching data for: ZIU.TO
Fetching data for: ZJG.TO
Fetching data for: ZJK.TO
Fetching data for: ZJPN.TO
Fetching data for: ZLB.TO
Fetching data for: ZLC.TO
Fetching data for: ZLD.TO
Fetching data for: ZLE.TO
Fetching data for: ZLH.TO
Fetching data for: ZLI.TO
Fetching data for: ZLSC.TO
Fetching data for: ZLSU.TO
Fetching data for: ZLU.TO
Fetching data for: ZMBS.TO
Fetching data for: ZMI.TO
Fetching data for: ZMID.TO
Fetching data for: ZMMK.TO
Fetching data for: ZMP.TO
Fetching data for: ZMSB.TO
Fetching data for: ZMT.TO
Fetching data for: ZMU.TO
Fetching data for: ZNQ.TO
Fetching data for: ZPAY.TO
Fetching data for: ZPH.TO
Fetching data for: ZPL.TO
Fetching data for: ZPR.TO
Fetching data for: ZPS.TO
Fetching data for: ZPW.TO
Fetching data for: ZQB.TO
Fetching data for: ZQQ.TO
Fetching data for: ZRE.TO
Fetching data for: ZRR.TO
Fetching data for: ZSB.TO
Fetching data for: ZSDB.TO
Fetching data for: ZSML.TO
Fetching data for: ZSP.TO
Fetching data for: ZST.TO
Fetching data for: ZSU.TO
Fetching data for: ZTIP.TO
Fetching data for: ZUAG.TO
Fetching data for: ZUB.TO
Fetching data for: ZUCM.TO
Fetching data for: ZUD.TO
Fetching data for: ZUE.TO
Fetching data for: ZUGE.TO
Fetching data for: ZUH.TO
Fetching data for: ZUP.TO
Fetching data for: ZUQ.TO
Fetching data for: ZUT.TO
Fetching data for: ZVC.TO
Fetching data for: ZVU.TO
Fetching data for: ZWA.TO
Fetching data for: ZWB.TO
Fetching data for: ZWC.TO
Fetching data for: ZWE.TO
Fetching data for: ZWEN.TO
Fetching data for: ZWG.TO
Fetching data for: ZWH.TO
Fetching data for: ZWHC.TO
Fetching data for: ZWK.TO
Fetching data for: ZWP.TO
Fetching data for: ZWQT.TO
Fetching data for: ZWS.TO
Fetching data for: ZWT.TO
Fetching data for: ZWU.TO
Fetching data for: ZXM.TO
Fetching data for: ZZZD.TO
DataFrame columns: ['date', 'close', 'high', 'low', 'open', 'volume', 'tic', 'day']
DataFrame shape: (4066965, 8)

First few rows:
              date      close       high        low       open  volume  \
952970  2004-01-01   0.105000   0.105000   0.105000   0.105000       0
985564  2004-01-01   1.378000   1.378000   1.378000   1.378000       0
3143022 2004-01-01   0.300000   0.300000   0.300000   0.300000       0
0       2004-01-02   0.489625   0.489625   0.489625   0.489625       0
9404    2004-01-02  22.070263  22.211644  21.817266  21.899118  413000

            tic  day
952970   DYA.TO    3
985564   EDT.TO    3
3143022  TSK.TO    3
0        AAB.TO    4
9404     ABX.TO    4

In [ ]:
historical_data

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,date,close,high,low,open,volume,tic,day
952970,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3
985564,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3
3143022,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3
0,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4
9404,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4
...,...,...,...,...,...,...,...,...
4058709,2024-12-30,20.230000,20.309999,20.150000,20.309999,700,ZWS.TO,0
4059695,2024-12-30,53.099998,53.360001,52.830002,53.299999,11600,ZWT.TO,0
4062941,2024-12-30,10.510000,10.520000,10.430000,10.500000,168700,ZWU.TO,0
4065476,2024-12-30,42.599998,42.610001,42.599998,42.610001,300,ZXM.TO,0
4066964,2024-12-30,27.700001,27.700001,27.700001,27.700001,1700,ZZZD.TO,0

In [ ]:
# Define the list of stock tickers
tickers = ["AAB.TO", "AAUC.TO", "AAV.TO", "ABX.TO", "AC.TO", "ACAA.TO", "ACB.TO", "ACD.TO", "ACQ.TO", "ACX.TO", "ADCO.TO", "ADEN.TO", "ADIV.TO", "ADN.TO", "AEG.TO", "AEM.TO", "AFN.TO", "AG.TO", "AGG.TO", "AGI.TO", "AI.TO", "AIDX.TO", "AIF.TO", "AIGO.TO", "AII.TO", "AIM.TO", "ALA.TO", "ALC.TO", "ALS.TO", "ALYA.TO", "AMAX.TO", "AMC.TO", "AMHE.TO", "AMM.TO", "AMZH.TO", "AND.TO", "ANRG.TO", "AOI.TO", "AOT.TO", "APLI.TO", "APM.TO", "APS.TO", "AQN.TO", "ARA.TO", "ARB.TO", "ARE.TO", "ARG.TO", "ARIS.TO", "ARTI.TO", "ARX.TO", "ASCU.TO", "ASM.TO", "ASND.TO", "ASTL.TO", "ATCU.TO", "ATD.TO", "ATH.TO", "ATRL.TO", "ATS.TO", "ATSX.TO", "ATZ.TO", "AUMN.TO", "AVCN.TO", "AVL.TO", "AVNT.TO", "AW.TO", "AYA.TO", "BABY.TO", "BAM.TO", "BANK.TO", "BASE.TO", "BB.TO", "BBUC.TO", "BCE.TO", "BCHT.TO", "BCT.TO", "BDGI.TO", "BDI.TO", "BDIV.TO", "BDT.TO", "BEPC.TO", "BEPR.TO", "BESG.TO", "BFIN.TO", "BGC.TO", "BGU.TO", "BHC.TO", "BIPC.TO", "BIR.TO", "BITF.TO", "BITI.TO", "BK.TO", "BKCC.TO", "BKCL.TO", "BKI.TO", "BLCO.TO", "BLDP.TO", "BLN.TO", "BLOV.TO", "BLX.TO", "BMAX.TO", "BMO.TO", "BN.TO", "BNC.TO", "BND.TO", "BNE.TO", "BNG.TO", "BNK.TO", "BNKL.TO", "BNS.TO", "BNT.TO", "BOND.TO", "BOS.TO", "BPRF.TO", "BR.TO", "BRAG.TO", "BRE.TO", "BREA.TO", "BRMI.TO", "BRY.TO", "BSKT.TO", "BSX.TO", "BTCC.TO", "BTCQ.TO", "BTCY.TO", "BTE.TO", "BTO.TO", "BU.TO", "BUI.TO", "BXF.TO", "BYD.TO", "BYL.TO", "CACB.TO", "CAE.TO", "CAFR.TO", "CAGG.TO", "CAGS.TO", "CALL.TO", "CANL.TO", "CAPG.TO", "CAPI.TO", "CAPM.TO", "CAPW.TO", "CARB.TO", "CARS.TO", "CAS.TO", "CASH.TO", "CBAL.TO", "CBCX.TO", "CBGR.TO", "CBH.TO", "CBIL.TO", "CBIN.TO", "CBL.TO", "CBND.TO", "CBNK.TO", "CBO.TO", "CBUG.TO", "CCA.TO", "CCBI.TO", "CCEI.TO", "CCM.TO", "CCNS.TO", "CCNV.TO", "CCO.TO", "CCOM.TO", "CCRE.TO", "CDEF.TO", "CDIV.TO", "CDLB.TO", "CDNA.TO", "CDR.TO", "CDZ.TO", "CEF.TO", "CEMI.TO", "CEMX.TO", "CEQT.TO", "CEU.TO", "CEW.TO", "CF.TO", "CFF.TO", "CFLX.TO", "CFP.TO", "CFRT.TO", "CFW.TO", "CFX.TO", "CG.TO", "CGAA.TO", "CGBI.TO", "CGDV.TO", "CGG.TO", "CGHY.TO", "CGI.TO", "CGIN.TO", "CGL.TO", "CGLO.TO", "CGO.TO", "CGR.TO", "CGRA.TO", "CGRE.TO", "CGRN.TO", "CGRO.TO", "CGX.TO", "CGXF.TO", "CGY.TO", "CHPS.TO", "CHR.TO", "CIA.TO", "CIAI.TO", "CIBR.TO", "CIC.TO", "CIEH.TO", "CIEI.TO", "CIEM.TO", "CIF.TO", "CIGI.TO", "CINF.TO", "CINT.TO", "CINV.TO", "CIX.TO", "CJ.TO", "CJT.TO", "CKI.TO", "CLF.TO", "CLG.TO", "CLML.TO", "CLS.TO", "CM.TO", "CMAG.TO", "CMAR.TO", "CMDO.TO", "CMG.TO", "CMGG.TO", "CMNY.TO", "CMOM.TO", "CMR.TO", "CMVX.TO", "CNCC.TO", "CNCL.TO", "CNDX.TO", "CNE.TO", "CNL.TO", "CNQ.TO", "CNR.TO", "CNT.TO", "CNV.TO", "COG.TO", "COMM.TO", "COPP.TO", "COPR.TO", "CORE.TO", "COW.TO", "CP.TO", "CPD.TO", "CPH.TO", "CPLS.TO", "CPX.TO", "CRDL.TO", "CRED.TO", "CRON.TO", "CROP.TO", "CRP.TO", "CRRX.TO", "CRWN.TO", "CS.TO", "CSAV.TO", "CSBI.TO", "CSCI.TO", "CSU.TO", "CTC.TO", "CTS.TO", "CTX.TO", "CU.TO", "CUBD.TO", "CUD.TO", "CUDV.TO", "CUEH.TO", "CUEI.TO", "CURA.TO", "CUTL.TO", "CVD.TO", "CVE.TO", "CVG.TO", "CVLU.TO", "CVO.TO", "CWB.TO", "CWEB.TO", "CWL.TO", "CWW.TO", "CXB.TO", "CXF.TO", "CXI.TO", "CYB.TO", "CYBR.TO", "CYH.TO", "DAMG.TO", "DANC.TO", "DATA.TO", "DAY.TO", "DBM.TO", "DBO.TO", "DCBC.TO", "DCBO.TO", "DCC.TO", "DCG.TO", "DCM.TO", "DCP.TO", "DCS.TO", "DCU.TO", "DF.TO", "DFN.TO", "DFY.TO", "DGR.TO", "DGRC.TO", "DGS.TO", "DIAM.TO", "DISC.TO", "DIV.TO", "DIVS.TO", "DLCG.TO", "DLR.TO", "DMEC.TO", "DMEI.TO", "DMEU.TO", "DML.TO", "DND.TO", "DNG.TO", "DNTL.TO", "DOL.TO", "DOO.TO", "DPM.TO", "DR.TO", "DRCU.TO", "DRFC.TO", "DRFD.TO", "DRFE.TO", "DRFG.TO", "DRFU.TO", "DRM.TO", "DRMC.TO", "DRMD.TO", "DRME.TO", "DRMU.TO", "DRT.TO", "DRX.TO", "DS.TO", "DSAE.TO", "DSG.TO", "DSV.TO", "DTOL.TO", "DXAU.TO", "DXB.TO", "DXBB.TO", "DXBC.TO", "DXBG.TO", "DXBU.TO", "DXC.TO", "DXCB.TO", "DXCO.TO", "DXCP.TO", "DXDB.TO", "DXEM.TO", "DXET.TO", "DXF.TO", "DXG.TO", "DXGE.TO", "DXIF.TO", "DXMO.TO", "DXN.TO", "DXO.TO", "DXP.TO", "DXQ.TO", "DXR.TO", "DXT.TO", "DXU.TO", "DXUS.TO", "DXV.TO", "DXW.TO", "DXZ.TO", "DYA.TO", "E.TO", "EAGR.TO", "EARN.TO", "EBIT.TO", "EBNK.TO", "ECN.TO", "ECO.TO", "ECOR.TO", "EDGE.TO", "EDGF.TO", "EDR.TO", "EDT.TO", "EDV.TO", "EFN.TO", "EFR.TO", "EFX.TO", "EGLX.TO", "EIF.TO", "ELD.TO", "ELEF.TO", "ELF.TO", "ELO.TO", "ELR.TO", "ELVA.TO", "EMA.TO", "EMAX.TO", "ENB.TO", "ENCC.TO", "ENCL.TO", "ENGH.TO", "ENS.TO", "EPRX.TO", "EQB.TO", "EQCC.TO", "EQCL.TO", "EQL.TO", "EQLI.TO", "EQX.TO", "ERD.TO", "ERO.TO", "ESG.TO", "ESGA.TO", "ESGB.TO", "ESGC.TO", "ESGE.TO", "ESGF.TO", "ESGG.TO", "ESGH.TO", "ESGY.TO", "ESI.TO", "ESM.TO", "ESP.TO", "ESPX.TO", "ET.TO", "ETC.TO", "ETG.TO", "ETHH.TO", "ETHI.TO", "ETHQ.TO", "ETHR.TO", "ETHY.TO", "ETP.TO", "ETSX.TO", "EVO.TO", "EVT.TO", "EXE.TO", "EXN.TO", "EXRO.TO", "FAP.TO", "FAR.TO", "FBGO.TO", "FBT.TO", "FBTC.TO", "FC.TO", "FCCD.TO", "FCCQ.TO", "FCCV.TO", "FCEM.TO", "FCGI.TO", "FCID.TO", "FCII.TO", "FCIQ.TO", "FCIV.TO", "FCMI.TO", "FCQH.TO", "FCRR.TO", "FCUD.TO", "FCUH.TO", "FCUQ.TO", "FCUV.TO", "FCVH.TO", "FDL.TO", "FDN.TO", "FDY.TO", "FEC.TO", "FETH.TO", "FF.TO", "FFH.TO", "FFM.TO", "FFN.TO", "FGB.TO", "FGEB.TO", "FGEP.TO", "FGGE.TO", "FGO.TO", "FGOV.TO", "FGRW.TO", "FHG.TO", "FHH.TO", "FHI.TO", "FHIS.TO", "FHQ.TO", "FIE.TO", "FIG.TO", "FIL.TO", "FINC.TO", "FINE.TO", "FINO.TO", "FLCI.TO", "FLCP.TO", "FLGA.TO", "FLI.TO", "FLNT.TO", "FLOW.TO", "FLSD.TO", "FLUS.TO", "FLX.TO", "FM.TO", "FMAX.TO", "FN.TO", "FNV.TO", "FOM.TO", "FOOD.TO", "FORA.TO", "FOUR.TO", "FPR.TO", "FRU.TO", "FRX.TO", "FSB.TO", "FSF.TO", "FSL.TO", "FST.TO", "FSV.TO", "FSY.TO", "FSZ.TO", "FT.TO", "FTG.TO", "FTHI.TO", "FTN.TO", "FTS.TO", "FTT.TO", "FTU.TO", "FURY.TO", "FVI.TO", "FVL.TO", "FXM.TO", "G.TO", "GATO.TO", "GAU.TO", "GBAL.TO", "GBT.TO", "GCBD.TO", "GCFE.TO", "GCG.TO", "GCL.TO", "GCNS.TO", "GCSC.TO", "GCTB.TO", "GCU.TO", "GDC.TO", "GDEP.TO", "GDI.TO", "GDL.TO", "GDPY.TO", "GDV.TO", "GEC.TO", "GEI.TO", "GENM.TO", "GEO.TO", "GEQT.TO", "GFL.TO", "GFP.TO", "GFR.TO", "GGD.TO", "GGRO.TO", "GH.TO", "GIGC.TO", "GIL.TO", "GIQG.TO", "GIQU.TO", "GLCC.TO", "GLDX.TO", "GLO.TO", "GLXY.TO", "GMIN.TO", "GMTN.TO", "GMX.TO", "GOLD.TO", "GOOS.TO", "GPMD.TO", "GRA.TO", "GRC.TO", "GRCC.TO", "GRGD.TO", "GRID.TO", "GRN.TO", "GRNI.TO", "GRO.TO", "GSY.TO", "GTE.TO", "GTWO.TO", "GUD.TO", "GURU.TO", "GVC.TO", "GWO.TO", "GXE.TO", "H.TO", "HAB.TO", "HAC.TO", "HAD.TO", "HAF.TO", "HAI.TO", "HAL.TO", "HAZ.TO", "HBA.TO", "HBAL.TO", "HBB.TO", "HBD.TO", "HBF.TO", "HBGD.TO", "HBIE.TO", "HBIG.TO", "HBIL.TO", "HBKD.TO", "HBKU.TO", "HBLK.TO", "HBM.TO", "HBND.TO", "HBNK.TO", "HBP.TO", "HBU.TO", "HBUG.TO", "HCA.TO", "HCAL.TO", "HCLN.TO", "HCON.TO", "HCRE.TO", "HDGE.TO", "HDIF.TO", "HDIV.TO", "HEB.TO", "HED.TO", "HEQL.TO", "HEQT.TO", "HERO.TO", "HEU.TO", "HEWB.TO", "HFD.TO", "HFG.TO", "HFIN.TO", "HFR.TO", "HFU.TO", "HGD.TO", "HGGG.TO", "HGR.TO", "HGRW.TO", "HGU.TO", "HGY.TO", "HHL.TO", "HHLE.TO", "HIG.TO", "HIND.TO", "HIU.TO", "HIX.TO", "HLF.TO", "HLIF.TO", "HLIT.TO", "HLPR.TO", "HLS.TO", "HMAX.TO", "HMMJ.TO", "HMP.TO", "HND.TO", "HNU.TO", "HOD.TO", "HOU.TO", "HPF.TO", "HPR.TO", "HPYM.TO", "HPYT.TO", "HQD.TO", "HQU.TO", "HRAA.TO", "HRED.TO", "HREU.TO", "HRIF.TO", "HRX.TO", "HSAV.TO", "HSD.TO", "HSH.TO", "HSU.TO", "HTA.TO","HTAE.TO", "HTB.TO", "HUBL.TO", "HUC.TO", "HUG.TO", "HULC.TO", "HUM.TO", "HUN.TO", "HURA.TO", "HUT.TO", "HUTE.TO", "HUTL.TO", "HUTS.TO", "HUV.TO", "HUZ.TO", "HWO.TO", "HWX.TO", "HXCN.TO", "HXD.TO", "HXDM.TO", "HXE.TO", "HXEM.TO", "HXF.TO", "HXH.TO", "HXQ.TO", "HXS.TO", "HXT.TO", "HXU.TO", "HXX.TO", "HYBR.TO", "HYLD.TO", "HZD.TO", "HZU.TO", "IAG.TO", "IAU.TO", "ICAE.TO", "ICE.TO", "ICPB.TO", "ICTE.TO", "IE.TO", "IFA.TO", "IFC.TO", "IFP.TO", "IFRF.TO", "IGAF.TO", "IGB.TO", "IGEO.TO", "IGET.TO", "IGM.TO", "IIAE.TO", "IICE.TO", "III.TO", "IIMF.TO", "IITE.TO", "ILGB.TO", "ILLM.TO", "IMG.TO", "IMO.TO", "IMP.TO", "INAI.TO", "INCM.TO", "INE.TO", "INOC.TO", "IPCO.TO", "IPO.TO", "IQD.TO", "IS.TO", "ISC.TO", "ISCB.TO", "ISO.TO", "ISTE.TO", "ITH.TO", "IUAE.TO", "IUCE.TO", "IUMF.TO", "IUTE.TO", "IVN.TO", "IVQ.TO", "IWBE.TO", "IXTE.TO", "JAG.TO", "JAPN.TO", "JEPI.TO", "JEPQ.TO", "JOY.TO", "JWEL.TO", "K.TO", "KBL.TO", "KEC.TO", "KEI.TO", "KEL.TO", "KEY.TO", "KILO.TO", "KITS.TO", "KLS.TO", "KNGC.TO", "KNGU.TO", "KNGX.TO", "KNT.TO", "KPT.TO", "KRN.TO", "KSI.TO", "KXS.TO", "L.TO", "LAAC.TO", "LABS.TO", "LAC.TO", "LAM.TO", "LB.TO", "LBS.TO", "LCFS.TO", "LCS.TO", "LEAD.TO", "LFE.TO", "LGD.TO", "LGO.TO", "LIF.TO", "LIFE.TO", "LIRC.TO", "LLHE.TO", "LLYH.TO", "LMAX.TO", "LN.TO", "LNF.TO", "LNR.TO", "LPAY.TO", "LSPD.TO", "LSPK.TO", "LUC.TO", "LUG.TO", "LUN.TO", "LYCT.TO", "LYFR.TO", "MAG.TO", "MAL.TO", "MARI.TO", "MART.TO", "MATR.TO", "MBAL.TO", "MBX.TO", "MCAD.TO", "MCB.TO", "MCLC.TO", "MCLV.TO", "MCON.TO", "MCSB.TO", "MCSM.TO", "MDA.TO", "MDI.TO", "MDIV.TO", "MDNA.TO", "MDP.TO", "MDVD.TO", "MEG.TO", "MEQ.TO", "MEQT.TO", "MFC.TO", "MFI.TO", "MFT.TO", "MG.TO", "MGA.TO", "MGAB.TO", "MGB.TO", "MGDV.TO", "MGQE.TO", "MGRW.TO", "MHCD.TO", "MINF.TO", "MINN.TO", "MINT.TO", "MIQE.TO", "MIVG.TO", "MKB.TO", "MKP.TO", "MND.TO", "MNO.TO", "MNS.TO", "MNT.TO", "MNXT.TO", "MNY.TO", "MOGO.TO", "MORE.TO", "MPAY.TO", "MPC.TO", "MPVD.TO", "MPY.TO", "MRC.TO", "MRD.TO", "MRE.TO", "MREL.TO", "MRU.TO", "MSA.TO", "MSCL.TO", "MSFH.TO", "MSHE.TO", "MSV.TO", "MTAV.TO", "MTL.TO", "MTY.TO", "MUB.TO", "MULC.TO", "MULV.TO", "MUMC.TO", "MUSA.TO", "MUX.TO", "MWLV.TO", "MX.TO", "MXG.TO", "NA.TO", "NALT.TO", "NANO.TO", "NCF.TO", "NDIV.TO", "NDM.TO", "NEO.TO", "NEXT.TO", "NFI.TO", "NG.TO", "NGD.TO", "NGDN.TO", "NGEX.TO", "NGPE.TO", "NGT.TO", "NGUP.TO", "NHYB.TO", "NINT.TO", "NOA.TO", "NPI.TO", "NPK.TO", "NPRF.TO", "NPS.TO", "NREA.TO", "NRGY.TO", "NSCB.TO", "NSCC.TO", "NSCE.TO", "NSGE.TO", "NSSB.TO", "NTR.TO", "NUAG.TO", "NUBF.TO", "NUMI.TO", "NUSA.TO", "NVA.TO", "NVDH.TO", "NVHE.TO", "NVO.TO", "NWC.TO", "NXE.TO", "NXF.TO", "NXTG.TO", "OBE.TO", "OGC.TO", "OGD.TO", "OGI.TO", "OLA.TO", "OLY.TO", "ONC.TO", "ONEB.TO", "ONEC.TO", "ONEQ.TO", "ONEX.TO", "OPT.TO", "OR.TO", "ORA.TO", "ORE.TO", "ORV.TO", "OTEX.TO", "OVV.TO", "PAAS.TO", "PABF.TO", "PACF.TO", "PAGF.TO", "PAY.TO", "PAYF.TO", "PAYL.TO", "PAYM.TO", "PAYS.TO", "PBD.TO", "PBH.TO", "PBI.TO", "PBL.TO", "PCOR.TO", "PD.TO", "PDC.TO", "PDF.TO", "PDIV.TO", "PDN.TO", "PDV.TO", "PEA.TO", "PET.TO", "PEY.TO", "PFAA.TO", "PFAE.TO", "PFCB.TO", "PFIA.TO", "PFL.TO", "PFLS.TO", "PFMN.TO", "PFSS.TO", "PGIC.TO", "PHR.TO", "PHX.TO", "PHYS.TO", "PID.TO", "PIF.TO", "PIN.TO", "PINC.TO", "PKI.TO", "PLDI.TO", "PLV.TO", "PME.TO", "PMET.TO", "PMIF.TO", "PMM.TO", "PMNT.TO", "PNE.TO", "PNP.TO", "POU.TO", "POW.TO", "PPL.TO", "PPLN.TO", "PPR.TO", "PPTA.TO", "PR.TO", "PRA.TO", "PRB.TO", "PREF.TO", "PRL.TO", "PRM.TO", "PRN.TO", "PRQ.TO", "PRU.TO", "PRYM.TO", "PSA.TO", "PSB.TO", "PSD.TO", "PSI.TO", "PSK.TO", "PSLV.TO", "PTM.TO", "PWI.TO", "PXC.TO", "PXS.TO", "PXT.TO", "PYF.TO", "PYR.TO", "PZA.TO", "PZW.TO", "QAH.TO", "QASH.TO", "QBB.TO", "QBTC.TO", "QBTL.TO", "QCE.TO", "QCLN.TO", "QCN.TO", "QDX.TO", "QDXB.TO", "QDXH.TO", "QEBH.TO", "QEBL.TO", "QEC.TO", "QEE.TO", "QHY.TO", "QIE.TO", "QINF.TO", "QIPT.TO", "QLB.TO", "QMAX.TO", "QQC.TO", "QQCC.TO", "QQCE.TO", "QQCI.TO", "QQCL.TO", "QQEQ.TO", "QQJE.TO", "QQJR.TO", "QQQL.TO", "QQQT.TO", "QQQX.TO", "QQQY.TO", "QRC.TO", "QRET.TO", "QSB.TO", "QSR.TO", "QTLT.TO", "QTRH.TO", "QUB.TO", "QUIG.TO", "QUS.TO", "QUU.TO", "QXM.TO", "RAAA.TO", "RATE.TO", "RBA.TO", "RBNK.TO", "RBO.TO", "RBOT.TO", "RBY.TO", "RCD.TO", "RCDC.TO", "RCG.TO", "RCH.TO", "RDBH.TO", "REAL.TO", "RGQN.TO", "RGQO.TO", "RGQP.TO", "RGQQ.TO", "RGQR.TO", "RGQS.TO", "RID.TO", "RIDH.TO", "RIFI.TO", "RIIN.TO", "RING.TO", "RIRA.TO", "RIT.TO", "RLB.TO", "RMAX.TO", "ROOT.TO", "RPD.TO", "RPDH.TO", "RPF.TO", "RPSB.TO", "RQN.TO", "RQO.TO", "RQP.TO", "RQQ.TO", "RQR.TO", "RQS.TO", "RS.TO", "RSI.TO", "RTG.TO", "RUBH.TO", "RUBY.TO", "RUD.TO", "RUDB.TO", "RUDC.TO", "RUDH.TO", "RUP.TO", "RUQN.TO", "RUQO.TO", "RUQQ.TO", "RUQR.TO", "RUQS.TO", "RUS.TO", "RUSB.TO", "RVX.TO", "RXD.TO", "RY.TO", "S.TO", "SAFE.TO", "SAM.TO", "SAP.TO", "SAU.TO", "SBC.TO", "SBI.TO", "SBT.TO", "SCR.TO", "SCY.TO", "SDE.TO", "SEA.TO", "SEC.TO", "SES.TO", "SFC.TO", "SFD.TO", "SFI.TO", "SFTC.TO", "SGLD.TO", "SGY.TO", "SHLE.TO", "SHOP.TO", "SIA.TO", "SII.TO", "SIL.TO", "SIS.TO", "SJ.TO", "SKE.TO", "SKYY.TO", "SLF.TO", "SLR.TO", "SLS.TO", "SMAX.TO", "SMC.TO", "SMT.TO", "SOBO.TO", "SOIL.TO", "SOLG.TO", "SOY.TO", "SPAY.TO", "SPB.TO", "SPFD.TO", "SPLT.TO", "SPPP.TO", "SSL.TO", "SSRM.TO", "STC.TO", "STCK.TO", "STEP.TO", "STGO.TO", "STLR.TO", "STN.TO", "STPL.TO", "SU.TO", "SVA.TO", "SVB.TO", "SVI.TO", "SVM.TO", "SVR.TO", "SWP.TO", "SXI.TO", "SXP.TO", "SYLD.TO", "SYZ.TO", "T.TO", "TA.TO", "TAL.TO", "TBAL.TO", "TBCE.TO", "TBCF.TO", "TBCG.TO", "TBIL.TO", "TBL.TO", "TBNK.TO", "TC.TO", "TCBN.TO", "TCLB.TO", "TCLV.TO", "TCON.TO", "TCS.TO", "TCSB.TO", "TCSH.TO", "TCW.TO", "TD.TO", "TDB.TO", "TDOC.TO", "TEC.TO", "TECH.TO", "TECI.TO", "TECX.TO", "TERM.TO", "TF.TO", "TFII.TO", "TFPM.TO", "TGAF.TO", "TGED.TO", "TGFI.TO", "TGGR.TO", "TGO.TO", "TGRE.TO", "TGRO.TO", "TH.TO", "The.TO", "THNC.TO", "THU.TO", "TI.TO", "TIH.TO", "TILV.TO", "TINF.TO", "TIPS.TO", "TIXT.TO", "TKN.TO", "TKO.TO", "TLF.TO", "TLG.TO", "TLO.TO", "TLRY.TO", "TLV.TO", "TMQ.TO", "TNZ.TO", "TOT.TO", "TOU.TO", "TOWR.TO", "TOY.TO", "TPE.TO", "TPRF.TO", "TPU.TO", "TPZ.TO", "TQCD.TO", "TQGD.TO", "TQGM.TO", "TQSM.TO", "TRI.TO", "TRP.TO", "TRVI.TO", "TRVL.TO", "TRX.TO", "TRZ.TO", "TSAT.TO", "TSK.TO", "TSL.TO", "TSND.TO", "TSU.TO", "TTNM.TO", "TTP.TO", "TTTX.TO", "TUED.TO", "TUEX.TO", "TUHY.TO", "TULB.TO", "TULV.TO", "TUSB.TO", "TVE.TO", "TVK.TO", "TWC.TO", "TWM.TO", "TXF.TO", "TXG.TO", "TXP.TO", "UDA.TO", "UDIV.TO", "UMAX.TO", "UMI.TO", "UNC.TO", "UNI.TO", "URB.TO", "URC.TO", "URE.TO", "USA.TO", "USCC.TO", "USCL.TO", "USSL.TO", "USSX.TO", "UTES.TO", "UTIL.TO", "VA.TO", "VAB.TO", "VALT.TO", "VBAL.TO", "VBNK.TO", "VCB.TO", "VCE.TO", "VCIP.TO", "VCM.TO", "VCN.TO", "VCNS.TO", "VDU.TO", "VDY.TO", "VE.TO", "VEE.TO", "VEF.TO", "VEQT.TO", "VET.TO", "VFV.TO", "VGG.TO", "VGH.TO", "VGRO.TO", "VGV.TO", "VGZ.TO", "VHI.TO", "VI.TO", "VIDY.TO", "VIU.TO", "VLB.TO", "VLE.TO", "VLN.TO", "VMO.TO", "VNP.TO", "VOXR.TO", "VQS.TO", "VRE.TO", "VRIF.TO", "VRN.TO", "VRTS.TO", "VSB.TO", "VSC.TO", "VSP.TO", "VUN.TO", "VUS.TO", "VVL.TO", "VVO.TO", "VVSG.TO", "VXC.TO", "VXM.TO", "VZLA.TO", "WCN.TO", "WCP.TO", "WDO.TO", "WEED.TO", "WEF.TO", "WELL.TO", "WFC.TO", "WFG.TO", "WGX.TO", "WILD.TO", "WJX.TO", "WLLW.TO", "WM.TO", "WN.TO", "WNDR.TO", "WOMN.TO", "WPK.TO", "WPM.TO", "WPRT.TO", "WRG.TO", "WRN.TO", "WRX.TO", "WSP.TO", "WSRD.TO", "WSRI.TO", "WTE.TO", "WXM.TO", "X.TO", "XAD.TO", "XAGG.TO", "XAGH.TO", "XAM.TO", "XAU.TO", "XAW.TO", "XBAL.TO", "XBB.TO", "XBM.TO", "XCB.TO", "XCBG.TO", "XCBU.TO", "XCD.TO", "XCG.TO", "XCH.TO", "XCHP.TO", "XCLN.TO", "XCNS.TO", "XCS.TO", "XCSR.TO", "XCV.TO", "XDG.TO", "XDGH.TO", "XDIV.TO", "XDNA.TO", "XDRV.TO", "XDSR.TO", "XDU.TO", "XDUH.TO", "XDV.TO", "XEB.TO", "XEC.TO", "XEF.TO", "XEG.TO", "XEH.TO", "XEI.TO", "XEM.TO", "XEMC.TO", "XEN.TO", "XEQT.TO", "XESG.TO", "XETM.TO", "XEU.TO", "XEXP.TO", "XFH.TO", "XFLB.TO", "XFLI.TO", "XFLX.TO", "XFN.TO", "XFR.TO", "XGB.TO", "XGD.TO", "XGI.TO", "XGRO.TO", "XHAK.TO", "XHB.TO", "XHC.TO", "XHD.TO", "XHU.TO", "XHY.TO", "XIC.TO", "XID.TO", "XIG.TO", "XIGS.TO", "XIN.TO", "XINC.TO", "XIT.TO", "XIU.TO", "XLB.TO", "XLY.TO", "XMA.TO", "XMC.TO", "XMD.TO", "XMH.TO", "XMI.TO", "XML.TO", "XMM.TO", "XMS.TO", "XMTM.TO", "XMU.TO", "XMV.TO", "XMW.TO", "XMY.TO", "XPF.TO", "XQB.TO", "XQLT.TO", "XQQ.TO", "XQQU.TO", "XRB.TO", "XRE.TO", "XSAB.TO", "XSB.TO", "XSC.TO", "XSE.TO", "XSEA.TO", "XSEM.TO", "XSH.TO", "XSHG.TO", "XSHU.TO", "XSI.TO", "XSMC.TO", "XSMH.TO", "XSP.TO", "XSPC.TO", "XST.TO", "XSTB.TO", "XSTH.TO", "XSTP.TO", "XSU.TO", "XSUS.TO", "XTC.TO", "XTD.TO", "XTG.TO", "XTLH.TO", "XTLT.TO", "XTR.TO", "XTRA.TO", "XUH.TO", "XUS.TO", "XUSC.TO", "XUSF.TO", "XUSR.TO", "XUT.TO", "XUU.TO", "XVLU.TO", "XWD.TO", "Y.TO", "YCM.TO", "YGR.TO", "YRB.TO", "ZACE.TO", "ZAG.TO", "ZBAL.TO", "ZBBB.TO", "ZBI.TO", "ZBK.TO", "ZCB.TO", "ZCDB.TO", "ZCH.TO", "ZCLN.TO", "ZCM.TO", "ZCN.TO", "ZCON.TO", "ZCPB.TO", "ZCS.TO", "ZDB.TO", "ZDH.TO", "ZDI.TO", "ZDJ.TO", "ZDM.TO", "ZDV.TO", "ZDY.TO", "ZEA.TO", "ZEAT.TO", "ZEB.TO", "ZEF.TO", "ZEM.TO", "ZEO.TO", "ZEQ.TO", "ZEQT.TO", "ZESG.TO", "ZFC.TO", "ZFH.TO", "ZFL.TO", "ZFM.TO", "ZFN.TO", "ZFS.TO", "ZGB.TO", "ZGD.TO", "ZGI.TO", "ZGLD.TO", "ZGLH.TO", "ZGQ.TO", "ZGRN.TO", "ZGRO.TO", "ZGSB.TO", "ZHP.TO", "ZHU.TO", "ZHY.TO", "ZIC.TO", "ZID.TO", "ZIN.TO", "ZIQ.TO", "ZIU.TO", "ZJG.TO", "ZJK.TO", "ZJPN.TO", "ZLB.TO", "ZLC.TO", "ZLD.TO", "ZLE.TO", "ZLH.TO", "ZLI.TO", "ZLSC.TO", "ZLSU.TO", "ZLU.TO", "ZMBS.TO", "ZMI.TO", "ZMID.TO", "ZMMK.TO", "ZMP.TO", "ZMSB.TO", "ZMT.TO", "ZMU.TO", "ZNQ.TO", "ZPAY.TO", "ZPH.TO", "ZPL.TO", "ZPR.TO", "ZPS.TO", "ZPW.TO", "ZQB.TO", "ZQQ.TO", "ZRE.TO", "ZRR.TO", "ZSB.TO", "ZSDB.TO", "ZSML.TO", "ZSP.TO", "ZST.TO", "ZSU.TO", "ZTIP.TO", "ZUAG.TO", "ZUB.TO", "ZUCM.TO", "ZUD.TO", "ZUE.TO", "ZUGE.TO", "ZUH.TO", "ZUP.TO", "ZUQ.TO", "ZUT.TO", "ZVC.TO", "ZVU.TO", "ZWA.TO", "ZWB.TO", "ZWC.TO", "ZWE.TO", "ZWEN.TO", "ZWG.TO", "ZWH.TO", "ZWHC.TO", "ZWK.TO", "ZWP.TO", "ZWQT.TO", "ZWS.TO", "ZWT.TO", "ZWU.TO", "ZXM.TO", "ZZZD.TO"]  # Replace with your desired tickers

# Desired fields to extract
desired_fields = [
    "symbol", "sector", "industry", "longName", "shortName", "exchange", "country",
    "state", "city", "currency", "sharesOutstanding", "trailingPE",
    "forwardPE", "pegRatio", "grossProfits", "profitMargins"
]

# Initialize an empty list to store the stock information
stock_data = []

# Fetch information for each ticker
for ticker_symbol in tickers:
    ticker = yf.Ticker(ticker_symbol)
    stock_info = ticker.info
    # Extract only the desired fields
    filtered_info = {key: stock_info.get(key, None) for key in desired_fields}
    stock_data.append(filtered_info)

    # Delay of 1 second between requests to avoid hitting rate limit
    time.sleep(1)

# Create a DataFrame from the collected stock data
chart_info_df = pd.DataFrame(stock_data)

# Display the DataFrame with gridlines using tabulate
print(tabulate(chart_info_df, headers="keys", tablefmt="grid"))

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|      | symbol   | sector                 | industry                                 | longName                                                                       | shortName                       | exchange   | country                | state   | city                   | currency   |   sharesOutstanding | trailingPE   | forwardPE    | pegRatio   |      grossProfits |   profitMargins |
+======+==========+========================+==========================================+================================================================================+=================================+============+========================+=========+========================+============+=====================+==============+==============+============+===================+=================+
|    0 | AAB.TO   | Financial Services     | Asset Management                         | Aberdeen International Inc.                                                    | ABERDEEN INTERNATIONAL INC.     | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.59187e+08 |              |              |            |      -8.89676e+06 |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    1 | AAUC.TO  | Basic Materials        | Gold                                     | Allied Gold Corporation                                                        | ALLIED GOLD CORPORATION         | TOR        | Canada                 | ON      | Toronto                | CAD        |         3.28888e+08 |              | 6.182117     |            |       2.40241e+08 |        -0.13515 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    2 | AAV.TO   | Energy                 | Oil & Gas E&P                            | Advantage Energy Ltd.                                                          | ADVANTAGE ENERGY LTD            | TOR        | Canada                 | AB      | Calgary                | CAD        |         1.66972e+08 | 36.11111     | 8.478261     |            |       2.77729e+08 |         0.09331 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    3 | ABX.TO   | Basic Materials        | Gold                                     | Barrick Gold Corporation                                                       | BARRICK GOLD CORPORATION        | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.74805e+09 | 17.537878    | 12.574961    |            |       4.242e+09   |         0.13189 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    4 | AC.TO    | Industrials            | Airlines                                 | Air Canada                                                                     | AIR CANADA                      | TOR        | Canada                 | QC      | Saint-Laurent          | CAD        |         3.58493e+08 | 2.9894896    | 8.205437     |            |       6.865e+09   |         0.11568 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    5 | ACAA.TO  |                        |                                          | Arrow Long/Short Alternative Fund ETF                                          | ARROW LONG SHORT ALTERNATIVE FU | TOR        |                        |         |                        | CAD        |       nan           | 13.669558    |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    6 | ACB.TO   | Healthcare             | Drug Manufacturers - Specialty & Generic | Aurora Cannabis Inc.                                                           | AURORA CANNABIS INC             | TOR        | Canada                 | AB      | Edmonton               | CAD        |         5.48772e+07 |              | -16.878788   |            |       1.5775e+08  |        -0.14708 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    7 | ACD.TO   | Financial Services     | Credit Services                          | Accord Financial Corp.                                                         | ACCORD FINANCIAL                | TOR        | Canada                 | ON      | Toronto                | CAD        |         8.55891e+06 |              | 6.47541      |            |       4.1942e+07  |        -0.21136 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    8 | ACQ.TO   | Consumer Cyclical      | Auto & Truck Dealerships                 | AutoCanada Inc.                                                                | AUTOCANADA INC                  | TOR        | Canada                 | AB      | Edmonton               | CAD        |         2.31417e+07 |              | 14.984918    |            |       1.02707e+09 |        -0.00593 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    9 | ACX.TO   | Energy                 | Oil & Gas Drilling                       | ACT Energy Technologies Ltd.                                                   | ACT ENERGY TECHNOLOGIES LTD     | TOR        | Canada                 | AB      | Calgary                | CAD        |         3.48764e+07 | 5.826087     | 3.8953485    |            |       1.65468e+08 |         0.07601 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   10 | ADCO.TO  | Technology             | Software - Application                   | Adcore Inc.                                                                    | ADCORE INC                      | TOR        | Canada                 | ON      | Toronto                | CAD        |         6.04856e+07 |              |              |            |       9.568e+06   |        -0.03921 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   11 | ADEN.TO  | Industrials            | Industrial Distribution                  | ADENTRA Inc.                                                                   | ADENTRA INC                     | TOR        | Canada                 | BC      | Langley                | CAD        |         2.50189e+07 | 12.552083    | 11.092088    |            |       4.67112e+08 |         0.02074 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   12 | ADIV.TO  |                        |                                          | Arrow EC Equity Advantage Alternative Fund Series ETF                          | ARROW EC EQ ADVTG ALTERNATV FND | TOR        |                        |         |                        | CAD        |       nan           |              |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   13 | ADN.TO   | Basic Materials        | Lumber & Wood Production                 | Acadian Timber Corp.                                                           | ACADIAN TIMBER CORP             | TOR        | Canada                 | NB      | Edmundston             | CAD        |         1.75368e+07 | 10.8         | 16.615385    |            |       3.759e+07   |         0.23165 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   14 | AEG.TO   | Consumer Cyclical      | Restaurants                              | Aegis Brands Inc.                                                              | AEGIS BRANDS INC                | TOR        | Canada                 | ON      | Toronto                | CAD        |         8.52872e+07 |              |              |            |       1.5222e+07  |        -0.27739 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   15 | AEM.TO   | Basic Materials        | Gold                                     | Agnico Eagle Mines Limited                                                     | AGNICO EAGLE MINES LIMITED      | TOR        | Canada                 | ON      | Toronto                | CAD        |         5.01517e+08 | 45.252632    | 25.41376     |            |       4.73119e+09 |         0.12947 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   16 | AFN.TO   | Industrials            | Farm & Heavy Construction Machinery      | Ag Growth International Inc.                                                   | AG GROWTH INTERNATIONAL INC.    | TOR        | Canada                 | MB      | Winnipeg               | CAD        |         1.90749e+07 | 32.382114    | 9.347352     |            |       4.49629e+08 |         0.01706 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   17 | AG.TO    | Basic Materials        | Silver                                   | First Majestic Silver Corp.                                                    | FIRST MAJESTIC SILVER CORP      | TOR        | Canada                 | BC      | Vancouver              | CAD        |         4.79012e+08 |              | 11.838828    |            |       1.55028e+08 |        -0.14885 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   18 | AGG.TO   |                        |                                          | Evolve Canadian Aggregate Bond Enhanced Yield Fund ETF                         | EVOLVE CDN AGGRGT BOND ENHD YLD | TOR        |                        |         |                        | CAD        |       nan           |              |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   19 | AGI.TO   | Basic Materials        | Gold                                     | Alamos Gold Inc.                                                               | ALAMOS GOLD INC CLS A           | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.20282e+08 | 34.32558     | 23.95676     |            |       7.195e+08   |         0.19891 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   20 | AI.TO    | Financial Services     | Mortgage Finance                         | Atrium Mortgage Investment Corporation                                         | ATRIUM MORTGAGE INVESTMENT CORP | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.71161e+07 | 10.561906    | 10.612441    |            |       4.8158e+07  |         0.81768 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   21 | AIDX.TO  | Healthcare             | Medical Care Facilities                  | Healwell AI Inc.                                                               | HEALWELL AI INC                 | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.6588e+08  |              | -22.25       |            |       1.0999e+07  |        -0.79138 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   22 | AIF.TO   | Real Estate            | Real Estate Services                     | Altus Group Limited                                                            | ALTUS GROUP LIMITED             | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.58946e+07 | 222.19232    | 36.049023    |            |       2.99311e+08 |         0.0034  |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   23 | AIGO.TO  |                        |                                          | Global X Artificial Intelligence & Technology Index ETF                        | GLOBAL X ARTIFCL INTELLIG TECH  | TOR        |                        |         |                        | CAD        |       nan           | 33.316402    |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+

In [ ]:
chart_info_df

,symbol,sector,industry,longName,shortName,exchange,country,state,city,currency,sharesOutstanding,trailingPE,forwardPE,pegRatio,grossProfits,profitMargins
0,AAB.TO,Financial Services,Asset Management,Aberdeen International Inc.,ABERDEEN INTERNATIONAL INC.,TOR,Canada,ON,Toronto,CAD,1.591870e+08,None,None,None,-8.896760e+06,NaN
1,AAUC.TO,Basic Materials,Gold,Allied Gold Corporation,ALLIED GOLD CORPORATION,TOR,Canada,ON,Toronto,CAD,3.288880e+08,None,6.182117,None,2.402410e+08,-0.13515
2,AAV.TO,Energy,Oil & Gas E&P,Advantage Energy Ltd.,ADVANTAGE ENERGY LTD,TOR,Canada,AB,Calgary,CAD,1.669720e+08,36.11111,8.478261,None,2.777290e+08,0.09331
3,ABX.TO,Basic Materials,Gold,Barrick Gold Corporation,BARRICK GOLD CORPORATION,TOR,Canada,ON,Toronto,CAD,1.748050e+09,17.537878,12.574961,None,4.242000e+09,0.13189
4,AC.TO,Industrials,Airlines,Air Canada,AIR CANADA,TOR,Canada,QC,Saint-Laurent,CAD,3.584930e+08,2.98949,8.205437,None,6.865000e+09,0.11568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1632,ZWS.TO,None,None,BMO US High Dividend Covered Call Hedged to CA...,BMO US HIGH DIV COV CALL HGD ET,TOR,None,None,None,CAD,NaN,None,None,None,NaN,NaN
1633,ZWT.TO,None,None,BMO Covered Call Technology ETF,BMO COVERED CALL TECHNOLOGY ETF,TOR,None,None,None,CAD,NaN,None,None,None,NaN,NaN
1634,ZWU.TO,None,None,BMO Covered Call Utilities ETF,BMO COVERED CALL UTILITIES ETF,TOR,None,None,None,CAD,NaN,None,None,None,NaN,NaN
1635,ZXM.TO,None,None,CI Morningstar International Momentum Index ET...,CI MORNINGSTAR INTL MOMENTUM ID,TOR,None,None,None,CAD,NaN,12.263581,None,None,NaN,NaN
1636,ZZZD.TO,None,None,BMO Tactical Dividend ETF Fund ETF,BMO TATICAL DIVIDEND ETF FUND,TOR,None,None,None,CAD,NaN,15.417759,None,None,NaN,NaN

In [ ]:
chart_info_df.to_csv('chart_info.csv', index=False)

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
historical_data.to_csv('historical_data.csv', index=False)

In [ ]:
from google.colab import files
files.download('historical_data.csv')

In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv('/content/historical_data.csv')

In [4]:
df2 = pd.read_csv('/content/TSX Ticker Info.csv')

In [5]:
df2

,industry,sector,longBusinessSummary,priceHint,beta,regularMarketVolume,averageVolume,marketCap,fiftyTwoWeekLow,fiftyTwoWeekHigh,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
0,Asset Management,Financial Services,"Aberdeen International Inc., a resource invest...",4.0,1.824,3597.0,387819.0,6.367480e+06,0.02,0.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gold,Basic Materials,"Allied Gold Corporation, together with its sub...",4.0,NaN,115702.0,610130.0,1.105064e+09,2.69,4.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Oil & Gas E&P,Energy,"Advantage Energy Ltd., together with its subsi...",2.0,1.445,257238.0,440509.0,1.636326e+09,8.24,11.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gold,Basic Materials,Barrick Gold Corporation engages in the explor...,2.0,0.480,606469.0,3595311.0,3.990798e+10,18.65,29.50,...,0.315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Airlines,Industrials,"Air Canada provides domestic, U.S. transborder...",2.0,2.407,1672227.0,3851196.0,7.177030e+09,14.47,26.18,...,0.743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,NaN,NaN,NaN,2.0,NaN,1415.0,2954.0,NaN,19.29,21.70,...,NaN,1.295231e+08,20.36416,0.008412,BMO Asset Management Inc,Exchange Traded Fund,0.0534,0.025391,0.062181,0.81
1632,NaN,NaN,NaN,2.0,NaN,1415.0,6568.0,NaN,38.21,54.54,...,NaN,1.766196e+08,52.94526,0.006265,BMO Asset Management Inc,Exchange Traded Fund,0.0334,0.219085,NaN,1.40
1633,NaN,NaN,NaN,2.0,NaN,122568.0,235435.0,NaN,9.67,11.42,...,NaN,1.804342e+09,10.44929,-0.010427,BMO Asset Management Inc,Exchange Traded Fund,0.0797,0.008859,0.017905,0.63
1634,NaN,NaN,NaN,2.0,NaN,200.0,227.0,NaN,37.24,43.55,...,NaN,5.533632e+07,42.61740,-0.000117,CI Investments Inc,Exchange Traded Fund,0.0297,0.050808,0.094018,0.90
1635,NaN,NaN,NaN,2.0,NaN,300.0,409.0,NaN,27.40,29.63,...,NaN,1.549907e+08,28.18158,0.004651,BMO Investments Inc.,Exchange Traded Fund,0.0430,0.041152,0.014513,0.65

In [6]:
merged_df = pd.merge(df1, df2, left_on='tic', right_on='symbol', how='inner')
merged_df

,date,close,high,low,open,volume,tic,day,industry,sector,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,Specialty Industrial Machinery,Industrials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3,Diagnostics & Research,Healthcare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,Other Industrial Metals & Mining,Basic Materials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4,Gold,Basic Materials,...,0.315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4059425,2024-12-30,20.230000,20.309999,20.150000,20.309999,700,ZWS.TO,0,NaN,NaN,...,NaN,1.295231e+08,20.36416,0.008412,BMO Asset Management Inc,Exchange Traded Fund,0.0534,0.025391,0.062181,0.81
4059426,2024-12-30,53.099998,53.360001,52.830002,53.299999,11600,ZWT.TO,0,NaN,NaN,...,NaN,1.766196e+08,52.94526,0.006265,BMO Asset Management Inc,Exchange Traded Fund,0.0334,0.219085,NaN,1.40
4059427,2024-12-30,10.510000,10.520000,10.430000,10.500000,168700,ZWU.TO,0,NaN,NaN,...,NaN,1.804342e+09,10.44929,-0.010427,BMO Asset Management Inc,Exchange Traded Fund,0.0797,0.008859,0.017905,0.63
4059428,2024-12-30,42.599998,42.610001,42.599998,42.610001,300,ZXM.TO,0,NaN,NaN,...,NaN,5.533632e+07,42.61740,-0.000117,CI Investments Inc,Exchange Traded Fund,0.0297,0.050808,0.094018,0.90
4059429,2024-12-30,27.700001,27.700001,27.700001,27.700001,1700,ZZZD.TO,0,NaN,NaN,...,NaN,1.549907e+08,28.18158,0.004651,BMO Investments Inc.,Exchange Traded Fund,0.0430,0.041152,0.014513,0.65

In [12]:
head_values= merged_df.head()
head_values

,date,close,high,low,open,volume,tic,day,industry,sector,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,Specialty Industrial Machinery,Industrials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3,Diagnostics & Research,Healthcare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,Other Industrial Metals & Mining,Basic Materials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4,Gold,Basic Materials,...,0.315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import pandas as pd
import numpy as np

class StockDataIterator:
    def __init__(self, file_path, lookback_window=10, chunk_size=100000):
        self.file_path = file_path
        self.lookback_window = lookback_window
        self.chunk_size = chunk_size

        # Read the first row to get column names dynamically
        with open(self.file_path) as f:
            first_line = f.readline().strip().split(',')

        # Ensure expected columns exist (without 'volume')
        expected_columns = {'date', 'close', 'high', 'low', 'tic'}
        missing_columns = expected_columns - set(first_line)
        if missing_columns:
            raise ValueError(f"Missing columns in CSV: {missing_columns}")

        self.columns = first_line  # Dynamically assign columns
        print("Initializing iterator...")
        self._initialize_metadata()

        self.current_chunk = 0
        self.data_buffer = pd.DataFrame()

    def _initialize_metadata(self):
        """Fast row count without loading data"""
        with open(self.file_path) as f:
            self.total_rows = sum(1 for _ in f) - 1  # Exclude header

        self.num_chunks = (self.total_rows + self.chunk_size - 1) // self.chunk_size
        print(f"Total rows: {self.total_rows:,}, Chunks: {self.num_chunks}")

    def _load_next_chunk(self):
        """Optimized chunk loading"""
        if self.current_chunk >= self.num_chunks:
            return None

        chunk = pd.read_csv(
            self.file_path,
            skiprows=1 + self.current_chunk * self.chunk_size,
            nrows=self.chunk_size,
            names=self.columns,
            usecols=['date', 'tic', 'close', 'high', 'low'],  # Omit 'volume'
            dtype={
                'close': 'float32',
                'high': 'float32',
                'low': 'float32',
                'tic': 'category'
            },
            parse_dates=['date'],
            engine='c'
        )

        if chunk.empty:
            return None

        chunk = chunk.sort_values(['date', 'tic'])
        self.current_chunk += 1
        return chunk

    def __iter__(self):
        self.current_chunk = 0
        self.data_buffer = pd.DataFrame(columns=['date', 'tic', 'close', 'high', 'low'])
        return self

    def __next__(self):
        """Main processing loop with validation"""
        while True:
            # Ensure buffer has enough dates
            while self.data_buffer.empty or self.data_buffer['date'].nunique() < self.lookback_window + 2:
                chunk = self._load_next_chunk()
                if chunk is None:
                    break
                self.data_buffer = pd.concat([self.data_buffer, chunk], ignore_index=True, sort=False)

            if self.data_buffer.empty or self.data_buffer['date'].nunique() < self.lookback_window:
                raise StopIteration

            # Get sorted unique dates
            dates = np.sort(self.data_buffer['date'].unique())
            window_dates = dates[:self.lookback_window]

            # Filter valid stocks
            window_mask = self.data_buffer['date'].isin(window_dates)
            tic_counts = self.data_buffer[window_mask].groupby('tic').size()
            valid_tics = tic_counts[tic_counts == self.lookback_window].index

            if not valid_tics.empty:
                valid_mask = window_mask & self.data_buffer['tic'].isin(valid_tics)
                window_data = self.data_buffer[valid_mask]
                prepared = self._prepare_features(window_data)

                if prepared:
                    # Drop the oldest date to move forward
                    self.data_buffer = self.data_buffer[~self.data_buffer['date'].isin([window_dates[0]])]
                    return prepared

            # Drop the oldest date and continue
            self.data_buffer = self.data_buffer[~self.data_buffer['date'].isin([window_dates[0]])]

    def _prepare_features(self, window_data):
        """Feature calculation"""
        if window_data.empty:
            return []

        features = []
        grouped = window_data.groupby('tic', observed=False)  # Fixed observed=False

        for tic, group in grouped:
            if len(group) != self.lookback_window:
                continue

            close = group['close'].values.astype('float32')
            high = group['high'].values.astype('float32')
            low = group['low'].values.astype('float32')

            features.append({
                'tic': tic,
                'close_prices': close,
                'returns': np.diff(close, prepend=close[0]) / close[0],
                'log_returns': np.log(close / np.roll(close, 1)),
                'price_range': (high - low) / close  # Keep price range feature
            })

        return features

def demonstrate_iterator():
    print("Creating optimized iterator...")
    iterator = StockDataIterator(
        '/content/historical_data.csv',
        lookback_window=10,
        chunk_size=10000
    )

    print("\nProcessing first 3 valid batches:")
    count = 0
    for batch in iterator:
        if count >= 3:
            break
        if batch:
            print(f"\nBatch {count+1}:")
            print(f"Stocks: {len(batch)}")
            print(f"Features for {batch[0]['tic']}:")
            for key, val in batch[0].items():
                print(f" - {key}: {val[:3]}...")
            count += 1

if __name__ == "__main__":
    demonstrate_iterator()

Creating optimized iterator...
Initializing iterator...
Total rows: 4,066,965, Chunks: 407

Processing first 3 valid batches:

Batch 1:
Stocks: 3
Features for DYA.TO:
 - tic: DYA...
 - close_prices: [0.105 0.105 0.105]...
 - returns: [0. 0. 0.]...
 - log_returns: [0. 0. 0.]...
 - price_range: [0. 0. 0.]...

Batch 2:
Stocks: 275
Features for AAB.TO:
 - tic: AAB...
 - close_prices: [0.48962528 0.48962528 0.25866997]...
 - returns: [ 0.          0.         -0.47169808]...
 - log_returns: [ 0.         0.        -0.6380874]...
 - price_range: [0. 0. 0.]...

Batch 3:
Stocks: 275
Features for AAB.TO:
 - tic: AAB...
 - close_prices: [0.48962528 0.25866997 0.48962528]...
 - returns: [ 0.         -0.47169808  0.47169808]...
 - log_returns: [ 0.        -0.6380874  0.6380874]...
 - price_range: [0. 0. 0.]...

<ipython-input-3-ec6463d41d3e>:76: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data_buffer = pd.concat([self.data_buffer, chunk], ignore_index=True, sort=False)
<ipython-input-3-ec6463d41d3e>:76: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data_buffer = pd.concat([self.data_buffer, chunk], ignore_index=True, sort=False)
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

In [4]:
!pip install gym
!pip install finrl
!pip install stable-baselines3
!pip install pandas

import gym
from gym import spaces

class StockTradingEnv(gym.Env):
    def __init__(self, data_iterator):
        super(StockTradingEnv, self).__init__()

        self.data_iterator = data_iterator
        self.initial_cash = 10000.0

        # Define observation space for flattened features
        num_features = 4  # close_prices, returns, log_returns, price_range
        self.lookback_window = data_iterator.lookback_window

        # Flatten the observation space
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.lookback_window * num_features,),
            dtype=np.float32
        )

        self.action_space = spaces.Discrete(3)  # Buy (0), Hold (1), Sell (2)
        self.iterator = iter(self.data_iterator)

    def _get_observation(self):
        if not self.current_features:
            return np.zeros(self.observation_space.shape)

        # Flatten and concatenate all features
        features = self.current_features[0]  # Take first stock's features
        obs = np.concatenate([
            features['close_prices'],
            features['returns'],
            features['log_returns'],
            features['price_range']
        ])
        return obs.astype(np.float32)

    def reset(self):
        self.cash = self.initial_cash
        self.stock_held = 0
        self.iterator = iter(self.data_iterator)  # Reset iterator

        try:
            self.current_features = next(self.iterator)
        except StopIteration:
            self.current_features = None

        return self._get_observation()

    def step(self, action):
        if self.current_features is None:
            return self._get_observation(), 0, True, {}

        current_price = self.current_features[0]['close_prices'][-1]
        prev_portfolio_value = self.cash + self.stock_held * current_price

        # Execute action
        if action == 0 and self.cash >= current_price:  # Buy
            self.stock_held += 1
            self.cash -= current_price
        elif action == 2 and self.stock_held > 0:  # Sell
            self.stock_held -= 1
            self.cash += current_price

        try:
            self.current_features = next(self.iterator)
            new_price = self.current_features[0]['close_prices'][-1]
        except StopIteration:
            return self._get_observation(), 0, True, {}

        current_portfolio_value = self.cash + self.stock_held * new_price
        reward = (current_portfolio_value - prev_portfolio_value) / prev_portfolio_value  # Percentage return

        return self._get_observation(), reward, False, {}

    def render(self):
        if self.current_features:
            current_price = self.current_features[0]['close_prices'][-1]
            portfolio_value = self.cash + self.stock_held * current_price
            print(f"Cash: {self.cash:.2f}, Stocks: {self.stock_held}, "
                  f"Price: {current_price:.2f}, Portfolio: {portfolio_value:.2f}")

Requirement already satisfied: gym in /usr/local/lib/python3.11/dist-packages (0.25.2)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.11/dist-packages (from gym) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gym) (3.1.1)
Requirement already satisfied: gym_notices>=0.0.4 in /usr/local/lib/python3.11/dist-packages (from gym) (0.0.8)
Requirement already satisfied: finrl in /usr/local/lib/python3.11/dist-packages (0.3.7)
Requirement already satisfied: stable-baselines3 in /usr/local/lib/python3.11/dist-packages (2.5.0)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (1.0.0)
Requirement already satisfied: numpy<3.0,>=1.20 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (1.26.4)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (2.5.1+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (3.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from stable-baselines3) (3.10.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3) (0.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3.0,>=2.3->stable-baselines3) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3.0,>=2.3->stable-baselines3) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->stable-baselines3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->stable-baselines3) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->stable-baselines3) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3) (3.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# Test the environment
if __name__ == "__main__":
    # Create the iterator first
    data_iterator = StockDataIterator(
        file_path="/content/new_hist.csv",
        lookback_window=10,
        chunk_size=10000
    )

    # Create the environment with the iterator
    env = StockTradingEnv(data_iterator=data_iterator)

    # Test it
    obs = env.reset()
    done = False
    total_reward = 0

    while not done:
        action = env.action_space.sample()  # Random action
        obs, reward, done, _ = env.step(action)
        total_reward += reward
        env.render()

    print(f"Total reward: {total_reward}")

Initializing iterator...
Total rows: 1,016,741, Chunks: 102
Cash: 10000.00, Stocks: 0, Price: 0.49, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:76: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data_buffer = pd.concat([self.data_buffer, chunk], ignore_index=True, sort=False)
<ipython-input-3-ec6463d41d3e>:76: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data_buffer = pd.concat([self.data_buffer, chunk], ignore_index=True, sort=False)
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 10000.00, Stocks: 0, Price: 0.49, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 10000.00, Stocks: 0, Price: 0.27, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 9999.08, Stocks: 2, Price: 0.46, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 9999.08, Stocks: 2, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 9999.08, Stocks: 2, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00

<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()
<ipython-input-3-ec6463d41d3e>:87: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tic_counts = self.data_buffer[window_mask].groupby('tic').size()

Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.43, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 10000.00, Stocks: 0, Price: 0.46, Portfolio: 10000.00
Cash: 9999.54, Stocks: 1, Price: 0.46, Portfolio: 10000.00
Cash: 9999.08, Stocks: 2, Price: 0.46, Portfolio: 10000.00
Cash: 9998.61, Stocks: 3, Price: 0.46, Portfolio: 10000.00
Cash: 9999.08, Stocks: 2, Price: 0.46, Portfolio: 10000.00
Cash: 9998.61, Stocks: 3, Price: 0.32, Portfolio: 9999.58
Cash: 9998.29, Stocks: 4, Price: 0.46, Portfolio: 10000.14
Cash: 9998.75, Stocks: 3, Price: 0.46, Portfolio: 10000.14
Cash: 9998.75, Stocks: 3, Price: 0.46, Portfolio: 10000.14
Cash: 9998.29, Stocks: 4, Price: 0.46, Portfolio: 10000.14
Cash: 9998.75, Stocks: 3, Price: 0.46, Portfolio: 10000.14
Cash: 9998.29, Stocks: 4, Price: 0.34, Portfolio: 9999.66
Cash: 9997.95, Stocks: 5, Price: 0.46, Portfolio: 10000.26
Cash: 9997.49, Stocks: 6, Price: 0.46, Portfolio: 10000.26
Cash: 9997.95, Stocks: 5, Price: 0.46, Portfolio: 10000.26
Cash: 9997.49, Stocks: 6, Price: 0.46, Portfolio: 10000.26
Cash: 9997.49, Stocks: 6, Price: 0.46, Portfolio: 10000.26
Cash: 9997.49, Stocks: 6, Price: 0.46, Portfolio: 10000.26
Cash: 9997.03, Stocks: 7, Price: 0.37, Portfolio: 9999.61
Cash: 9997.03, Stocks: 7, Price: 0.35, Portfolio: 9999.48
Cash: 9997.38, Stocks: 6, Price: 0.37, Portfolio: 9999.59
Cash: 9997.75, Stocks: 5, Price: 0.37, Portfolio: 9999.59
Cash: 9997.75, Stocks: 5, Price: 0.37, Portfolio: 9999.59
Cash: 9998.12, Stocks: 4, Price: 0.35, Portfolio: 9999.52
Cash: 9997.76, Stocks: 5, Price: 0.37, Portfolio: 9999.61
Cash: 9997.39, Stocks: 6, Price: 0.37, Portfolio: 9999.61
Cash: 9997.03, Stocks: 7, Price: 0.37, Portfolio: 9999.61
Cash: 9997.03, Stocks: 7, Price: 0.37, Portfolio: 9999.61
Cash: 9996.66, Stocks: 8, Price: 0.37, Portfolio: 9999.61
Cash: 9996.66, Stocks: 8, Price: 2.45, Portfolio: 10016.26
Cash: 9999.11, Stocks: 7, Price: 2.04, Portfolio: 10013.39
Cash: 9999.11, Stocks: 7, Price: 2.24, Portfolio: 10014.79
Cash: 9996.87, Stocks: 8, Price: 2.03, Portfolio: 10013.11
Cash: 9998.90, Stocks: 7, Price: 2.05, Portfolio: 10013.25
Cash: 9996.85, Stocks: 8, Price: 2.00, Portfolio: 10012.85
Cash: 9998.85, Stocks: 7, Price: 1.60, Portfolio: 10010.05
Cash: 9998.85, Stocks: 7, Price: 1.21, Portfolio: 10007.32
Cash: 9997.64, Stocks: 8, Price: 1.14, Portfolio: 10006.76
Cash: 9998.78, Stocks: 7, Price: 1.15, Portfolio: 10006.83
Cash: 9998.78, Stocks: 7, Price: 0.38, Portfolio: 10001.43
Cash: 9998.40, Stocks: 8, Price: 0.46, Portfolio: 10002.09
Cash: 9998.40, Stocks: 8, Price: 0.46, Portfolio: 10002.09
Cash: 9997.94, Stocks: 9, Price: 0.46, Portfolio: 10002.09
Cash: 9997.47, Stocks: 10, Price: 0.46, Portfolio: 10002.09
Cash: 9997.47, Stocks: 10, Price: 0.38, Portfolio: 10001.26
Cash: 9997.47, Stocks: 10, Price: 0.46, Portfolio: 10002.09
Cash: 9997.94, Stocks: 9, Price: 0.46, Portfolio: 10002.09
Cash: 9997.47, Stocks: 10, Price: 0.46, Portfolio: 10002.09
Cash: 9997.01, Stocks: 11, Price: 0.46, Portfolio: 10002.09
Cash: 9997.47, Stocks: 10, Price: 0.46, Portfolio: 10002.09
Cash: 9997.94, Stocks: 9, Price: 0.46, Portfolio: 10002.09
Cash: 9997.47, Stocks: 10, Price: 0.46, Portfolio: 10002.09
Cash: 9997.01, Stocks: 11, Price: 0.38, Portfolio: 10001.18
Cash: 9997.39, Stocks: 10, Price: 0.46, Portfolio: 10002.01
Cash: 9996.93, Stocks: 11, Price: 0.46, Portfolio: 10002.01
Cash: 9996.93, Stocks: 11, Price: 0.46, Portfolio: 10002.01
Cash: 9997.39, Stocks: 10, Price: 0.46, Portfolio: 10002.01
Cash: 9997.39, Stocks: 10, Price: 0.38, Portfolio: 10001.18
Cash: 9997.77, Stocks: 9, Price: 0.46, Portfolio: 10001.93
Cash: 9997.77, Stocks: 9, Price: 0.46, Portfolio: 10001.93
Cash: 9997.77, Stocks: 9, Price: 0.78, Portfolio: 10004.79
Cash: 9996.99, Stocks: 10, Price: 0.86, Portfolio: 10005.59
Cash: 9996.13, Stocks: 11, Price: 0.78, Portfolio: 10004.71
Cash: 9995.35, Stocks: 12, Price: 0.72, Portfolio: 10003.99
Cash: 9995.35, Stocks: 12, Price: 0.70, Portfolio: 10003.75
Cash: 9994.65, Stocks: 13, Price: 0.70, Portfolio: 10003.75
Cash: 9994.65, Stocks: 13, Price: 0.63, Portfolio: 10002.84
Cash: 9994.65, Stocks: 13, Price: 0.78, Portfolio: 10004.79
Cash: 9994.65, Stocks: 13, Price: 1.31, Portfolio: 10011.68
Cash: 9994.65, Stocks: 13, Price: 1.17, Portfolio: 10009.86
Cash: 9995.82, Stocks: 12, Price: 0.46, Portfolio: 10001.36
Cash: 9995.36, Stocks: 13, Price: 0.46, Portfolio: 10001.36
Cash: 9994.89, Stocks: 14, Price: 0.46, Portfolio: 10001.36
Cash: 9994.43, Stocks: 15, Price: 0.46, Portfolio: 10001.36
Cash: 9993.97, Stocks: 16, Price: 0.46, Portfolio: 10001.36
Cash: 9993.51, Stocks: 17, Price: 0.46, Portfolio: 10001.36
Cash: 9993.97, Stocks: 16, Price: 0.46, Portfolio: 10001.36
Cash: 9993.51, Stocks: 17, Price: 0.46, Portfolio: 10001.36
Cash: 9993.05, Stocks: 18, Price: 0.46, Portfolio: 10001.36
Cash: 9992.59, Stocks: 19, Price: 0.46, Portfolio: 10001.36
Cash: 9992.59, Stocks: 19, Price: 0.46, Portfolio: 10001.36
Cash: 9993.05, Stocks: 18, Price: 0.40, Portfolio: 10000.20
Cash: 9993.05, Stocks: 18, Price: 0.46, Portfolio: 10001.36
Cash: 9993.05, Stocks: 18, Price: 0.46, Portfolio: 10001.36
Cash: 9993.51, Stocks: 17, Price: 0.46, Portfolio: 10001.36
Cash: 9993.51, Stocks: 17, Price: 0.46, Portfolio: 10001.36
Cash: 9993.97, Stocks: 16, Price: 0.46, Portfolio: 10001.36
Cash: 9993.51, Stocks: 17, Price: 0.46, Portfolio: 10001.36
Cash: 9993.97, Stocks: 16, Price: 0.80, Portfolio: 10006.77
Cash: 9993.17, Stocks: 17, Price: 0.88, Portfolio: 10008.13
Cash: 9994.05, Stocks: 16, Price: 0.87, Portfolio: 10007.97
Cash: 9993.18, Stocks: 17, Price: 0.81, Portfolio: 10006.95
Cash: 9992.37, Stocks: 18, Price: 0.90, Portfolio: 10008.57
Cash: 9992.37, Stocks: 18, Price: 0.85, Portfolio: 10007.67
Cash: 9993.22, Stocks: 17, Price: 0.85, Portfolio: 10007.67
Cash: 9994.07, Stocks: 16, Price: 0.86, Portfolio: 10007.83
Cash: 9994.93, Stocks: 15, Price: 0.90, Portfolio: 10008.43
Cash: 9995.83, Stocks: 14, Price: 0.85, Portfolio: 10007.73
Cash: 9994.98, Stocks: 15, Price: 0.44, Portfolio: 10001.63
Cash: 9995.42, Stocks: 14, Price: 0.42, Portfolio: 10001.37
Cash: 9995.42, Stocks: 14, Price: 0.44, Portfolio: 10001.63
Cash: 9994.98, Stocks: 15, Price: 0.44, Portfolio: 10001.63
Cash: 9995.42, Stocks: 14, Price: 0.44, Portfolio: 10001.63
Cash: 9995.87, Stocks: 13, Price: 0.44, Portfolio: 10001.63
Cash: 9996.31, Stocks: 12, Price: 0.44, Portfolio: 10001.63
Cash: 9996.75, Stocks: 11, Price: 0.42, Portfolio: 10001.43
Cash: 9997.18, Stocks: 10, Price: 0.44, Portfolio: 10001.61
Cash: 9997.62, Stocks: 9, Price: 0.44, Portfolio: 10001.61
Cash: 9998.07, Stocks: 8, Price: 0.44, Portfolio: 10001.61
Cash: 9998.51, Stocks: 7, Price: 0.55, Portfolio: 10002.39
Cash: 9998.51, Stocks: 7, Price: 0.80, Portfolio: 10004.11
Cash: 9998.51, Stocks: 7, Price: 0.75, Portfolio: 10003.76
Cash: 9999.26, Stocks: 6, Price: 0.80, Portfolio: 10004.06
Cash: 9998.46, Stocks: 7, Price: 0.75, Portfolio: 10003.71
Cash: 9997.71, Stocks: 8, Price: 0.75, Portfolio: 10003.71
Cash: 9998.46, Stocks: 7, Price: 0.75, Portfolio: 10003.71
Cash: 9999.21, Stocks: 6, Price: 0.72, Portfolio: 10003.53
Cash: 9999.21, Stocks: 6, Price: 0.70, Portfolio: 10003.41
Cash: 9999.21, Stocks: 6, Price: 0.65, Portfolio: 10003.11
Cash: 9999.86, Stocks: 5, Price: 0.65, Portfolio: 10003.11
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10001.06, Stocks: 3, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10001.06, Stocks: 3, Price: 0.55, Portfolio: 10002.73
Cash: 10001.06, Stocks: 3, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10001.06, Stocks: 3, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 9999.96, Stocks: 5, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10001.06, Stocks: 3, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.55, Portfolio: 10002.73
Cash: 10000.51, Stocks: 4, Price: 0.54, Portfolio: 10002.67
Cash: 9999.97, Stocks: 5, Price: 0.52, Portfolio: 10002.57
Cash: 9999.97, Stocks: 5, Price: 0.51, Portfolio: 10002.52
Cash: 9999.97, Stocks: 5, Price: 0.52, Portfolio: 10002.57
Cash: 10000.49, Stocks: 4, Price: 0.55, Portfolio: 10002.69
Cash: 10000.49, Stocks: 4, Price: 0.52, Portfolio: 10002.57
Cash: 9999.97, Stocks: 5, Price: 0.55, Portfolio: 10002.72
Cash: 10000.52, Stocks: 4, Price: 0.55, Portfolio: 10002.72
Cash: 10001.07, Stocks: 3, Price: 0.53, Portfolio: 10002.66
Cash: 10001.60, Stocks: 2, Price: 0.60, Portfolio: 10002.80
Cash: 10001.00, Stocks: 3, Price: 0.55, Portfolio: 10002.66
Cash: 10001.55, Stocks: 2, Price: 0.42, Portfolio: 10002.40
Cash: 10001.13, Stocks: 3, Price: 0.55, Portfolio: 10002.79
Cash: 10000.58, Stocks: 4, Price: 0.55, Portfolio: 10002.79
Cash: 10000.02, Stocks: 5, Price: 0.55, Portfolio: 10002.79
Cash: 10000.58, Stocks: 4, Price: 0.55, Portfolio: 10002.79
Cash: 10000.58, Stocks: 4, Price: 0.55, Portfolio: 10002.79
Cash: 10000.02, Stocks: 5, Price: 0.55, Portfolio: 10002.79
Cash: 10000.58, Stocks: 4, Price: 0.55, Portfolio: 10002.79
Cash: 10001.13, Stocks: 3, Price: 0.55, Portfolio: 10002.79
Cash: 10001.13, Stocks: 3, Price: 0.55, Portfolio: 10002.79
Cash: 10001.68, Stocks: 2, Price: 0.55, Portfolio: 10002.79
Cash: 10001.68, Stocks: 2, Price: 0.55, Portfolio: 10002.79
Cash: 10001.68, Stocks: 2, Price: 0.48, Portfolio: 10002.64
Cash: 10001.20, Stocks: 3, Price: 0.48, Portfolio: 10002.64
Cash: 10001.20, Stocks: 3, Price: 0.55, Portfolio: 10002.85
Cash: 10001.75, Stocks: 2, Price: 0.55, Portfolio: 10002.85
Cash: 10001.75, Stocks: 2, Price: 0.63, Portfolio: 10003.01
Cash: 10002.38, Stocks: 1, Price: 0.63, Portfolio: 10003.01
Cash: 10001.75, Stocks: 2, Price: 0.64, Portfolio: 10003.03
Cash: 10001.11, Stocks: 3, Price: 0.70, Portfolio: 10003.21
Cash: 10000.41, Stocks: 4, Price: 0.84, Portfolio: 10003.77
Cash: 9999.57, Stocks: 5, Price: 1.00, Portfolio: 10004.57
Cash: 9999.57, Stocks: 5, Price: 0.88, Portfolio: 10003.97
Cash: 9999.57, Stocks: 5, Price: 0.90, Portfolio: 10004.07
Cash: 9998.67, Stocks: 6, Price: 0.44, Portfolio: 10001.33
Cash: 9998.23, Stocks: 7, Price: 0.44, Portfolio: 10001.33
Cash: 9998.67, Stocks: 6, Price: 0.44, Portfolio: 10001.33
Cash: 9998.67, Stocks: 6, Price: 0.44, Portfolio: 10001.33
Cash: 9998.67, Stocks: 6, Price: 0.44, Portfolio: 10001.33
Cash: 9998.67, Stocks: 6, Price: 0.40, Portfolio: 10001.06
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.51, Stocks: 4, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9998.63, Stocks: 6, Price: 0.44, Portfolio: 10001.29
Cash: 9999.07, Stocks: 5, Price: 0.44, Portfolio: 10001.29
Cash: 9999.51, Stocks: 4, Price: 0.44, Portfolio: 10001.29
Cash: 9999.96, Stocks: 3, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.44, Portfolio: 10001.29
Cash: 10000.40, Stocks: 2, Price: 0.42, Portfolio: 10001.23
Cash: 9999.99, Stocks: 3, Price: 0.42, Portfolio: 10001.23
Cash: 9999.57, Stocks: 4, Price: 0.40, Portfolio: 10001.16
Cash: 9999.97, Stocks: 3, Price: 0.42, Portfolio: 10001.21
Cash: 9999.97, Stocks: 3, Price: 0.42, Portfolio: 10001.21
Cash: 10000.38, Stocks: 2, Price: 0.55, Portfolio: 10001.49
Cash: 9999.83, Stocks: 3, Price: 0.55, Portfolio: 10001.49
Cash: 9999.83, Stocks: 3, Price: 0.40, Portfolio: 10001.02
Cash: 9999.83, Stocks: 3, Price: 0.40, Portfolio: 10001.02
Cash: 9999.83, Stocks: 3, Price: 0.55, Portfolio: 10001.46
Cash: 9999.83, Stocks: 3, Price: 0.43, Portfolio: 10001.13
Cash: 10000.26, Stocks: 2, Price: 0.55, Portfolio: 10001.35
Cash: 10000.81, Stocks: 1, Price: 0.55, Portfolio: 10001.35
Cash: 10000.81, Stocks: 1, Price: 0.55, Portfolio: 10001.35
Cash: 10000.81, Stocks: 1, Price: 0.55, Portfolio: 10001.35
Cash: 10001.35, Stocks: 0, Price: 0.48, Portfolio: 10001.35
Cash: 10000.87, Stocks: 1, Price: 0.42, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.42, Portfolio: 10001.29
Cash: 10000.87, Stocks: 1, Price: 0.42, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.42, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.42, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.55, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.41, Portfolio: 10001.29
Cash: 10001.29, Stocks: 0, Price: 0.41, Portfolio: 10001.29
Cash: 10000.88, Stocks: 1, Price: 0.41, Portfolio: 10001.29
Cash: 10000.88, Stocks: 1, Price: 0.41, Portfolio: 10001.29
Cash: 10000.88, Stocks: 1, Price: 0.40, Portfolio: 10001.28
Cash: 10000.88, Stocks: 1, Price: 0.40, Portfolio: 10001.28
Cash: 10000.48, Stocks: 2, Price: 0.37, Portfolio: 10001.21
Cash: 10000.85, Stocks: 1, Price: 0.38, Portfolio: 10001.22
Cash: 10000.85, Stocks: 1, Price: 0.40, Portfolio: 10001.25
Cash: 10000.85, Stocks: 1, Price: 0.39, Portfolio: 10001.24
Cash: 10000.85, Stocks: 1, Price: 0.45, Portfolio: 10001.30
Cash: 10000.85, Stocks: 1, Price: 0.45, Portfolio: 10001.30
Cash: 10000.40, Stocks: 2, Price: 0.45, Portfolio: 10001.30
Cash: 10000.40, Stocks: 2, Price: 0.45, Portfolio: 10001.30
Cash: 10000.40, Stocks: 2, Price: 0.45, Portfolio: 10001.30
Cash: 9999.94, Stocks: 3, Price: 0.45, Portfolio: 10001.30
Cash: 10000.40, Stocks: 2, Price: 0.55, Portfolio: 10001.50
Cash: 10000.95, Stocks: 1, Price: 0.46, Portfolio: 10001.41
Cash: 10000.49, Stocks: 2, Price: 0.46, Portfolio: 10001.41
Cash: 10000.95, Stocks: 1, Price: 0.40, Portfolio: 10001.35
Cash: 10000.55, Stocks: 2, Price: 0.40, Portfolio: 10001.35
Cash: 10000.55, Stocks: 2, Price: 0.40, Portfolio: 10001.35
Cash: 10000.15, Stocks: 3, Price: 0.40, Portfolio: 10001.35
Cash: 10000.15, Stocks: 3, Price: 0.40, Portfolio: 10001.35
Cash: 10000.15, Stocks: 3, Price: 0.40, Portfolio: 10001.35
Cash: 10000.15, Stocks: 3, Price: 0.40, Portfolio: 10001.35
Cash: 9999.76, Stocks: 4, Price: 0.40, Portfolio: 10001.35
Cash: 9999.76, Stocks: 4, Price: 0.40, Portfolio: 10001.35
Cash: 9999.76, Stocks: 4, Price: 0.40, Portfolio: 10001.35
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9998.94, Stocks: 6, Price: 0.42, Portfolio: 10001.44
Cash: 9998.94, Stocks: 6, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9998.94, Stocks: 6, Price: 0.42, Portfolio: 10001.44
Cash: 9998.94, Stocks: 6, Price: 0.42, Portfolio: 10001.44
Cash: 9998.94, Stocks: 6, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9999.36, Stocks: 5, Price: 0.42, Portfolio: 10001.44
Cash: 9999.78, Stocks: 4, Price: 0.42, Portfolio: 10001.44
Cash: 10000.19, Stocks: 3, Price: 0.42, Portfolio: 10001.44
Cash: 10000.61, Stocks: 2, Price: 0.42, Portfolio: 10001.44
Cash: 10000.61, Stocks: 2, Price: 0.42, Portfolio: 10001.44
Cash: 10001.02, Stocks: 1, Price: 0.42, Portfolio: 10001.44
Cash: 10000.61, Stocks: 2, Price: 0.42, Portfolio: 10001.44
Cash: 10001.02, Stocks: 1, Price: 0.42, Portfolio: 10001.44
Cash: 10000.61, Stocks: 2, Price: 0.42, Portfolio: 10001.44
Cash: 10001.02, Stocks: 1, Price: 0.55, Portfolio: 10001.58
Cash: 10001.02, Stocks: 1, Price: 0.55, Portfolio: 10001.58
Cash: 10000.47, Stocks: 2, Price: 0.55, Portfolio: 10001.58
Cash: 10000.47, Stocks: 2, Price: 0.46, Portfolio: 10001.39
Cash: 10000.47, Stocks: 2, Price: 0.46, Portfolio: 10001.39
Cash: 10000.47, Stocks: 2, Price: 0.46, Portfolio: 10001.39
Cash: 10000.93, Stocks: 1, Price: 0.58, Portfolio: 10001.51
Cash: 10000.35, Stocks: 2, Price: 0.55, Portfolio: 10001.44
Cash: 10000.89, Stocks: 1, Price: 0.55, Portfolio: 10001.45
Cash: 10000.34, Stocks: 2, Price: 0.55, Portfolio: 10001.45
Cash: 10000.89, Stocks: 1, Price: 0.55, Portfolio: 10001.45
Cash: 10000.89, Stocks: 1, Price: 0.55, Portfolio: 10001.45
Cash: 10001.45, Stocks: 0, Price: 0.55, Portfolio: 10001.45
Cash: 10001.45, Stocks: 0, Price: 0.56, Portfolio: 10001.45
Cash: 10001.45, Stocks: 0, Price: 0.56, Portfolio: 10001.45
Cash: 10001.45, Stocks: 0, Price: 0.51, Portfolio: 10001.45
Cash: 10000.94, Stocks: 1, Price: 0.51, Portfolio: 10001.45
Cash: 10000.43, Stocks: 2, Price: 0.53, Portfolio: 10001.49
Cash: 10000.43, Stocks: 2, Price: 0.55, Portfolio: 10001.52
Cash: 9999.89, Stocks: 3, Price: 0.53, Portfolio: 10001.47
Cash: 9999.36, Stocks: 4, Price: 0.59, Portfolio: 10001.73
Cash: 9999.36, Stocks: 4, Price: 0.59, Portfolio: 10001.73
Cash: 9999.36, Stocks: 4, Price: 0.56, Portfolio: 10001.61
Cash: 9999.92, Stocks: 3, Price: 0.56, Portfolio: 10001.61
Cash: 9999.36, Stocks: 4, Price: 0.57, Portfolio: 10001.65
Cash: 9999.93, Stocks: 3, Price: 0.57, Portfolio: 10001.65
Cash: 9999.36, Stocks: 4, Price: 0.57, Portfolio: 10001.65
Cash: 9999.93, Stocks: 3, Price: 0.51, Portfolio: 10001.46
Cash: 9999.93, Stocks: 3, Price: 0.51, Portfolio: 10001.46
Cash: 9999.43, Stocks: 4, Price: 0.52, Portfolio: 10001.49
Cash: 9999.94, Stocks: 3, Price: 0.52, Portfolio: 10001.49
Cash: 9999.43, Stocks: 4, Price: 0.52, Portfolio: 10001.49
Cash: 9998.91, Stocks: 5, Price: 0.51, Portfolio: 10001.45
Cash: 9998.40, Stocks: 6, Price: 0.48, Portfolio: 10001.28
Cash: 9998.88, Stocks: 5, Price: 0.52, Portfolio: 10001.47
Cash: 9998.88, Stocks: 5, Price: 0.50, Portfolio: 10001.37
Cash: 9998.88, Stocks: 5, Price: 0.52, Portfolio: 10001.47
Cash: 9998.36, Stocks: 6, Price: 0.52, Portfolio: 10001.47
Cash: 9998.36, Stocks: 6, Price: 0.54, Portfolio: 10001.58
Cash: 9998.90, Stocks: 5, Price: 0.54, Portfolio: 10001.58
Cash: 9999.43, Stocks: 4, Price: 0.54, Portfolio: 10001.58
Cash: 9999.97, Stocks: 3, Price: 0.54, Portfolio: 10001.58
Cash: 10000.51, Stocks: 2, Price: 0.49, Portfolio: 10001.49
Cash: 10000.02, Stocks: 3, Price: 0.49, Portfolio: 10001.49
Cash: 10000.02, Stocks: 3, Price: 0.49, Portfolio: 10001.49
Cash: 10000.51, Stocks: 2, Price: 0.51, Portfolio: 10001.52
Cash: 10001.01, Stocks: 1, Price: 0.51, Portfolio: 10001.52
Cash: 10001.01, Stocks: 1, Price: 0.46, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.46, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.42, Portfolio: 10001.48
Cash: 10001.06, Stocks: 1, Price: 0.43, Portfolio: 10001.49
Cash: 10001.06, Stocks: 1, Price: 0.42, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.38, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.38, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.37, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.40, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.40, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.40, Portfolio: 10001.48
Cash: 10001.48, Stocks: 0, Price: 0.40, Portfolio: 10001.48
Cash: 10001.08, Stocks: 1, Price: 0.38, Portfolio: 10001.46
Cash: 10000.70, Stocks: 2, Price: 0.38, Portfolio: 10001.46
Cash: 10001.08, Stocks: 1, Price: 0.42, Portfolio: 10001.49

There is negative reward because I used 1/4 of the original dataset just for testing purpose