In [196]:
#installing FinRL library
!pip install wrds
!pip install swig

!apt-get update -y -qq && apt-get install -y -qq cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx swig
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wrds in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.3.0)
Requirement already satisfied: packaging<=24.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wrds) (24.1)
Requirement already satisfied: pandas<2.3,>=2.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wrds) (2.2.2)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wrds) (2.9.10)
Requirement already satisfied: sqlalchemy<2.1,>=2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wrds) (2.0.38)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas<2.3,>=2.2->wrds) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas<2.3,>=2.2->wrds) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas<2.3,>=2.2->wrds) (2024.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\nikhi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: swig in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (4.3.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\nikhi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to c:\users\nikhi\appdata\local\temp\pip-req-build-upae03oc
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit 8cf3cacc6f570d26b430e403ea522c8fe9e6876a
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to c:\users\nikhi\appdata\local\temp\pip-install-a4hua_x6\elegantrl_db351e7455104bb79f0dba28c9eced0c
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 3bdc958c8e624b61a9e661832b01fef816924f61
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting alpaca-py<0.38,>=0.37 (from finrl==0.3.6)
  Using cached alpaca_py-0.37.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: alpaca-trade-api<4,>=3 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from finrl==0.3.6) (3.2.0)
Collecting ccxt<4,>=3 (from finrl==0.3.6)
  Using cached ccxt-3.1.60-py2.py3-none-any.whl.metadata (108 kB)
Requirement already satisfied: exchange-calendars<5,>=4 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from finrl==0.3.6) (4.9)
Collecting jqdatasdk<2,>=1 (from finrl==0.3.6)
  Using cached jqdatasdk-1.9.7-py3-none-any.whl.metadata (5.8 kB)
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.6)
  Using cached pyfolio-0.9.2.tar.gz (91 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git 'C:\Users\nikhi\AppData\Local\Temp\pip-req-build-upae03oc'
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\elegantrl_db351e7455104bb79f0dba28c9eced0c'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\pyfolio_3600ed936dd046ec96e3bf4100286145\versioneer.py:468: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\pyfolio_3600ed936dd046ec96e3bf4100286145\setup.py", line 71, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\pyfolio_3600ed936dd046ec96e3bf4100286145\versioneer.py", line 1407, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\pyfolio_3600ed936dd046ec96e3bf4100286145\versioneer.py", line 1341, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\nikhi\AppData\Local\Temp\pip-install-a4hua_x6\pyfolio_3600ed936dd046ec96e3bf4100286145\versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\nikhi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [197]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import datetime
import gym
from finrl import config
from finrl.agents.stablebaselines3.models import DRLEnsembleAgent
from finrl.meta.preprocessor.preprocessors import FeatureEngineer
from pprint import pprint
import sys
sys.path.append("../FinRL-Library")
import itertools

In [198]:
import warnings
warnings.filterwarnings("ignore")

In [199]:
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)

import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

In [200]:
TRAIN_START_DATE = '2017-01-01'
TRAIN_END_DATE = '2021-10-01'
TEST_START_DATE = '2021-10-01'
TEST_END_DATE = '2023-03-01'

In [201]:
df = pd.read_csv('C:/Users/nikhi/Desktop/Capstone project/historical_data.csv')

In [202]:
df.head(5)

         date      close       high        low       open  volume     tic  day
0  2004-01-01   0.105000   0.105000   0.105000   0.105000       0  DYA.TO    3
1  2004-01-01   1.378000   1.378000   1.378000   1.378000       0  EDT.TO    3
2  2004-01-01   0.300000   0.300000   0.300000   0.300000       0  TSK.TO    3
3  2004-01-02   0.489625   0.489625   0.489625   0.489625       0  AAB.TO    4
4  2004-01-02  22.070263  22.211644  21.817266  21.899118  413000  ABX.TO    4

In [203]:
INDICATORS = ['macd',
               'rsi_30',
               'cci_30',
               'dx_30']

In [204]:
TICKERS = ["RY.TO", "TD.TO", "BNS.TO", "ENB.TO", "SHOP.TO"]

In [205]:
df = df[df['tic'].isin(TICKERS)]

In [206]:
df.shape

(23500, 8)

In [207]:
feature_engineer = FeatureEngineer(use_technical_indicator=True, tech_indicator_list=INDICATORS)

In [208]:
df = feature_engineer.add_technical_indicator(df)

In [209]:
df = feature_engineer.add_turbulence(df)

In [210]:
df["date"] = pd.to_datetime(df["date"])

In [211]:
stock_dimension = len(df.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 5, State Space: 31

In [212]:
df.head(5)

,date,close,high,low,open,volume,tic,day,macd,rsi_30,cci_30,dx_30,turbulence
0,2004-01-02,3.425969,3.436876,3.397921,3.406751,1108800,BNS.TO,4,0.00000,NaN,NaN,NaN,0.0
1,2004-01-02,5.307566,5.310516,5.251511,5.251511,439600,ENB.TO,4,0.00000,NaN,NaN,NaN,0.0
2,2004-01-02,13.910172,14.113713,13.834123,13.834123,1938000,RY.TO,4,0.00000,NaN,NaN,NaN,0.0
3,2004-01-02,9.893545,9.945557,9.800829,9.825704,1756600,TD.TO,4,0.00000,NaN,NaN,NaN,0.0
4,2004-01-05,3.422853,3.436357,3.420256,3.420775,1675400,BNS.TO,0,-0.00007,0.0,66.666667,NaN,0.0

In [213]:
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "buy_cost_pct": 0.001,
    "sell_cost_pct": 0.001,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4,
    "print_verbosity":5

}

In [214]:
rebalance_window = 63 # rebalance_window is the number of days to retrain the model
validation_window = 63 # validation_window is the number of days to do validation and trading (e.g. if validation_window=63, then both validation and trading period will be 63 days)

ensemble_agent = DRLEnsembleAgent(df,
                 train_period=(TRAIN_START_DATE,TRAIN_END_DATE),
                 val_test_period=(TEST_START_DATE,TEST_END_DATE),
                 rebalance_window=rebalance_window,
                 validation_window=validation_window,
                 **env_kwargs)

In [215]:
from stable_baselines3 import SAC

SAC_model_kwargs = {
    "buffer_size": 100000,
    "learning_rate": 0.0005,
    "batch_size": 64,
    "ent_coef": "auto",  # Automatic entropy coefficient
    "tau": 0.005,       # Target network update rate
    "gamma": 0.99,      # Discount factor
    "learning_starts": 1000
}


timesteps_dict = {'a2c' : 0,
                 'ppo' : 0,
                 'ddpg' : 0,
                 'sac' : 10_000,  # Focus on SAC
                 'td3' : 0
                 }

In [216]:
df_summary = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  
    PPO_model_kwargs={},  
    DDPG_model_kwargs={},  
    SAC_model_kwargs=SAC_model_kwargs,  # Use SAC config
    TD3_model_kwargs={},  
    timesteps_dict=timesteps_dict
)

============Start Ensemble Strategy============
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_2

======a2c Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
a2c Sharpe Ratio:  -0.16962801171200861
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_126_2
======ddpg Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ddpg Sharpe Ratio:  0.242884150618702
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_126_2
======td3 Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
td3 Sharpe Ratio:  0.0
======sac Training========
{'buffer_size': 100000, 'learning_rate': 0.0005, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_126_2
day: 1192, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1491797.74
total_reward: 491797.74
total_cost: 999.00
total_trades: 5790
Sharpe: 0.512
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 19        |
|    time_elapsed    | 239       |
|    total_timesteps | 4772      |
| train/             |           |
|    actor_loss      | 5.65e+03  |
|    critic_loss     | 3.51e+03  |
|    ent_coef        | 6.29      |
|    ent_coef_loss   | -182      |
|    learning_rate   | 0.0005    |
|    n_updates       | 3771      |
|    reward          | 1.5784123 |
----------------------------------
day: 1192, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1491797.74
total_reward: 491797.74
total_cost: 999.00
total_trades: 5790
Sharpe: 0.512
=================================
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 20        |
|    time_elapsed    | 464       |
|    total_timesteps | 9544      |
| train/             |           |
|    actor_loss      | 7.18e+04  |
|    critic_loss     | 3.08e+05  |
|    ent_coef        | 67.1      |
|    ent_coef_loss   | -406      |
|    learning_rate   | 0.0005    |
|    n_updates       | 8543      |
|    reward          | 1.5784123 |
----------------------------------
======sac Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
sac Sharpe Ratio:  0.3929993019077747
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_126_2
======ppo Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ppo Sharpe Ratio:  0.3180505314534718
======Best Model Retraining from:  2017-01-01 to  2022-01-05 00:00:00
======Trading from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-01-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_189_2
======a2c Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
a2c Sharpe Ratio:  -0.2603265488412802
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_189_2
======ddpg Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ddpg Sharpe Ratio:  -0.10098236821174222
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_189_2
======td3 Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
td3 Sharpe Ratio:  -0.029529296769953892
======sac Training========
{'buffer_size': 100000, 'learning_rate': 0.0005, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_189_2
day: 1255, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 2816540.42
total_reward: 1816540.42
total_cost: 999.00
total_trades: 5020
Sharpe: 0.983
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 28         |
|    time_elapsed    | 177        |
|    total_timesteps | 5024       |
| train/             |            |
|    actor_loss      | 6.81e+03   |
|    critic_loss     | 3.13e+04   |
|    ent_coef        | 7.32       |
|    ent_coef_loss   | -126       |
|    learning_rate   | 0.0005     |
|    n_updates       | 4023       |
|    reward          | -12.838872 |
-----------------------------------
day: 1255, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 2816540.42
total_reward: 1816540.42
total_cost: 999.00
total_trades: 5020
Sharpe: 0.983
=================================
======sac Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
sac Sharpe Ratio:  -0.15921532249998843
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_189_2
======ppo Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ppo Sharpe Ratio:  -0.056165228802213495
======Best Model Retraining from:  2017-01-01 to  2022-04-05 00:00:00
======Trading from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-04-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_252_2
======a2c Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
a2c Sharpe Ratio:  -0.551517242400055
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_252_2
======ddpg Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ddpg Sharpe Ratio:  -0.4362329352038983
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_252_2
======td3 Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
td3 Sharpe Ratio:  -0.15344633559333856
======sac Training========
{'buffer_size': 100000, 'learning_rate': 0.0005, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_252_2
day: 1318, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 2706656.88
total_reward: 1706656.88
total_cost: 999.00
total_trades: 3954
Sharpe: 0.855
=================================
---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 26       |
|    time_elapsed    | 197      |
|    total_timesteps | 5276     |
| train/             |          |
|    actor_loss      | 7.54e+03 |
|    critic_loss     | 7.44e+03 |
|    ent_coef        | 8.47     |
|    ent_coef_loss   | -148     |
|    learning_rate   | 0.0005   |
|    n_updates       | 4275     |
|    reward          | 6.927641 |
---------------------------------
day: 1318, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 2706656.88
total_reward: 1706656.88
total_cost: 999.00
total_trades: 3954
Sharpe: 0.855
=================================
======sac Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
sac Sharpe Ratio:  -0.3276576541934657
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_252_2
======ppo Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ppo Sharpe Ratio:  -0.5092243392770245
======Best Model Retraining from:  2017-01-01 to  2022-07-06 00:00:00
======Trading from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-07-06 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_315_2
======a2c Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
a2c Sharpe Ratio:  -0.017901854318655604
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_315_2
======ddpg Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ddpg Sharpe Ratio:  -0.1331236028691857
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_315_2
======td3 Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
td3 Sharpe Ratio:  0.15130760541434843
======sac Training========
{'buffer_size': 100000, 'learning_rate': 0.0005, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_315_2
day: 1381, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1471299.31
total_reward: 471299.31
total_cost: 998.99
total_trades: 2762
Sharpe: 0.444
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 22         |
|    time_elapsed    | 247        |
|    total_timesteps | 5528       |
| train/             |            |
|    actor_loss      | 1.69e+04   |
|    critic_loss     | 3.04e+04   |
|    ent_coef        | 9.61       |
|    ent_coef_loss   | -259       |
|    learning_rate   | 0.0005     |
|    n_updates       | 4527       |
|    reward          | -0.6019052 |
-----------------------------------
day: 1381, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1471299.31
total_reward: 471299.31
total_cost: 998.99
total_trades: 2762
Sharpe: 0.444
=================================
======sac Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
sac Sharpe Ratio:  0.10002524134441973
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_315_2
======ppo Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ppo Sharpe Ratio:  -0.09552861602791109
======Best Model Retraining from:  2017-01-01 to  2022-10-05 00:00:00
======Trading from:  2022-10-05 00:00:00 to  2023-01-06 00:00:00
Ensemble Strategy took:  31.150932331879932  minutes

In [218]:
df_summary

,Iter,Val Start,Val End,Model Used,A2C Sharpe,PPO Sharpe,DDPG Sharpe,SAC Sharpe,TD3 Sharpe
0,126,2021-10-04 00:00:00,2022-01-05 00:00:00,SAC,-0.169628,0.318051,0.242884,0.392999,0.0
1,189,2022-01-05 00:00:00,2022-04-05 00:00:00,TD3,-0.260327,-0.056165,-0.100982,-0.159215,-0.029529
2,252,2022-04-05 00:00:00,2022-07-06 00:00:00,TD3,-0.551517,-0.509224,-0.436233,-0.327658,-0.153446
3,315,2022-07-06 00:00:00,2022-10-05 00:00:00,TD3,-0.017902,-0.095529,-0.133124,0.100025,0.151308

For SAC (a reinforcement learning model), tuning involves adjusting hyperparameters such as:
Learning rate – How fast the model updates weights.
Gamma (γ) – Discount factor for future rewards.
Batch size – Number of experiences used per training step.
Tau (τ) – Controls soft update of target networks.
Alpha (α) – Controls exploration vs. exploitation trade-off.

In [219]:
SAc_model_kwargs_TUNING = {
    "learning_rate": 0.0005,
    "buffer_size": 50000,
    "batch_size": 64,
    "ent_coef": "auto",  # Automatic entropy coefficient
    "tau": 0.005,       # Target network update rate
    "gamma": 0.99,      # Discount factor
    "learning_starts": 1000
}

In [220]:
df_summary_tuning = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  
    PPO_model_kwargs={},  
    DDPG_model_kwargs={},  
    SAC_model_kwargs=SAc_model_kwargs_TUNING,  # Use SAC config
    TD3_model_kwargs={},  
    timesteps_dict=timesteps_dict
)
df_summary_tuning

============Start Ensemble Strategy============
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_3
======a2c Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
a2c Sharpe Ratio:  0.22899223256664197
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_126_3
======ddpg Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ddpg Sharpe Ratio:  0.2996524179757144
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_126_3
======td3 Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
td3 Sharpe Ratio:  -0.177465909633174
======sac Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_126_3
day: 1192, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 4533738.66
total_reward: 3533738.66
total_cost: 2299.50
total_trades: 3161
Sharpe: 1.172
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 31         |
|    time_elapsed    | 152        |
|    total_timesteps | 4772       |
| train/             |            |
|    actor_loss      | 6.29e+03   |
|    critic_loss     | 6.12e+03   |
|    ent_coef        | 6.34       |
|    ent_coef_loss   | -128       |
|    learning_rate   | 0.0005     |
|    n_updates       | 3771       |
|    reward          | -1.5953833 |
-----------------------------------
day: 1192, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 4953261.99
total_reward: 3953261.99
total_cost: 999.00
total_trades: 2384
Sharpe: 1.241
=================================
-----------------------------------
| time/              |            |
|    episodes        | 8          |
|    fps             | 27         |
|    time_elapsed    | 350        |
|    total_timesteps | 9544       |
| train/             |            |
|    actor_loss      | 5.51e+04   |
|    critic_loss     | 2.05e+06   |
|    ent_coef        | 68.9       |
|    ent_coef_loss   | -295       |
|    learning_rate   | 0.0005     |
|    n_updates       | 8543       |
|    reward          | -1.5953833 |
-----------------------------------
======sac Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
sac Sharpe Ratio:  -0.1487408317062874
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_126_3
======ppo Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ppo Sharpe Ratio:  0.04735558144708061
======Best Model Retraining from:  2017-01-01 to  2022-01-05 00:00:00
======Trading from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-01-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_189_3
======a2c Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
a2c Sharpe Ratio:  0.03684945242879222
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_189_3
======ddpg Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ddpg Sharpe Ratio:  -0.1627166157348534
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_189_3
======td3 Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
td3 Sharpe Ratio:  -0.06619087485041619
======sac Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_189_3
day: 1255, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1892630.40
total_reward: 892630.40
total_cost: 998.98
total_trades: 1255
Sharpe: 0.716
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 31        |
|    time_elapsed    | 160       |
|    total_timesteps | 5024      |
| train/             |           |
|    actor_loss      | 7.82e+03  |
|    critic_loss     | 2.71e+05  |
|    ent_coef        | 7.47      |
|    ent_coef_loss   | -94.3     |
|    learning_rate   | 0.0005    |
|    n_updates       | 4023      |
|    reward          | 2.7082314 |
----------------------------------
day: 1255, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1892630.40
total_reward: 892630.40
total_cost: 998.98
total_trades: 1255
Sharpe: 0.716
=================================
======sac Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
sac Sharpe Ratio:  -0.058881137832029605
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_189_3
======ppo Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ppo Sharpe Ratio:  -0.11642033481341725
======Best Model Retraining from:  2017-01-01 to  2022-04-05 00:00:00
======Trading from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-04-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_252_3
======a2c Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
a2c Sharpe Ratio:  -0.4888310347533049
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_252_3
======ddpg Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ddpg Sharpe Ratio:  -0.3244230728227674
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_252_3
======td3 Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
td3 Sharpe Ratio:  -0.37558886207558384
======sac Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_252_3
day: 1318, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1829215.29
total_reward: 829215.29
total_cost: 1008.22
total_trades: 2649
Sharpe: 0.705
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 29        |
|    time_elapsed    | 176       |
|    total_timesteps | 5276      |
| train/             |           |
|    actor_loss      | 6.99e+03  |
|    critic_loss     | 8.18e+03  |
|    ent_coef        | 7.65      |
|    ent_coef_loss   | -142      |
|    learning_rate   | 0.0005    |
|    n_updates       | 4275      |
|    reward          | 1.9188378 |
----------------------------------
day: 1318, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1829168.33
total_reward: 829168.33
total_cost: 998.99
total_trades: 2636
Sharpe: 0.705
=================================
======sac Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
sac Sharpe Ratio:  -0.31772797236622147
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_252_3
======ppo Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ppo Sharpe Ratio:  -0.42092499825303753
======Best Model Retraining from:  2017-01-01 to  2022-07-06 00:00:00
======Trading from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
============================================
turbulence_threshold:  60.18625422507027
======Model training from:  2017-01-01 to  2022-07-06 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_315_3
======a2c Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
a2c Sharpe Ratio:  -0.16607567211363025
======ddpg Training========
{}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_315_3
======ddpg Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ddpg Sharpe Ratio:  -0.05048445114832332
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_315_3
======td3 Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
td3 Sharpe Ratio:  0.10002524134441973
======sac Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 64, 'ent_coef': 'auto', 'tau': 0.005, 'gamma': 0.99, 'learning_starts': 1000}
Using cpu device
Logging to tensorboard_log/sac\sac_315_3
day: 1381, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1631840.20
total_reward: 631840.20
total_cost: 1227.86
total_trades: 5321
Sharpe: 0.563
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 25         |
|    time_elapsed    | 215        |
|    total_timesteps | 5528       |
| train/             |            |
|    actor_loss      | 1.05e+04   |
|    critic_loss     | 1.62e+05   |
|    ent_coef        | 9.05       |
|    ent_coef_loss   | -165       |
|    learning_rate   | 0.0005     |
|    n_updates       | 4527       |
|    reward          | -0.7349823 |
-----------------------------------
day: 1381, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1598903.01
total_reward: 598903.01
total_cost: 999.00
total_trades: 5459
Sharpe: 0.545
=================================
======sac Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
sac Sharpe Ratio:  0.049354905296076695
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_315_3
======ppo Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ppo Sharpe Ratio:  -0.040575270168671865
======Best Model Retraining from:  2017-01-01 to  2022-10-05 00:00:00
======Trading from:  2022-10-05 00:00:00 to  2023-01-06 00:00:00
Ensemble Strategy took:  25.851130870978036  minutes

,Iter,Val Start,Val End,Model Used,A2C Sharpe,PPO Sharpe,DDPG Sharpe,SAC Sharpe,TD3 Sharpe
0,126,2021-10-04 00:00:00,2022-01-05 00:00:00,DDPG,0.228992,0.047356,0.299652,-0.148741,-0.177466
1,189,2022-01-05 00:00:00,2022-04-05 00:00:00,A2C,0.036849,-0.11642,-0.162717,-0.058881,-0.066191
2,252,2022-04-05 00:00:00,2022-07-06 00:00:00,SAC,-0.488831,-0.420925,-0.324423,-0.317728,-0.375589
3,315,2022-07-06 00:00:00,2022-10-05 00:00:00,TD3,-0.166076,-0.040575,-0.050484,0.049355,0.100025

SAC Hyperparameter Tuning with Optuna

In [175]:
!pip install optuna

Defaulting to user installation because normal site-packages is not writeable
Collecting optuna
  Downloading optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.14.1-py3-none-any.whl.metadata (7.4 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (24.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (2.0.38)
Requirement already satisfied: tqdm in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (4.66.5)
Requirement already satisfied: PyYAML in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (6.0.1)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.9-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: colorama in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Downloading optuna-4.2.1-py3-none-any.whl (383 kB)
Downloading alembic-1.14.1-py3-none-any.whl (233 kB)
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading Mako-1.3.9-py3-none-any.whl (78 kB)
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.9 alembic-1.14.1 colorlog-6.9.0 optuna-4.2.1

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\nikhi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [191]:
import optuna
import gymnasium as gym 
import torch
from stable_baselines3 import SAC
from stable_baselines3.common.evaluation import evaluate_policy

In [177]:
# Define the environment
ENV_NAME = "Pendulum-v1"  # Change this to your custom environment if needed

In [ ]:
def optimize_sac(trial):
    """ Objective function for Optuna to optimize SAC hyperparameters. """
    
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 3e-4)
    gamma = trial.suggest_float("gamma", 0.90, 0.99)
    batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    tau = trial.suggest_float("tau", 0.005, 0.05)
    alpha = trial.suggest_float("alpha", 0.05, 0.3)

In [192]:
def optimize_sac(trial):
    """ Objective function for Optuna to optimize SAC hyperparameters. """
    
    # Sample hyperparameters
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 3e-4)
    gamma = trial.suggest_float("gamma", 0.90, 0.99)
    batch_size = trial.suggest_categorical("batch_size", [64, 128, 256, 512])
    tau = trial.suggest_float("tau", 0.005, 0.05)
    alpha = trial.suggest_float("alpha", 0.05, 0.3)
    
    # Create environment
    env = gym.make(ENV_NAME)

    # Define the SAC model **inside** the function
    model = SAC(
        "MlpPolicy",
        env,
        learning_rate=learning_rate,
        gamma=gamma,
        batch_size=batch_size,
        tau=tau,
        ent_coef=alpha,
        verbose=0,
        tensorboard_log="./sac_tuning/"
    )

    # Train model for a few time steps
    model.learn(total_timesteps=10000)

    # Evaluate performance
    mean_reward, _ = evaluate_policy(model, env, n_eval_episodes=5)

    env.close()
    
    return mean_reward

In [190]:
pip install gymnasium[box2d] stable-baselines3 optuna

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: stable-baselines3 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.5.0)
Requirement already satisfied: optuna in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (4.2.1)
Requirement already satisfied: gymnasium[box2d] in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.0.0)
Requirement already satisfied: numpy>=1.21.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gymnasium[box2d]) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gymnasium[box2d]) (3.1.1)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gymnasium[box2d]) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gymnasium[box2d]) (0.0.4)
Collecting box2d-py==2.3.5 (from gymnasium[box2d])
  Downloading box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pygame>=2.1.3 (from gymnasium[box2d])
  Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: swig==4.* in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from gymnasium[box2d]) (4.3.0)
Requirement already satisfied: torch<3.0,>=2.3 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from stable-baselines3) (2.6.0)
Requirement already satisfied: pandas in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from stable-baselines3) (2.2.2)
Requirement already satisfied: matplotlib in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from stable-baselines3) (3.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (1.14.1)
Requirement already satisfied: colorlog in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (6.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (24.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (2.0.38)
Requirement already satisfied: tqdm in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (4.66.5)
Requirement already satisfied: PyYAML in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optuna) (6.0.1)
Requirement already satisfied: Mako in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from alembic>=1.5.0->optuna) (1.3.9)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: filelock in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (3.15.4)
Requirement already satisfied: networkx in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (3.1.4)
Requirement already satisfied: fsspec in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (2024.6.1)
Requirement already satisfied: setuptools in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (71.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch<3.0,>=2.3->stable-baselines3) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sympy==1.13.1->torch<3.0,>=2.3->stable-baselines3) (1.3.0)
Requirement already satisfied: colorama in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (1.4.5)
Requirement already satisfied: pillow>=8 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->stable-baselines3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->stable-baselines3) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->stable-baselines3) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nikhi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3) (2.1.5)
Downloading pygame-2.6.1-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.6 MB 4.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/10.6 MB 5.0 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/10.6 MB 5.1 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/10.6 MB 5.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.8/10.6 MB 6.0 MB/s eta 0:00:01
   --------------------------- ------------ 7.3/10.6 MB 6.3 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.6 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 6.8 MB/s eta 0:00:00
Building wheels for collected packages: box2d-py
  Building wheel for box2d-py (setup.py): started
  Building wheel for box2d-py (setup.py): finished with status 'error'
  Running setup.py clean for box2d-py
Failed to build box2d-py
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Using setuptools (version 71.1.0).
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\Box2D
      copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-312\Box2D
      copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-312\Box2D
      creating build\lib.win-amd64-cpython-312\Box2D\b2
      copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-312\Box2D\b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
      swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
      Box2D\Common\b2Math.h(67) : Warning 302: Redefinition of identifier 'b2Vec2' by %extend ignored,
      Box2D\Box2D_math.i(47) : Warning 302: %extend definition of 'b2Vec2'.
      Box2D\Common\b2Math.h(158) : Warning 302: Redefinition of identifier 'b2Vec3' by %extend ignored,
      Box2D\Box2D_math.i(168) : Warning 302: %extend definition of 'b2Vec3'.
      Box2D\Common\b2Math.h(197) : Warning 302: Redefinition of identifier 'b2Mat22' by %extend ignored,
      Box2D\Box2D_math.i(301) : Warning 302: %extend definition of 'b2Mat22'.
      Box2D\Common\b2Math.h(271) : Warning 302: Redefinition of identifier 'b2Mat33' by %extend ignored,
      Box2D\Box2D_math.i(372) : Warning 302: %extend definition of 'b2Mat33'.
      Box2D\Collision\b2DynamicTree.h(44) : Warning 312: Nested union not currently supported (ignored).
      Box2D\Common\b2Settings.h(144) : Warning 506: Can't wrap varargs with keyword arguments enabled
      Box2D\Common\b2Math.h(91) : Warning 509: Overloaded method b2Vec2::operator ()(int32) effectively ignored,
      Box2D\Common\b2Math.h(85) : Warning 509: as it is shadowed by b2Vec2::operator ()(int32) const.
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for box2d-py

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\nikhi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (box2d-py)

In [193]:
# Run Optuna optimization
study = optuna.create_study(direction="maximize")  # Maximize the reward
study.optimize(optimize_sac, n_trials=20)  # Run 20 trials

[I 2025-03-03 03:51:49,649] A new study created in memory with name: no-name-58ade97c-b072-4235-9abc-8dcfa2f43abc
[I 2025-03-03 03:56:50,047] Trial 0 finished with value: -1031.1671267524362 and parameters: {'learning_rate': 5.062425619318205e-05, 'gamma': 0.9762215219235065, 'batch_size': 512, 'tau': 0.043324338558708965, 'alpha': 0.11054429661089386}. Best is trial 0 with value: -1031.1671267524362.
[I 2025-03-03 03:59:55,870] Trial 1 finished with value: -1677.5736792325974 and parameters: {'learning_rate': 1.0337890818149418e-05, 'gamma': 0.979757912042467, 'batch_size': 128, 'tau': 0.014850779447869621, 'alpha': 0.15739903735542082}. Best is trial 0 with value: -1031.1671267524362.
[I 2025-03-03 04:03:07,397] Trial 2 finished with value: -792.9772980809212 and parameters: {'learning_rate': 9.882759814175665e-05, 'gamma': 0.9220796892184415, 'batch_size': 256, 'tau': 0.005465935002723749, 'alpha': 0.09923592660302245}. Best is trial 2 with value: -792.9772980809212.
[I 2025-03-03 04:05:01,318] Trial 3 finished with value: -876.6915627658367 and parameters: {'learning_rate': 0.00016721014419955377, 'gamma': 0.9327960730900183, 'batch_size': 64, 'tau': 0.016521077072625744, 'alpha': 0.13633202438913783}. Best is trial 2 with value: -792.9772980809212.
[I 2025-03-03 04:08:11,037] Trial 4 finished with value: -1081.8008570075035 and parameters: {'learning_rate': 2.3381922770115194e-05, 'gamma': 0.9118352514853241, 'batch_size': 256, 'tau': 0.04056594554449745, 'alpha': 0.28802978178794275}. Best is trial 2 with value: -792.9772980809212.
[I 2025-03-03 04:10:45,858] Trial 5 finished with value: -692.9930237472057 and parameters: {'learning_rate': 0.00010526918747214566, 'gamma': 0.9743713418275894, 'batch_size': 128, 'tau': 0.03154636284729839, 'alpha': 0.21296237396553308}. Best is trial 5 with value: -692.9930237472057.
[I 2025-03-03 04:13:54,157] Trial 6 finished with value: -848.1207657247782 and parameters: {'learning_rate': 5.777832180117753e-05, 'gamma': 0.9579250583148228, 'batch_size': 256, 'tau': 0.024216464708196755, 'alpha': 0.13115087080592702}. Best is trial 5 with value: -692.9930237472057.
[I 2025-03-03 04:16:31,625] Trial 7 finished with value: -170.1272806494031 and parameters: {'learning_rate': 0.00017314428653836687, 'gamma': 0.9785325564404298, 'batch_size': 128, 'tau': 0.028517947760463333, 'alpha': 0.17275511797181314}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:20:19,958] Trial 8 finished with value: -1579.4084303608165 and parameters: {'learning_rate': 1.0041010680228475e-05, 'gamma': 0.9228722751860718, 'batch_size': 512, 'tau': 0.02015089459753959, 'alpha': 0.10868691390055053}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:24:09,663] Trial 9 finished with value: -926.0952578905969 and parameters: {'learning_rate': 2.2598889846623445e-05, 'gamma': 0.9319534747901282, 'batch_size': 512, 'tau': 0.03854048166170176, 'alpha': 0.29244319587339457}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:26:50,984] Trial 10 finished with value: -279.63135286970066 and parameters: {'learning_rate': 0.00024616180154564225, 'gamma': 0.9503223375838982, 'batch_size': 128, 'tau': 0.04878775800208568, 'alpha': 0.20943912800362927}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:29:27,297] Trial 11 finished with value: -196.5814512080513 and parameters: {'learning_rate': 0.0002595298747716563, 'gamma': 0.9551190276349035, 'batch_size': 128, 'tau': 0.049354221807194315, 'alpha': 0.21186016057533985}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:32:14,780] Trial 12 finished with value: -1193.0839410167187 and parameters: {'learning_rate': 0.00029523919524765716, 'gamma': 0.9894040150413527, 'batch_size': 128, 'tau': 0.031729747293763, 'alpha': 0.20868424029483645}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:34:50,572] Trial 13 finished with value: -770.0006310731172 and parameters: {'learning_rate': 0.00015662004036658204, 'gamma': 0.9572016250906912, 'batch_size': 128, 'tau': 0.049251151791114035, 'alpha': 0.058585564952443936}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:36:57,654] Trial 14 finished with value: -684.925310369581 and parameters: {'learning_rate': 0.00015943926495486972, 'gamma': 0.9646867923411485, 'batch_size': 64, 'tau': 0.03358803007723687, 'alpha': 0.24245441157336037}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:39:29,723] Trial 15 finished with value: -205.00551906581967 and parameters: {'learning_rate': 8.397421171487181e-05, 'gamma': 0.9402040587135856, 'batch_size': 128, 'tau': 0.0066204689664858055, 'alpha': 0.1753012174798086}. Best is trial 7 with value: -170.1272806494031.
[I 2025-03-03 04:42:07,656] Trial 16 finished with value: -145.90164729088508 and parameters: {'learning_rate': 0.00021319194087739252, 'gamma': 0.9899375818292613, 'batch_size': 128, 'tau': 0.025405564719087035, 'alpha': 0.2515576894516406}. Best is trial 16 with value: -145.90164729088508.
[I 2025-03-03 04:44:43,123] Trial 17 finished with value: -1074.8280710458755 and parameters: {'learning_rate': 5.8254505512736896e-05, 'gamma': 0.9894543545157236, 'batch_size': 128, 'tau': 0.02614828438346779, 'alpha': 0.25945392256950406}. Best is trial 16 with value: -145.90164729088508.
[I 2025-03-03 04:46:39,355] Trial 18 finished with value: -148.7560457506608 and parameters: {'learning_rate': 0.00019469747015626835, 'gamma': 0.9678309319682471, 'batch_size': 64, 'tau': 0.021144665809021135, 'alpha': 0.16956730846900528}. Best is trial 16 with value: -145.90164729088508.
[I 2025-03-03 04:48:33,511] Trial 19 finished with value: -1142.5986034959556 and parameters: {'learning_rate': 2.9424252239763552e-05, 'gamma': 0.9665278106787206, 'batch_size': 64, 'tau': 0.012422078692144655, 'alpha': 0.244173060695387}. Best is trial 16 with value: -145.90164729088508.

In [194]:
# Print best parameters
print("Best hyperparameters:", study.best_params)

Best hyperparameters: {'learning_rate': 0.00021319194087739252, 'gamma': 0.9899375818292613, 'batch_size': 128, 'tau': 0.025405564719087035, 'alpha': 0.2515576894516406}

references:
[GitHUB](https://github.com/AI4Finance-Foundation/FinRL/blob/master/examples/Stock_NeurIPS2018_SB3.ipynb)
https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#optimizing-hyperparameters-with-optuna
https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#optimizing-hyperparameters-with-optuna