**WORK LOGS**


RAJKARAN  ---- 15/01/2025 : 19/01/2025 ----- Data Collection, Data Merging

# **DATA EXTRACTION**

### **INSTALLING REQUIRED LIBRARIES**

In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.50)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2024.12.14)

### **INSTALLING FINRL LIBRARIES**

In [2]:
import yfinance as yf

In [3]:
!pip install alpaca-trade-api --upgrade

Requirement already satisfied: alpaca-trade-api in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (1.26.4)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (3.11.10)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (24.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api) (1.18.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>2->alpaca-trade-api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>2->alpaca-trade-api) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>2->alpaca-trade-api) (2024.12.14)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from multidict<7.0,>=4.5->aiohttp<4,>=3.8.3->alpaca-trade-api) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.18.1->alpaca-trade-api) (1.17.0)

In [8]:
import yfinance as yf
import pandas as pd
from tabulate import tabulate
import time

!pip install alpaca-py

!pip install swig
!pip install wrds
!pip install pyportfolioopt
## install finrl library
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git
## Hide matplotlib warnings
import warnings
warnings.filterwarnings('ignore')

import logging
logging.getLogger('matplotlib.font_manager').disabled = True

import torch

import numpy as np
from sklearn.preprocessing import MaxAbsScaler

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
#from finrl.meta.preprocessor.preprocessors import GroupByScaler
#from finrl.meta.env_portfolio_optimization.env_portfolio_optimization import PortfolioOptimizationEnv
#from finrl.agents.portfolio_optimization.models import DRLAgent
#from finrl.agents.portfolio_optimization.architectures import EIIE

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

Collecting alpaca-py
  Downloading alpaca_py-0.35.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-py) (1.0.3)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-py) (2.2.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-py) (2.10.3)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-py) (2.32.3)
Collecting sseclient-py<2.0.0,>=1.7.2 (from alpaca-py)
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.10/dist-packages (from alpaca-py) (10.4)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->alpaca-py) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->alpaca-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->alpaca-py) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->alpaca-py) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.30.0->alpaca-py) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.30.0->alpaca-py) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.30.0->alpaca-py) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.30.0->alpaca-py) (2024.12.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->alpaca-py) (1.17.0)
Downloading alpaca_py-0.35.1-py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.4/120.4 kB 2.9 MB/s eta 0:00:00
Downloading sseclient_py-1.8.0-py2.py3-none-any.whl (8.8 kB)
Installing collected packages: sseclient-py, alpaca-py
Successfully installed alpaca-py-0.35.1 sseclient-py-1.8.0
Requirement already satisfied: swig in /usr/local/lib/python3.10/dist-packages (4.3.0)
Requirement already satisfied: wrds in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: numpy<1.27,>=1.26 in /usr/local/lib/python3.10/dist-packages (from wrds) (1.26.4)
Requirement already satisfied: packaging<23.3 in /usr/local/lib/python3.10/dist-packages (from wrds) (23.2)
Requirement already satisfied: pandas<2.3,>=2.2 in /usr/local/lib/python3.10/dist-packages (from wrds) (2.2.2)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /usr/local/lib/python3.10/dist-packages (from wrds) (2.9.10)
Requirement already satisfied: scipy<1.13,>=1.12 in /usr/local/lib/python3.10/dist-packages (from wrds) (1.12.0)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /usr/local/lib/python3.10/dist-packages (from wrds) (2.0.36)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)
Requirement already satisfied: pyportfolioopt in /usr/local/lib/python3.10/dist-packages (1.5.6)
Requirement already satisfied: cvxpy>=1.1.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.6.0)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (2.0.14)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (2.2.2)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (5.24.1)
Requirement already satisfied: scipy>=1.3 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.12.0)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.1.19->pyportfolioopt) (3.2.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt) (23.2)
Requirement already satisfied: qdldl in /usr/local/lib/python3.10/dist-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (0.1.7.post4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.19->pyportfolioopt) (1.17.0)
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-fgvua9rz
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-fgvua9rz
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit bc12fe7b57c483e8fac666f4cf05cbf62077958a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-hs0crnxj/elegantrl_c4b42a409beb4a21a2273b7e5156e8d0
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-hs0crnxj/elegantrl_c4b42a409beb4a21a2273b7e5156e8d0
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 2fa34dd9236498beada8d8443d927970a9de1f7f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: alpaca-trade-api<4,>=3 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: ccxt<4,>=3 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (3.1.60)
Requirement already satisfied: exchange-calendars<5,>=4 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (4.8)
Requirement already satisfied: jqdatasdk<2,>=1 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (1.9.7)
Requirement already satisfied: pyfolio<0.10,>=0.9 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (0.9.2)
Requirement already satisfied: pyportfolioopt<2,>=1 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (1.5.6)
Requirement already satisfied: ray<3,>=2 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.40.0)
Requirement already satisfied: scikit-learn<2,>=1 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (1.6.0)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.5.0a1)
Requirement already satisfied: stockstats<0.6,>=0.5 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (0.5.4)
Requirement already satisfied: wrds<4,>=3 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (0.2.50)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.4)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.32.3)
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.8.0)
Requirement already satisfied: websockets<11,>=9.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (10.4)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.0.3)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (3.11.10)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.6) (23.2)
Requirement already satisfied: setuptools>=60.9.0 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (75.1.0)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (2024.12.14)
Requirement already satisfied: cryptography>=2.6.1 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (43.0.3)
Requirement already satisfied: aiodns>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (3.2.0)
Requirement already satisfied: yarl>=1.7.2 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (1.18.3)
Requirement already satisfied: pyluach in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2.2.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.12.1)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2024.2)
Requirement already satisfied: korean_lunar_calendar in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (2.0.36)
Requirement already satisfied: pymysql>=0.7.6 in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.1.1)
Requirement already satisfied: thriftpy2!=0.5.1,>=0.3.9 in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (0.5.2)
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (7.34.0)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (3.8.0)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (2024.2)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (1.12.0)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.13.2)
Requirement already satisfied: empyrical>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.5.5)
Requirement already satisfied: cvxpy>=1.1.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (1.6.0)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (2.0.14)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (5.24.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (8.1.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (3.16.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (4.23.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (4.25.5)
Requirement already satisfied: aiosignal in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (1.3.2)
Requirement already satisfied: frozenlist in /usr/local/lib/python3.10/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (1.5.0)
Requirement already satisfied: aiohttp-cors in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.7.0)
Requirement already satisfied: colorful in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.5.6)
Requirement already satisfied: py-spy>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.4.0)
Requirement already satisfied: opencensus in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.11.4)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.10.3)
Requirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.21.1)
Requirement already satisfied: smart-open in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (7.1.0)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (20.29.1)
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.68.1)
Requirement already satisfied: memray in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.15.0)
Requirement already satisfied: tensorboardX>=1.9 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.6.2.2)
Requirement already satisfied: pyarrow>=9.0.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (17.0.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2024.10.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (3.5.0)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (1.0.0)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.5.1+cu121)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (3.1.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.10.0.84)
Requirement already satisfied: pygame in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.17.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (5.9.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.67.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.10.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (11.0.0)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /usr/local/lib/python3.10/dist-packages (from wrds<4,>=3->finrl==0.3.6) (2.9.10)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (1.1)

**LIST OF TICKERS FROM CANADIAN STOCK MARKET**

In [9]:
FIRST_SET_TICKERS = [
    "AAB.TO", "AAUC.TO", "AAV.TO", "ABX.TO", "AC.TO", "ACAA.TO", "ACB.TO", "ACD.TO", "ACQ.TO", "ACX.TO", "ADCO.TO", "ADEN.TO", "ADIV.TO", "ADN.TO", "AEG.TO", "AEM.TO", "AFN.TO", "AG.TO", "AGG.TO", "AGI.TO", "AI.TO", "AIDX.TO", "AIF.TO", "AIGO.TO", "AII.TO", "AIM.TO", "ALA.TO", "ALC.TO", "ALS.TO", "ALYA.TO", "AMAX.TO", "AMC.TO", "AMHE.TO", "AMM.TO", "AMZH.TO", "AND.TO", "ANRG.TO", "AOI.TO", "AOT.TO", "APLI.TO", "APM.TO", "APS.TO", "AQN.TO", "ARA.TO", "ARB.TO", "ARE.TO", "ARG.TO", "ARIS.TO", "ARTI.TO", "ARX.TO", "ASCU.TO", "ASM.TO", "ASND.TO", "ASTL.TO", "ATCU.TO", "ATD.TO", "ATH.TO", "ATRL.TO", "ATS.TO", "ATSX.TO", "ATZ.TO", "AUMN.TO", "AVCN.TO", "AVL.TO", "AVNT.TO", "AW.TO", "AYA.TO", "BABY.TO", "BAM.TO", "BANK.TO", "BASE.TO", "BB.TO", "BBUC.TO", "BCE.TO", "BCHT.TO", "BCT.TO", "BDGI.TO", "BDI.TO", "BDIV.TO", "BDT.TO", "BEPC.TO", "BEPR.TO", "BESG.TO", "BFIN.TO", "BGC.TO", "BGU.TO", "BHC.TO", "BIPC.TO", "BIR.TO", "BITF.TO", "BITI.TO", "BK.TO", "BKCC.TO", "BKCL.TO", "BKI.TO", "BLCO.TO", "BLDP.TO", "BLN.TO", "BLOV.TO", "BLX.TO", "BMAX.TO", "BMO.TO", "BN.TO", "BNC.TO", "BND.TO", "BNE.TO", "BNG.TO", "BNK.TO", "BNKL.TO", "BNS.TO", "BNT.TO", "BOND.TO", "BOS.TO", "BPRF.TO", "BR.TO", "BRAG.TO", "BRE.TO", "BREA.TO", "BRMI.TO", "BRY.TO", "BSKT.TO", "BSX.TO", "BTCC.TO", "BTCQ.TO", "BTCY.TO", "BTE.TO", "BTO.TO", "BU.TO", "BUI.TO", "BXF.TO", "BYD.TO", "BYL.TO", "CACB.TO", "CAE.TO", "CAFR.TO", "CAGG.TO", "CAGS.TO", "CALL.TO", "CANL.TO", "CAPG.TO", "CAPI.TO", "CAPM.TO", "CAPW.TO", "CARB.TO", "CARS.TO", "CAS.TO", "CASH.TO", "CBAL.TO", "CBCX.TO", "CBGR.TO", "CBH.TO", "CBIL.TO", "CBIN.TO", "CBL.TO", "CBND.TO", "CBNK.TO", "CBO.TO", "CBUG.TO", "CCA.TO", "CCBI.TO", "CCEI.TO", "CCM.TO", "CCNS.TO", "CCNV.TO", "CCO.TO", "CCOM.TO", "CCRE.TO", "CDEF.TO", "CDIV.TO", "CDLB.TO", "CDNA.TO", "CDR.TO", "CDZ.TO", "CEF.TO", "CEMI.TO", "CEMX.TO", "CEQT.TO", "CEU.TO", "CEW.TO", "CF.TO", "CFF.TO", "CFLX.TO", "CFP.TO", "CFRT.TO", "CFW.TO", "CFX.TO", "CG.TO", "CGAA.TO", "CGBI.TO", "CGDV.TO", "CGG.TO", "CGHY.TO", "CGI.TO", "CGIN.TO", "CGL.TO", "CGLO.TO", "CGO.TO", "CGR.TO", "CGRA.TO", "CGRE.TO", "CGRN.TO", "CGRO.TO", "CGX.TO", "CGXF.TO", "CGY.TO", "CHPS.TO", "CHR.TO", "CIA.TO", "CIAI.TO", "CIBR.TO", "CIC.TO", "CIEH.TO", "CIEI.TO", "CIEM.TO", "CIF.TO", "CIGI.TO", "CINF.TO", "CINT.TO", "CINV.TO", "CIX.TO", "CJ.TO", "CJT.TO", "CKI.TO", "CLF.TO", "CLG.TO", "CLML.TO", "CLS.TO", "CM.TO", "CMAG.TO", "CMAR.TO", "CMDO.TO", "CMG.TO", "CMGG.TO", "CMNY.TO", "CMOM.TO", "CMR.TO", "CMVX.TO", "CNCC.TO", "CNCL.TO", "CNDX.TO", "CNE.TO", "CNL.TO", "CNQ.TO", "CNR.TO", "CNT.TO", "CNV.TO", "COG.TO", "COMM.TO", "COPP.TO", "COPR.TO", "CORE.TO", "COW.TO", "CP.TO", "CPD.TO", "CPH.TO", "CPLS.TO", "CPX.TO", "CRDL.TO", "CRED.TO", "CRON.TO", "CROP.TO", "CRP.TO", "CRRX.TO", "CRWN.TO", "CS.TO", "CSAV.TO", "CSBI.TO", "CSCI.TO", "CSU.TO", "CTC.TO", "CTS.TO", "CTX.TO", "CU.TO", "CUBD.TO", "CUD.TO", "CUDV.TO", "CUEH.TO", "CUEI.TO", "CURA.TO", "CUTL.TO", "CVD.TO", "CVE.TO", "CVG.TO", "CVLU.TO", "CVO.TO", "CWB.TO", "CWEB.TO", "CWL.TO", "CWW.TO", "CXB.TO", "CXF.TO", "CXI.TO", "CYB.TO", "CYBR.TO", "CYH.TO", "DAMG.TO", "DANC.TO", "DATA.TO", "DAY.TO", "DBM.TO", "DBO.TO", "DCBC.TO", "DCBO.TO", "DCC.TO", "DCG.TO", "DCM.TO", "DCP.TO", "DCS.TO", "DCU.TO", "DF.TO", "DFN.TO", "DFY.TO", "DGR.TO", "DGRC.TO", "DGS.TO", "DIAM.TO", "DISC.TO", "DIV.TO", "DIVS.TO", "DLCG.TO", "DLR.TO", "DMEC.TO", "DMEI.TO", "DMEU.TO", "DML.TO", "DND.TO", "DNG.TO", "DNTL.TO", "DOL.TO", "DOO.TO", "DPM.TO", "DR.TO", "DRCU.TO", "DRFC.TO", "DRFD.TO", "DRFE.TO", "DRFG.TO", "DRFU.TO", "DRM.TO", "DRMC.TO", "DRMD.TO", "DRME.TO", "DRMU.TO", "DRT.TO", "DRX.TO", "DS.TO", "DSAE.TO", "DSG.TO", "DSV.TO", "DTOL.TO", "DXAU.TO", "DXB.TO", "DXBB.TO", "DXBC.TO", "DXBG.TO", "DXBU.TO", "DXC.TO", "DXCB.TO", "DXCO.TO", "DXCP.TO", "DXDB.TO", "DXEM.TO", "DXET.TO", "DXF.TO", "DXG.TO", "DXGE.TO", "DXIF.TO", "DXMO.TO", "DXN.TO", "DXO.TO", "DXP.TO", "DXQ.TO", "DXR.TO", "DXT.TO", "DXU.TO", "DXUS.TO", "DXV.TO", "DXW.TO", "DXZ.TO", "DYA.TO", "E.TO", "EAGR.TO", "EARN.TO", "EBIT.TO", "EBNK.TO", "ECN.TO", "ECO.TO", "ECOR.TO", "EDGE.TO", "EDGF.TO", "EDR.TO", "EDT.TO", "EDV.TO", "EFN.TO", "EFR.TO", "EFX.TO", "EGLX.TO", "EIF.TO", "ELD.TO", "ELEF.TO", "ELF.TO", "ELO.TO", "ELR.TO", "ELVA.TO", "EMA.TO", "EMAX.TO", "ENB.TO", "ENCC.TO", "ENCL.TO", "ENGH.TO", "ENS.TO", "EPRX.TO", "EQB.TO", "EQCC.TO", "EQCL.TO", "EQL.TO", "EQLI.TO", "EQX.TO", "ERD.TO", "ERO.TO", "ESG.TO", "ESGA.TO", "ESGB.TO", "ESGC.TO", "ESGE.TO", "ESGF.TO", "ESGG.TO", "ESGH.TO", "ESGY.TO", "ESI.TO", "ESM.TO", "ESP.TO", "ESPX.TO", "ET.TO", "ETC.TO", "ETG.TO", "ETHH.TO", "ETHI.TO", "ETHQ.TO", "ETHR.TO", "ETHY.TO", "ETP.TO", "ETSX.TO", "EVO.TO", "EVT.TO", "EXE.TO", "EXN.TO", "EXRO.TO", "FAP.TO", "FAR.TO", "FBGO.TO", "FBT.TO", "FBTC.TO", "FC.TO", "FCCD.TO", "FCCQ.TO", "FCCV.TO", "FCEM.TO", "FCGI.TO", "FCID.TO", "FCII.TO", "FCIQ.TO", "FCIV.TO", "FCMI.TO", "FCQH.TO", "FCRR.TO", "FCUD.TO", "FCUH.TO", "FCUQ.TO", "FCUV.TO", "FCVH.TO", "FDL.TO", "FDN.TO", "FDY.TO", "FEC.TO", "FETH.TO", "FF.TO", "FFH.TO", "FFM.TO", "FFN.TO", "FGB.TO", "FGEB.TO", "FGEP.TO", "FGGE.TO", "FGO.TO", "FGOV.TO", "FGRW.TO", "FHG.TO", "FHH.TO", "FHI.TO", "FHIS.TO", "FHQ.TO", "FIE.TO", "FIG.TO", "FIL.TO", "FINC.TO", "FINE.TO", "FINO.TO", "FLCI.TO", "FLCP.TO", "FLGA.TO", "FLI.TO", "FLNT.TO", "FLOW.TO", "FLSD.TO", "FLUS.TO", "FLX.TO", "FM.TO", "FMAX.TO", "FN.TO", "FNV.TO", "FOM.TO", "FOOD.TO", "FORA.TO", "FOUR.TO", "FPR.TO", "FRU.TO", "FRX.TO", "FSB.TO", "FSF.TO", "FSL.TO", "FST.TO", "FSV.TO", "FSY.TO", "FSZ.TO", "FT.TO", "FTG.TO", "FTHI.TO", "FTN.TO", "FTS.TO", "FTT.TO", "FTU.TO", "FURY.TO", "FVI.TO", "FVL.TO", "FXM.TO", "G.TO", "GATO.TO", "GAU.TO", "GBAL.TO", "GBT.TO", "GCBD.TO", "GCFE.TO", "GCG.TO", "GCL.TO", "GCNS.TO", "GCSC.TO", "GCTB.TO", "GCU.TO", "GDC.TO", "GDEP.TO", "GDI.TO", "GDL.TO", "GDPY.TO", "GDV.TO", "GEC.TO", "GEI.TO", "GENM.TO", "GEO.TO", "GEQT.TO", "GFL.TO", "GFP.TO", "GFR.TO", "GGD.TO", "GGRO.TO", "GH.TO", "GIGC.TO", "GIL.TO", "GIQG.TO", "GIQU.TO", "GLCC.TO", "GLDX.TO", "GLO.TO", "GLXY.TO", "GMIN.TO", "GMTN.TO", "GMX.TO", "GOLD.TO", "GOOS.TO", "GPMD.TO", "GRA.TO", "GRC.TO", "GRCC.TO", "GRGD.TO", "GRID.TO", "GRN.TO", "GRNI.TO", "GRO.TO", "GSY.TO", "GTE.TO", "GTWO.TO", "GUD.TO", "GURU.TO", "GVC.TO", "GWO.TO", "GXE.TO", "H.TO", "HAB.TO", "HAC.TO", "HAD.TO", "HAF.TO", "HAI.TO", "HAL.TO", "HAZ.TO", "HBA.TO", "HBAL.TO", "HBB.TO", "HBD.TO", "HBF.TO", "HBGD.TO", "HBIE.TO", "HBIG.TO", "HBIL.TO", "HBKD.TO", "HBKU.TO", "HBLK.TO", "HBM.TO", "HBND.TO", "HBNK.TO", "HBP.TO", "HBU.TO", "HBUG.TO", "HCA.TO", "HCAL.TO", "HCLN.TO", "HCON.TO", "HCRE.TO", "HDGE.TO", "HDIF.TO", "HDIV.TO", "HEB.TO", "HED.TO", "HEQL.TO", "HEQT.TO", "HERO.TO", "HEU.TO", "HEWB.TO", "HFD.TO", "HFG.TO", "HFIN.TO", "HFR.TO", "HFU.TO", "HGD.TO", "HGGG.TO", "HGR.TO", "HGRW.TO", "HGU.TO", "HGY.TO", "HHL.TO", "HHLE.TO", "HIG.TO", "HIND.TO", "HIU.TO", "HIX.TO", "HLF.TO", "HLIF.TO", "HLIT.TO", "HLPR.TO", "HLS.TO", "HMAX.TO", "HMMJ.TO", "HMP.TO", "HND.TO", "HNU.TO", "HOD.TO", "HOU.TO", "HPF.TO", "HPR.TO", "HPYM.TO", "HPYT.TO", "HQD.TO", "HQU.TO", "HRAA.TO", "HRED.TO", "HREU.TO", "HRIF.TO", "HRX.TO", "HSAV.TO", "HSD.TO", "HSH.TO", "HSU.TO", "HTA.TO","HTAE.TO", "HTB.TO", "HUBL.TO", "HUC.TO", "HUG.TO", "HULC.TO", "HUM.TO", "HUN.TO", "HURA.TO", "HUT.TO", "HUTE.TO", "HUTL.TO", "HUTS.TO", "HUV.TO", "HUZ.TO", "HWO.TO", "HWX.TO", "HXCN.TO", "HXD.TO", "HXDM.TO", "HXE.TO", "HXEM.TO", "HXF.TO", "HXH.TO", "HXQ.TO", "HXS.TO", "HXT.TO", "HXU.TO", "HXX.TO", "HYBR.TO", "HYLD.TO", "HZD.TO", "HZU.TO", "IAG.TO", "IAU.TO", "ICAE.TO", "ICE.TO", "ICPB.TO", "ICTE.TO", "IE.TO", "IFA.TO", "IFC.TO", "IFP.TO", "IFRF.TO", "IGAF.TO", "IGB.TO", "IGEO.TO", "IGET.TO", "IGM.TO", "IIAE.TO", "IICE.TO", "III.TO", "IIMF.TO", "IITE.TO", "ILGB.TO", "ILLM.TO", "IMG.TO", "IMO.TO", "IMP.TO", "INAI.TO", "INCM.TO", "INE.TO", "INOC.TO", "IPCO.TO", "IPO.TO", "IQD.TO", "IS.TO", "ISC.TO", "ISCB.TO", "ISO.TO", "ISTE.TO", "ITH.TO", "IUAE.TO", "IUCE.TO", "IUMF.TO", "IUTE.TO", "IVN.TO", "IVQ.TO", "IWBE.TO", "IXTE.TO", "JAG.TO", "JAPN.TO", "JEPI.TO", "JEPQ.TO", "JOY.TO", "JWEL.TO", "K.TO", "KBL.TO", "KEC.TO", "KEI.TO", "KEL.TO", "KEY.TO", "KILO.TO", "KITS.TO", "KLS.TO", "KNGC.TO", "KNGU.TO", "KNGX.TO", "KNT.TO", "KPT.TO", "KRN.TO", "KSI.TO", "KXS.TO", "L.TO", "LAAC.TO", "LABS.TO", "LAC.TO", "LAM.TO", "LB.TO", "LBS.TO", "LCFS.TO", "LCS.TO", "LEAD.TO", "LFE.TO", "LGD.TO", "LGO.TO", "LIF.TO", "LIFE.TO", "LIRC.TO", "LLHE.TO", "LLYH.TO", "LMAX.TO", "LN.TO", "LNF.TO", "LNR.TO", "LPAY.TO", "LSPD.TO", "LSPK.TO", "LUC.TO", "LUG.TO", "LUN.TO", "LYCT.TO", "LYFR.TO", "MAG.TO", "MAL.TO", "MARI.TO", "MART.TO", "MATR.TO", "MBAL.TO", "MBX.TO", "MCAD.TO", "MCB.TO", "MCLC.TO", "MCLV.TO", "MCON.TO", "MCSB.TO", "MCSM.TO", "MDA.TO", "MDI.TO", "MDIV.TO", "MDNA.TO", "MDP.TO", "MDVD.TO", "MEG.TO", "MEQ.TO", "MEQT.TO", "MFC.TO", "MFI.TO", "MFT.TO", "MG.TO", "MGA.TO", "MGAB.TO", "MGB.TO", "MGDV.TO", "MGQE.TO", "MGRW.TO", "MHCD.TO", "MINF.TO", "MINN.TO", "MINT.TO", "MIQE.TO", "MIVG.TO", "MKB.TO", "MKP.TO", "MND.TO", "MNO.TO", "MNS.TO", "MNT.TO", "MNXT.TO", "MNY.TO", "MOGO.TO", "MORE.TO", "MPAY.TO", "MPC.TO", "MPVD.TO", "MPY.TO", "MRC.TO", "MRD.TO", "MRE.TO", "MREL.TO", "MRU.TO", "MSA.TO", "MSCL.TO", "MSFH.TO", "MSHE.TO", "MSV.TO"
]
print(len(FIRST_SET_TICKERS))

878

In [10]:
import time
import pandas as pd

# Function to fetch data with rate limiting
def fetch_data_with_rate_limiting(start_date, end_date, ticker_list, requests_per_minute=100):
    data = []
    delay = 60 / requests_per_minute  # Calculate delay to respect the limit

    for i, ticker in enumerate(ticker_list):
        try:
            print(f"Fetching data for: {ticker}")
            downloader = YahooDownloader(start_date=start_date, end_date=end_date, ticker_list=[ticker])
            ticker_data = downloader.fetch_data()
            data.append(ticker_data)
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")

        if i < len(ticker_list) - 1:  # Avoid sleeping after the last request
            time.sleep(delay)

    return pd.concat(data, ignore_index=True)

# Fetch data with rate limiting
portfolio_raw_df = fetch_data_with_rate_limiting(
    start_date='2004-01-01',
    end_date='2024-12-30',
    ticker_list=FIRST_SET_TICKERS,  # Replace with your list of tickers
    requests_per_minute=100  # Limit to 100 requests per minute
)

portfolio_raw_df

Fetching data for: AAB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: AAUC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (325, 8)
Fetching data for: AAV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: ABX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AC.TO

Shape of DataFrame:  (3699, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ACAA.TO
Shape of DataFrame:  (120, 8)

Fetching data for: ACB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2065, 8)
Fetching data for: ACD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ACQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: ACX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ADCO.TO
Shape of DataFrame:  (1402, 8)

Fetching data for: ADEN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ADIV.TO
Shape of DataFrame:  (183, 8)

Fetching data for: ADN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: AEG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4811, 8)
Fetching data for: AEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: AFN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5175, 8)
Fetching data for: AG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AGG.TO
Shape of DataFrame:  (50, 8)

Fetching data for: AGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: AI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3088, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AIDX.TO
Shape of DataFrame:  (999, 8)

Fetching data for: AIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AIGO.TO
Shape of DataFrame:  (155, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AII.TO

Shape of DataFrame:  (3605, 8)
Fetching data for: AIM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4898, 8)
Fetching data for: ALA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5176, 8)
Fetching data for: ALC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ALS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ALYA.TO
Shape of DataFrame:  (1543, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AMAX.TO

Shape of DataFrame:  (224, 8)
Fetching data for: AMC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1695, 8)
Fetching data for: AMHE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (88, 8)
Fetching data for: AMM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AMZH.TO

Shape of DataFrame:  (89, 8)
Fetching data for: AND.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1266, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ANRG.TO

Shape of DataFrame:  (885, 8)
Fetching data for: AOI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: AOT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: APLI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1383, 8)
Fetching data for: APM.TO

[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['APM.TO']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2004-01-01 -> 2024-12-30) (Yahoo error = "Data doesn\'t exist for startDate = 1072933200, endDate = 1735534800")')

Error fetching data for APM.TO: no data is fetched.
Fetching data for: APS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: AQN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ARA.TO

Shape of DataFrame:  (764, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ARB.TO
Shape of DataFrame:  (252, 8)

Fetching data for: ARE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ARG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ARIS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3243, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ARTI.TO

Shape of DataFrame:  (773, 8)
Fetching data for: ARX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ASCU.TO

Shape of DataFrame:  (782, 8)
Fetching data for: ASM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ASND.TO

Shape of DataFrame:  (3199, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ASTL.TO

Shape of DataFrame:  (801, 8)
Fetching data for: ATCU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ATD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ATH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ATRL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ATS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)
Fetching data for: ATSX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1414, 8)
Fetching data for: ATZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2067, 8)
Fetching data for: AUMN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AVCN.TO

Shape of DataFrame:  (1367, 8)
Fetching data for: AVL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AVNT.TO

Shape of DataFrame:  (1635, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: AW.TO
Shape of DataFrame:  (49, 8)

Fetching data for: AYA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: BABY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3177, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BAM.TO

Shape of DataFrame:  (520, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BANK.TO

Shape of DataFrame:  (729, 8)
Fetching data for: BASE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1391, 8)
Fetching data for: BB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BBUC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (707, 8)
Fetching data for: BCE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BCHT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (46, 8)
Fetching data for: BCT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3105, 8)
Fetching data for: BDGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BDI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: BDIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: BDT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BEPC.TO
Shape of DataFrame:  (1111, 8)

Fetching data for: BEPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: BESG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3095, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BFIN.TO

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BGC.TO

Shape of DataFrame:  (1712, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BGU.TO
Shape of DataFrame:  (1712, 8)

Fetching data for: BHC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BIPC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1191, 8)
Fetching data for: BIR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BITF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1369, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BITI.TO
Shape of DataFrame:  (930, 8)

Fetching data for: BK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4881, 8)
Fetching data for: BKCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BKCL.TO
Shape of DataFrame:  (364, 8)

Fetching data for: BKI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3451, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BLCO.TO
Shape of DataFrame:  (664, 8)

Fetching data for: BLDP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3259, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BLOV.TO

Shape of DataFrame:  (1167, 8)
Fetching data for: BLX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BMAX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (550, 8)
Fetching data for: BMO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BNC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2031, 8)
Fetching data for: BND.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2300, 8)
Fetching data for: BNE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BNG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BNK.TO
Shape of DataFrame:  (1130, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BNKL.TO
Shape of DataFrame:  (366, 8)

Fetching data for: BNS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BNT.TO
Shape of DataFrame:  (879, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BOND.TO
Shape of DataFrame:  (310, 8)

Fetching data for: BOS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BPRF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: BR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BRAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1623, 8)
Fetching data for: BRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: BREA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1167, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BRMI.TO
Shape of DataFrame:  (945, 8)

Fetching data for: BRY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BSKT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1025, 8)
Fetching data for: BSX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BTCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (964, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BTCQ.TO

Shape of DataFrame:  (928, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BTCY.TO

Shape of DataFrame:  (769, 8)
Fetching data for: BTE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BTO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4234, 8)
Fetching data for: BU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BUI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: BXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2887, 8)
Fetching data for: BYD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: BYL.TO

Shape of DataFrame:  (2781, 8)
Fetching data for: CACB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: CAE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CAFR.TO

Shape of DataFrame:  (1494, 8)
Fetching data for: CAGG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1882, 8)
Fetching data for: CAGS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1850, 8)
Fetching data for: CALL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CANL.TO

Shape of DataFrame:  (368, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CAPG.TO

Shape of DataFrame:  (45, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CAPI.TO
Shape of DataFrame:  (45, 8)

Fetching data for: CAPM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (45, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CAPW.TO
Shape of DataFrame:  (45, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CARB.TO

Shape of DataFrame:  (723, 8)
Fetching data for: CARS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: CAS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CASH.TO
Shape of DataFrame:  (791, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBAL.TO
Shape of DataFrame:  (403, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBCX.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBGR.TO

Shape of DataFrame:  (398, 8)
Fetching data for: CBH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBIL.TO
Shape of DataFrame:  (429, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBIN.TO
Shape of DataFrame:  (406, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBL.TO
Shape of DataFrame:  (139, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBND.TO
Shape of DataFrame:  (1026, 8)

Fetching data for: CBNK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (710, 8)
Fetching data for: CBO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3779, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CBUG.TO

Shape of DataFrame:  (711, 8)
Fetching data for: CCA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CCBI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (945, 8)
Fetching data for: CCEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (945, 8)
Fetching data for: CCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CCNS.TO
Shape of DataFrame:  (1046, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CCNV.TO
Shape of DataFrame:  (406, 8)

Fetching data for: CCO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CCOM.TO

Shape of DataFrame:  (566, 8)
Fetching data for: CCRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1044, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CDEF.TO
Shape of DataFrame:  (788, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CDIV.TO
Shape of DataFrame:  (1026, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CDLB.TO
Shape of DataFrame:  (1164, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CDNA.TO

Shape of DataFrame:  (711, 8)
Fetching data for: CDR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: CDZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4594, 8)
Fetching data for: CEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1743, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CEMI.TO

Shape of DataFrame:  (822, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CEMX.TO

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CEQT.TO
Shape of DataFrame:  (406, 8)

Fetching data for: CEU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4725, 8)
Fetching data for: CEW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4234, 8)
Fetching data for: CF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4719, 8)
Fetching data for: CFF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3651, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CFLX.TO

Shape of DataFrame:  (1234, 8)
Fetching data for: CFP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CFRT.TO
Shape of DataFrame:  (677, 8)

Fetching data for: CFW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CFX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4454, 8)
Fetching data for: CG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5145, 8)
Fetching data for: CGAA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CGBI.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CGDV.TO
Shape of DataFrame:  (484, 8)

Fetching data for: CGG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CGHY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2485, 8)
Fetching data for: CGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CGIN.TO

Shape of DataFrame:  (252, 8)
Fetching data for: CGL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3572, 8)
Fetching data for: CGLO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1108, 8)
Fetching data for: CGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)
Fetching data for: CGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3994, 8)
Fetching data for: CGRA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1156, 8)
Fetching data for: CGRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1156, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CGRN.TO

Shape of DataFrame:  (569, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CGRO.TO
Shape of DataFrame:  (406, 8)

Fetching data for: CGX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3574, 8)
Fetching data for: CGXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3405, 8)
Fetching data for: CGY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CHPS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (883, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CHR.TO
Shape of DataFrame:  (2156, 8)

Fetching data for: CIA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2633, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CIAI.TO
Shape of DataFrame:  (162, 8)

Fetching data for: CIBR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2527, 8)
Fetching data for: CIC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3260, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CIEH.TO

Shape of DataFrame:  (252, 8)
Fetching data for: CIEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (939, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CIEM.TO
Shape of DataFrame:  (829, 8)

Fetching data for: CIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3994, 8)
Fetching data for: CIGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CINF.TO

Shape of DataFrame:  (1147, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CINT.TO
Shape of DataFrame:  (1108, 8)

Fetching data for: CINV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (845, 8)
Fetching data for: CIX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CJ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2755, 8)
Fetching data for: CJT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: CKI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CLF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4234, 8)
Fetching data for: CLG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: CLML.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (869, 8)
Fetching data for: CLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMAG.TO

Shape of DataFrame:  (1234, 8)
Fetching data for: CMAR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1235, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMDO.TO

Shape of DataFrame:  (845, 8)
Fetching data for: CMG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMGG.TO
Shape of DataFrame:  (995, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMNY.TO

Shape of DataFrame:  (350, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMOM.TO
Shape of DataFrame:  (240, 8)

Fetching data for: CMR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4231, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CMVX.TO
Shape of DataFrame:  (670, 8)

Fetching data for: CNCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3444, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CNCL.TO

Shape of DataFrame:  (371, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CNDX.TO
Shape of DataFrame:  (155, 8)

Fetching data for: CNE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CNL.TO

Shape of DataFrame:  (1497, 8)
Fetching data for: CNQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CNR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CNT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CNV.TO
Shape of DataFrame:  (139, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: COG.TO

Shape of DataFrame:  (1743, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: COMM.TO

Shape of DataFrame:  (1667, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: COPP.TO
Shape of DataFrame:  (657, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: COPR.TO
Shape of DataFrame:  (95, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CORE.TO
Shape of DataFrame:  (91, 8)

Fetching data for: COW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4271, 8)
Fetching data for: CP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CPD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: CPH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5181, 8)
Fetching data for: CPLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1041, 8)
Fetching data for: CPX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3861, 8)
Fetching data for: CRDL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1510, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CRED.TO

Shape of DataFrame:  (1235, 8)
Fetching data for: CRON.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2514, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CROP.TO

Shape of DataFrame:  (815, 8)
Fetching data for: CRP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4222, 8)
Fetching data for: CRRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4234, 8)
Fetching data for: CRWN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2377, 8)
Fetching data for: CS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CSAV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1388, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CSBI.TO

Shape of DataFrame:  (205, 8)
Fetching data for: CSCI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CSU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: CTC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CTS.TO

Shape of DataFrame:  (1537, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CTX.TO

Shape of DataFrame:  (1624, 8)
Fetching data for: CU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CUBD.TO
Shape of DataFrame:  (43, 8)

Fetching data for: CUD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3326, 8)
Fetching data for: CUDV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (488, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CUEH.TO

Shape of DataFrame:  (252, 8)
Fetching data for: CUEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (945, 8)
Fetching data for: CURA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (936, 8)
Fetching data for: CUTL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (29, 8)
Fetching data for: CVD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3398, 8)
Fetching data for: CVE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3803, 8)
Fetching data for: CVG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CVLU.TO
Shape of DataFrame:  (240, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: CVO.TO

Shape of DataFrame:  (780, 8)
Fetching data for: CWB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CWEB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1579, 8)
Fetching data for: CWL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: CWW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: CXB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)
Fetching data for: CXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: CXI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3081, 8)
Fetching data for: CYB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3994, 8)
Fetching data for: CYBR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: CYH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4253, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DAMG.TO
Shape of DataFrame:  (554, 8)

Fetching data for: DANC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1487, 8)
Fetching data for: DATA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (996, 8)
Fetching data for: DAY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1674, 8)
Fetching data for: DBM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4121, 8)
Fetching data for: DBO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3993, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DCBC.TO
Shape of DataFrame:  (173, 8)

Fetching data for: DCBO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1311, 8)
Fetching data for: DCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1937, 8)
Fetching data for: DCG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1941, 8)
Fetching data for: DCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4775, 8)
Fetching data for: DCP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1942, 8)
Fetching data for: DCS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1931, 8)
Fetching data for: DCU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1939, 8)
Fetching data for: DF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4544, 8)
Fetching data for: DFN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5219, 8)
Fetching data for: DFY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (780, 8)
Fetching data for: DGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2120, 8)
Fetching data for: DGRC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1732, 8)
Fetching data for: DGS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4283, 8)
Fetching data for: DIAM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: DISC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1936, 8)
Fetching data for: DIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: DIVS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: DLCG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2160, 8)
Fetching data for: DLR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3444, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DMEC.TO

Shape of DataFrame:  (173, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DMEI.TO
Shape of DataFrame:  (174, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DMEU.TO
Shape of DataFrame:  (173, 8)

Fetching data for: DML.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: DND.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1116, 8)
Fetching data for: DNG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DNTL.TO

Shape of DataFrame:  (904, 8)
Fetching data for: DOL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3818, 8)
Fetching data for: DOO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2912, 8)
Fetching data for: DPM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: DR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4539, 8)
Fetching data for: DRCU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1569, 8)
Fetching data for: DRFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1572, 8)
Fetching data for: DRFD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1572, 8)
Fetching data for: DRFE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1459, 8)
Fetching data for: DRFG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1460, 8)
Fetching data for: DRFU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1572, 8)
Fetching data for: DRM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2909, 8)
Fetching data for: DRMC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1569, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DRMD.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DRME.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DRMU.TO
Shape of DataFrame:  (1572, 8)

Fetching data for: DRT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2779, 8)
Fetching data for: DRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: DS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3539, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DSAE.TO

Shape of DataFrame:  (733, 8)
Fetching data for: DSG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DSV.TO

Shape of DataFrame:  (2554, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DTOL.TO

Shape of DataFrame:  (791, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXAU.TO

Shape of DataFrame:  (48, 8)
Fetching data for: DXB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1819, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXBB.TO
Shape of DataFrame:  (40, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXBC.TO
Shape of DataFrame:  (297, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXBG.TO
Shape of DataFrame:  (29, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXBU.TO
Shape of DataFrame:  (294, 8)

Fetching data for: DXC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1953, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXCB.TO
Shape of DataFrame:  (40, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXCO.TO
Shape of DataFrame:  (28, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXCP.TO
Shape of DataFrame:  (7, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXDB.TO
Shape of DataFrame:  (537, 8)

Fetching data for: DXEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (888, 8)
Fetching data for: DXET.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (881, 8)
Fetching data for: DXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1732, 8)
Fetching data for: DXG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1989, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXGE.TO
Shape of DataFrame:  (288, 8)

Fetching data for: DXIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (940, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXMO.TO
Shape of DataFrame:  (67, 8)

Fetching data for: DXN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1217, 8)
Fetching data for: DXO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: DXP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1816, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXQ.TO

Shape of DataFrame:  (571, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXR.TO
Shape of DataFrame:  (252, 8)

Fetching data for: DXT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4624, 8)
Fetching data for: DXU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1816, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: DXUS.TO
Shape of DataFrame:  (251, 8)

Fetching data for: DXV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1691, 8)
Fetching data for: DXW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1217, 8)
Fetching data for: DXZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1725, 8)
Fetching data for: DYA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5280, 8)
Fetching data for: E.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4848, 8)
Fetching data for: EAGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1365, 8)
Fetching data for: EARN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1535, 8)
Fetching data for: EBIT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (968, 8)
Fetching data for: EBNK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (744, 8)
Fetching data for: ECN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2070, 8)
Fetching data for: ECO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3361, 8)
Fetching data for: ECOR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3605, 8)
Fetching data for: EDGE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1669, 8)
Fetching data for: EDGF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1866, 8)
Fetching data for: EDR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EDT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5280, 8)
Fetching data for: EDV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EFN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3269, 8)
Fetching data for: EFR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EFX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3405, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EGLX.TO
Shape of DataFrame:  (1253, 8)

Fetching data for: EIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5181, 8)
Fetching data for: ELD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ELEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4664, 8)
Fetching data for: ELF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ELO.TO

Shape of DataFrame:  (4310, 8)
Fetching data for: ELR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ELVA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EMA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EMAX.TO
Shape of DataFrame:  (224, 8)

Fetching data for: ENB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ENCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3432, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ENCL.TO
Shape of DataFrame:  (306, 8)

Fetching data for: ENGH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ENS.TO

Shape of DataFrame:  (1630, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EPRX.TO
Shape of DataFrame:  (956, 8)

Fetching data for: EQB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EQCC.TO
Shape of DataFrame:  (144, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EQCL.TO
Shape of DataFrame:  (294, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EQL.TO

Shape of DataFrame:  (1634, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EQLI.TO

Shape of DataFrame:  (89, 8)
Fetching data for: EQX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2633, 8)
Fetching data for: ERD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: ERO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1805, 8)
Fetching data for: ESG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1209, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGA.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGB.TO
Shape of DataFrame:  (252, 8)

Fetching data for: ESGC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1059, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGE.TO
Shape of DataFrame:  (1235, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGF.TO

Shape of DataFrame:  (1239, 8)
Fetching data for: ESGG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1239, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGH.TO
Shape of DataFrame:  (973, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESGY.TO

Shape of DataFrame:  (1239, 8)
Fetching data for: ESI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESM.TO
Shape of DataFrame:  (2075, 8)

Fetching data for: ESP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2470, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ESPX.TO

Shape of DataFrame:  (495, 8)
Fetching data for: ET.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4641, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ETC.TO

Shape of DataFrame:  (815, 8)
Fetching data for: ETG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ETHH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (927, 8)
Fetching data for: ETHI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: ETHQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (924, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ETHR.TO

Shape of DataFrame:  (927, 8)
Fetching data for: ETHY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (770, 8)
Fetching data for: ETP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2613, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ETSX.TO
Shape of DataFrame:  (494, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: EVO.TO
Shape of DataFrame:  (189, 8)

Fetching data for: EVT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EXE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3077, 8)
Fetching data for: EXN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: EXRO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1071, 8)
Fetching data for: FAP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FAR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4367, 8)
Fetching data for: FBGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (878, 8)
Fetching data for: FBT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2550, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FBTC.TO

Shape of DataFrame:  (770, 8)
Fetching data for: FC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCCD.TO

Shape of DataFrame:  (1576, 8)
Fetching data for: FCCQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: FCCV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1139, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCEM.TO
Shape of DataFrame:  (94, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCGI.TO

Shape of DataFrame:  (1243, 8)
Fetching data for: FCID.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1576, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCII.TO

Shape of DataFrame:  (877, 8)
Fetching data for: FCIQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1484, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCIV.TO
Shape of DataFrame:  (1142, 8)

Fetching data for: FCMI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1243, 8)
Fetching data for: FCQH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1488, 8)
Fetching data for: FCRR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1576, 8)
Fetching data for: FCUD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1576, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCUH.TO

Shape of DataFrame:  (1576, 8)
Fetching data for: FCUQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1488, 8)
Fetching data for: FCUV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1142, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FCVH.TO
Shape of DataFrame:  (1145, 8)

Fetching data for: FDL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2061, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FDN.TO

Shape of DataFrame:  (2550, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FDY.TO

Shape of DataFrame:  (3608, 8)
Fetching data for: FEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2045, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FETH.TO

Shape of DataFrame:  (567, 8)
Fetching data for: FF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2432, 8)
Fetching data for: FFH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FFM.TO
Shape of DataFrame:  (7, 8)

Fetching data for: FFN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5069, 8)
Fetching data for: FGB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2211, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FGEB.TO
Shape of DataFrame:  (152, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FGEP.TO
Shape of DataFrame:  (152, 8)

Fetching data for: FGGE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1061, 8)
Fetching data for: FGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FGOV.TO
Shape of DataFrame:  (71, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FGRW.TO
Shape of DataFrame:  (348, 8)

Fetching data for: FHG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2406, 8)
Fetching data for: FHH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2550, 8)
Fetching data for: FHI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1640, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FHIS.TO

Shape of DataFrame:  (577, 8)
Fetching data for: FHQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2540, 8)
Fetching data for: FIE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3545, 8)
Fetching data for: FIG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2096, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FIL.TO

Shape of DataFrame:  (2087, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FINC.TO
Shape of DataFrame:  (348, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FINE.TO
Shape of DataFrame:  (348, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FINO.TO
Shape of DataFrame:  (978, 8)

Fetching data for: FLCI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1749, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FLCP.TO
Shape of DataFrame:  (251, 8)

Fetching data for: FLGA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: FLI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2845, 8)
Fetching data for: FLNT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4868, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FLOW.TO

Shape of DataFrame:  (868, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FLSD.TO

Shape of DataFrame:  (252, 8)
Fetching data for: FLUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1882, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FLX.TO
Shape of DataFrame:  (252, 8)

Fetching data for: FM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FMAX.TO
Shape of DataFrame:  (224, 8)

Fetching data for: FN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: FNV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4283, 8)
Fetching data for: FOM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FOOD.TO

Shape of DataFrame:  (1895, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FORA.TO
Shape of DataFrame:  (888, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FOUR.TO
Shape of DataFrame:  (1542, 8)

Fetching data for: FPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2141, 8)
Fetching data for: FRU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: FSF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2103, 8)
Fetching data for: FSL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2844, 8)
Fetching data for: FST.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2019, 8)
Fetching data for: FSV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2407, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FSY.TO

Shape of DataFrame:  (5271, 8)
Fetching data for: FSZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: FT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FTG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FTHI.TO
Shape of DataFrame:  (150, 8)

Fetching data for: FTN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FTS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FTT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FTU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FURY.TO
Shape of DataFrame:  (1624, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: FVI.TO

Shape of DataFrame:  (5271, 8)
Fetching data for: FVL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: FXM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3229, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: G.TO
Shape of DataFrame:  (942, 8)

Fetching data for: GATO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1046, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GAU.TO

Shape of DataFrame:  (3994, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GBAL.TO

Shape of DataFrame:  (1078, 8)
Fetching data for: GBT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GCBD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (940, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GCFE.TO
Shape of DataFrame:  (282, 8)

Fetching data for: GCG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GCL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3912, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GCNS.TO
Shape of DataFrame:  (1072, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GCSC.TO
Shape of DataFrame:  (941, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GCTB.TO
Shape of DataFrame:  (369, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GCU.TO

Shape of DataFrame:  (1967, 8)
Fetching data for: GDC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GDEP.TO
Shape of DataFrame:  (1096, 8)

Fetching data for: GDI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1624, 8)
Fetching data for: GDL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GDPY.TO

Shape of DataFrame:  (1097, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GDV.TO

Shape of DataFrame:  (1640, 8)
Fetching data for: GEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: GENM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1666, 8)
Fetching data for: GEO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3517, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GEQT.TO

Shape of DataFrame:  (1079, 8)
Fetching data for: GFL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1211, 8)
Fetching data for: GFP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5268, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GFR.TO
Shape of DataFrame:  (220, 8)

Fetching data for: GGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3683, 8)
Fetching data for: GGRO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1077, 8)
Fetching data for: GH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GIGC.TO
Shape of DataFrame:  (167, 8)

Fetching data for: GIL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GIQG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1091, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GIQU.TO
Shape of DataFrame:  (251, 8)

Fetching data for: GLCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3434, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GLDX.TO
Shape of DataFrame:  (34, 8)

Fetching data for: GLO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GLXY.TO

Shape of DataFrame:  (1112, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GMIN.TO
Shape of DataFrame:  (184, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GMTN.TO
Shape of DataFrame:  (777, 8)

Fetching data for: GMX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GOLD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1624, 8)
Fetching data for: GOOS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1954, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GPMD.TO

Shape of DataFrame:  (580, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRA.TO
Shape of DataFrame:  (1755, 8)

Fetching data for: GRC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRCC.TO

Shape of DataFrame:  (101, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRGD.TO
Shape of DataFrame:  (25, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRID.TO
Shape of DataFrame:  (975, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRN.TO
Shape of DataFrame:  (1394, 8)

Fetching data for: GRNI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (708, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GRO.TO
Shape of DataFrame:

(139, 8)
Fetching data for: GSY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GTE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4231, 8)
Fetching data for: GTWO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3539, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: GUD.TO

Shape of DataFrame:  (2717, 8)
Fetching data for: GURU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1043, 8)
Fetching data for: GVC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GWO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: GXE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2788, 8)
Fetching data for: H.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2287, 8)
Fetching data for: HAB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3605, 8)
Fetching data for: HAC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: HAD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3063, 8)
Fetching data for: HAF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: HAI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1011, 8)
Fetching data for: HAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3683, 8)
Fetching data for: HAZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3605, 8)
Fetching data for: HBA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1129, 8)
Fetching data for: HBAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1607, 8)
Fetching data for: HBB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2670, 8)
Fetching data for: HBD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4249, 8)
Fetching data for: HBF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2617, 8)
Fetching data for: HBGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1635, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBIE.TO
Shape of DataFrame:  (177, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBIG.TO
Shape of DataFrame:  (173, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBIL.TO
Shape of DataFrame:  (72, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBKD.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBKU.TO
Shape of DataFrame:  (577, 8)

Fetching data for: HBLK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1729, 8)
Fetching data for: HBM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4985, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBND.TO
Shape of DataFrame:  (323, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBNK.TO
Shape of DataFrame:  (371, 8)

Fetching data for: HBP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: HBU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4249, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HBUG.TO
Shape of DataFrame:  (770, 8)

Fetching data for: HCA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1129, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HCAL.TO
Shape of DataFrame:  (1055, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HCLN.TO

Shape of DataFrame:  (993, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HCON.TO

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HCRE.TO
Shape of DataFrame:  (252, 8)

Fetching data for: HDGE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1414, 8)
Fetching data for: HDIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (719, 8)
Fetching data for: HDIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (863, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HEB.TO
Shape of DataFrame:  (436, 8)

Fetching data for: HED.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4393, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HEQL.TO
Shape of DataFrame:  (213, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HEQT.TO

Shape of DataFrame:  (1325, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HERO.TO

Shape of DataFrame:  (1389, 8)
Fetching data for: HEU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4393, 8)
Fetching data for: HEWB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: HFD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4403, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HFG.TO

Shape of DataFrame:  (1129, 8)
Fetching data for: HFIN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (733, 8)
Fetching data for: HFR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: HFU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4403, 8)
Fetching data for: HGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4393, 8)
Fetching data for: HGGG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1495, 8)
Fetching data for: HGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1879, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HGRW.TO
Shape of DataFrame:  (307, 8)

Fetching data for: HGU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4393, 8)
Fetching data for: HGY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: HHL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2501, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HHLE.TO

Shape of DataFrame:  (547, 8)
Fetching data for: HIG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1692, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HIND.TO
Shape of DataFrame:

 (177, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HIU.TO

Shape of DataFrame:  (3685, 8)
Fetching data for: HIX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: HLF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HLIF.TO
Shape of DataFrame:  (639, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HLIT.TO

Shape of DataFrame:  (882, 8)
Fetching data for: HLPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1465, 8)
Fetching data for: HLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1704, 8)
Fetching data for: HMAX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (486, 8)
Fetching data for: HMMJ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1939, 8)
Fetching data for: HMP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2351, 8)
Fetching data for: HND.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4254, 8)
Fetching data for: HNU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4254, 8)
Fetching data for: HOD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4254, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HOU.TO

Shape of DataFrame:  (4254, 8)
Fetching data for: HPF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2429, 8)
Fetching data for: HPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3495, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HPYM.TO

Shape of DataFrame:  (239, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HPYT.TO
Shape of DataFrame:  (314, 8)

Fetching data for: HQD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: HQU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4033, 8)
Fetching data for: HRAA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1106, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HRED.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HREU.TO
Shape of DataFrame:  (834, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HRIF.TO
Shape of DataFrame:  (427, 8)

Fetching data for: HRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: HSAV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1225, 8)
Fetching data for: HSD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HSH.TO

Shape of DataFrame:  (2071, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HSU.TO

Shape of DataFrame:  (4033, 8)
Fetching data for: HTA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2407, 8)
Fetching data for: HTAE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (547, 8)
Fetching data for: HTB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2400, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HUBL.TO

Shape of DataFrame:  (1731, 8)
Fetching data for: HUC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: HUG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HULC.TO

Shape of DataFrame:  (1213, 8)
Fetching data for: HUM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1129, 8)
Fetching data for: HUN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: HURA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1410, 8)
Fetching data for: HUT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1711, 8)
Fetching data for: HUTE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (546, 8)
Fetching data for: HUTL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1487, 8)
Fetching data for: HUTS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (581, 8)
Fetching data for: HUV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3517, 8)
Fetching data for: HUZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: HWO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: HWX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: HXCN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1226, 8)
Fetching data for: HXD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4380, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HXDM.TO

Shape of DataFrame:  (1750, 8)
Fetching data for: HXE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2810, 8)
Fetching data for: HXEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1102, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HXF.TO

Shape of DataFrame:  (2808, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HXH.TO

Shape of DataFrame:  (2187, 8)
Fetching data for: HXQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2180, 8)
Fetching data for: HXS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3495, 8)
Fetching data for: HXT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3545, 8)
Fetching data for: HXU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4510, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: HXX.TO

Shape of DataFrame:  (2018, 8)
Fetching data for: HYBR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2819, 8)
Fetching data for: HYLD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (725, 8)
Fetching data for: HZD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3779, 8)
Fetching data for: HZU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3779, 8)
Fetching data for: IAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IAU.TO

Shape of DataFrame:  (932, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ICAE.TO
Shape of DataFrame:  (452, 8)

Fetching data for: ICE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ICPB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ICTE.TO

Shape of DataFrame:  (744, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IE.TO
Shape of DataFrame:  (628, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IFA.TO

Shape of DataFrame:  (3150, 8)
Fetching data for: IFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5032, 8)
Fetching data for: IFP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IFRF.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IGAF.TO
Shape of DataFrame:  (1293, 8)

Fetching data for: IGB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1623, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IGEO.TO
Shape of DataFrame:  (96, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IGET.TO
Shape of DataFrame:  (367, 8)

Fetching data for: IGM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IIAE.TO

Shape of DataFrame:  (469, 8)
Fetching data for: IICE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (745, 8)
Fetching data for: III.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: IIMF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (197, 8)
Fetching data for: IITE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (743, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ILGB.TO

Shape of DataFrame:  (836, 8)
Fetching data for: ILLM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2618, 8)
Fetching data for: IMG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: IMO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: IMP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: INAI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (235, 8)
Fetching data for: INCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (156, 8)
Fetching data for: INE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4279, 8)
Fetching data for: INOC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1787, 8)
Fetching data for: IPCO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1928, 8)
Fetching data for: IPO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2033, 8)
Fetching data for: IQD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2116, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IS.TO
Shape of DataFrame:  (161, 8)

Fetching data for: ISC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2879, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ISCB.TO
Shape of DataFrame:  (42, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ISO.TO
Shape of DataFrame:  (120, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ISTE.TO
Shape of DataFrame:  (743, 8)

Fetching data for: ITH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IUAE.TO
Shape of DataFrame:  (464, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IUCE.TO
Shape of DataFrame:  (743, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IUMF.TO
Shape of DataFrame:  (212, 8)

Fetching data for: IUTE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (730, 8)
Fetching data for: IVN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3061, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IVQ.TO

Shape of DataFrame:  (1323, 8)
Fetching data for: IWBE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (736, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: IXTE.TO
Shape of DataFrame:  (252, 8)

Fetching data for: JAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: JAPN.TO

Shape of DataFrame:  (253, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: JEPI.TO
Shape of DataFrame:  (61, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: JEPQ.TO
Shape of DataFrame:  (61, 8)

Fetching data for: JOY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2641, 8)
Fetching data for: JWEL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1873, 8)
Fetching data for: K.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: KBL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: KEC.TO
Shape of DataFrame:  (742, 8)

Fetching data for: KEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4131, 8)
Fetching data for: KEL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2968, 8)
Fetching data for: KEY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: KILO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1092, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: KITS.TO
Shape of DataFrame:  (990, 8)

Fetching data for: KLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: KNGC.TO
Shape of DataFrame:  (142, 8)

Fetching data for: KNGU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (143, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: KNGX.TO
Shape of DataFrame:  (108, 8)

Fetching data for: KNT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3493, 8)
Fetching data for: KPT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3020, 8)
Fetching data for: KRN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3522, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: KSI.TO

Shape of DataFrame:  (1965, 8)
Fetching data for: KXS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2648, 8)
Fetching data for: L.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: LAAC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4128, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LABS.TO
Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LAC.TO
Shape of DataFrame:  (308, 8)

Fetching data for: LAM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: LB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: LBS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4568, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LCFS.TO

Shape of DataFrame:  (847, 8)
Fetching data for: LCS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4437, 8)
Fetching data for: LEAD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1077, 8)
Fetching data for: LFE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4945, 8)
Fetching data for: LGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: LGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: LIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4121, 8)
Fetching data for: LIFE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LIRC.TO
Shape of DataFrame:  (454, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LLHE.TO
Shape of DataFrame:  (88, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LLYH.TO
Shape of DataFrame:  (89, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LMAX.TO
Shape of DataFrame:  (224, 8)

Fetching data for: LN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3260, 8)
Fetching data for: LNF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: LNR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LPAY.TO
Shape of DataFrame:  (308, 8)

Fetching data for: LSPD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1458, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LSPK.TO

Shape of DataFrame:  (874, 8)
Fetching data for: LUC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4742, 8)
Fetching data for: LUG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5269, 8)
Fetching data for: LUN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LYCT.TO

Shape of DataFrame:  (573, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: LYFR.TO

Shape of DataFrame:  (573, 8)
Fetching data for: MAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MARI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MART.TO
Shape of DataFrame:  (29, 8)

Fetching data for: MATR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MBAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1066, 8)
Fetching data for: MBX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MCAD.TO

Shape of DataFrame:  (252, 8)
Fetching data for: MCB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MCLC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1931, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MCLV.TO

Shape of DataFrame:  (72, 8)
Fetching data for: MCON.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1066, 8)
Fetching data for: MCSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1778, 8)
Fetching data for: MCSM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1712, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MDA.TO
Shape of DataFrame:  (936, 8)

Fetching data for: MDI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MDIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2952, 8)
Fetching data for: MDNA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1960, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MDP.TO

Shape of DataFrame:  (2753, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MDVD.TO
Shape of DataFrame:  (88, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MEG.TO

Shape of DataFrame:  (3605, 8)
Fetching data for: MEQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MEQT.TO
Shape of DataFrame:  (278, 8)

Fetching data for: MFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MFI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MFT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2176, 8)
Fetching data for: MG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5039, 8)
Fetching data for: MGA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5149, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MGAB.TO

Shape of DataFrame:  (1066, 8)
Fetching data for: MGB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2179, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MGDV.TO
Shape of DataFrame:  (140, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MGQE.TO
Shape of DataFrame:  (76, 8)

Fetching data for: MGRW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1066, 8)
Fetching data for: MHCD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1866, 8)
Fetching data for: MINF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1194, 8)
Fetching data for: MINN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1698, 8)
Fetching data for: MINT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1931, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MIQE.TO
Shape of DataFrame:  (76, 8)

Fetching data for: MIVG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1775, 8)
Fetching data for: MKB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2182, 8)
Fetching data for: MKP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MND.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4653, 8)
Fetching data for: MNO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5126, 8)
Fetching data for: MNS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2071, 8)
Fetching data for: MNT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MNXT.TO
Shape of DataFrame:  (75, 8)

Fetching data for: MNY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (575, 8)
Fetching data for: MOGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MORE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (76, 8)
Fetching data for: MPAY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (307, 8)
Fetching data for: MPC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MPVD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MPY.TO
Shape of DataFrame:  (198, 8)

Fetching data for: MRC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MRD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MREL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: MRU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MSA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (779, 8)
Fetching data for: MSCL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4261, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MSFH.TO

Shape of DataFrame:  (89, 8)
Fetching data for: MSHE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (88, 8)
Fetching data for: MSV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4784, 8)

Price          date     close  high   low  open  volume     tic  day
0        2004-01-02  0.489625  0.53  0.53  0.53       0  AAB.TO    4
1        2004-01-05  0.489625  0.53  0.53  0.53       0  AAB.TO    0
2        2004-01-06  0.258670  0.28  0.28  0.28     100  AAB.TO    1
3        2004-01-07  0.489625  0.53  0.53  0.53       0  AAB.TO    2
4        2004-01-08  0.489625  0.53  0.53  0.53       0  AAB.TO    3
...             ...       ...   ...   ...   ...     ...     ...  ...
2167770  2024-12-19  0.200000  0.20  0.18  0.18    5500  MSV.TO    3
2167771  2024-12-20  0.200000  0.20  0.20  0.20       0  MSV.TO    4
2167772  2024-12-23  0.190000  0.19  0.18  0.18   18800  MSV.TO    0
2167773  2024-12-24  0.180000  0.18  0.18  0.18    4500  MSV.TO    1
2167774  2024-12-27  0.190000  0.19  0.18  0.18   28700  MSV.TO    4

[2167775 rows x 8 columns]

In [11]:
SECOND_SET_TICKERS= ["MTAV.TO", "MTL.TO", "MTY.TO", "MUB.TO", "MULC.TO", "MULV.TO", "MUMC.TO", "MUSA.TO", "MUX.TO", "MWLV.TO", "MX.TO", "MXG.TO", "NA.TO", "NALT.TO", "NANO.TO", "NCF.TO", "NDIV.TO", "NDM.TO", "NEO.TO", "NEXT.TO", "NFI.TO", "NG.TO", "NGD.TO", "NGDN.TO", "NGEX.TO", "NGPE.TO", "NGT.TO", "NGUP.TO", "NHYB.TO", "NINT.TO", "NOA.TO", "NPI.TO", "NPK.TO", "NPRF.TO", "NPS.TO", "NREA.TO", "NRGY.TO", "NSCB.TO", "NSCC.TO", "NSCE.TO", "NSGE.TO", "NSSB.TO", "NTR.TO", "NUAG.TO", "NUBF.TO", "NUMI.TO", "NUSA.TO", "NVA.TO", "NVDH.TO", "NVHE.TO", "NVO.TO", "NWC.TO", "NXE.TO", "NXF.TO", "NXTG.TO", "OBE.TO", "OGC.TO", "OGD.TO", "OGI.TO", "OLA.TO", "OLY.TO", "ONC.TO", "ONEB.TO", "ONEC.TO", "ONEQ.TO", "ONEX.TO", "OPT.TO", "OR.TO", "ORA.TO", "ORE.TO", "ORV.TO", "OTEX.TO", "OVV.TO", "PAAS.TO", "PABF.TO", "PACF.TO", "PAGF.TO", "PAY.TO", "PAYF.TO", "PAYL.TO", "PAYM.TO", "PAYS.TO", "PBD.TO", "PBH.TO", "PBI.TO", "PBL.TO", "PCOR.TO", "PD.TO", "PDC.TO", "PDF.TO", "PDIV.TO", "PDN.TO", "PDV.TO", "PEA.TO", "PET.TO", "PEY.TO", "PFAA.TO", "PFAE.TO", "PFCB.TO", "PFIA.TO", "PFL.TO", "PFLS.TO", "PFMN.TO", "PFSS.TO", "PGIC.TO", "PHR.TO", "PHX.TO", "PHYS.TO", "PID.TO", "PIF.TO", "PIN.TO", "PINC.TO", "PKI.TO", "PLDI.TO", "PLV.TO", "PME.TO", "PMET.TO", "PMIF.TO", "PMM.TO", "PMNT.TO", "PNE.TO", "PNP.TO", "POU.TO", "POW.TO", "PPL.TO", "PPLN.TO", "PPR.TO", "PPTA.TO", "PR.TO", "PRA.TO", "PRB.TO", "PREF.TO", "PRL.TO", "PRM.TO", "PRN.TO", "PRQ.TO", "PRU.TO", "PRYM.TO", "PSA.TO", "PSB.TO", "PSD.TO", "PSI.TO", "PSK.TO", "PSLV.TO", "PTM.TO", "PWI.TO", "PXC.TO", "PXS.TO", "PXT.TO", "PYF.TO", "PYR.TO", "PZA.TO", "PZW.TO", "QAH.TO", "QASH.TO", "QBB.TO", "QBTC.TO", "QBTL.TO", "QCE.TO", "QCLN.TO", "QCN.TO", "QDX.TO", "QDXB.TO", "QDXH.TO", "QEBH.TO", "QEBL.TO", "QEC.TO", "QEE.TO", "QHY.TO", "QIE.TO", "QINF.TO", "QIPT.TO", "QLB.TO", "QMAX.TO", "QQC.TO", "QQCC.TO", "QQCE.TO", "QQCI.TO", "QQCL.TO", "QQEQ.TO", "QQJE.TO", "QQJR.TO", "QQQL.TO", "QQQT.TO", "QQQX.TO", "QQQY.TO", "QRC.TO", "QRET.TO", "QSB.TO", "QSR.TO", "QTLT.TO", "QTRH.TO", "QUB.TO", "QUIG.TO", "QUS.TO", "QUU.TO", "QXM.TO", "RAAA.TO", "RATE.TO", "RBA.TO", "RBNK.TO", "RBO.TO", "RBOT.TO", "RBY.TO", "RCD.TO", "RCDC.TO", "RCG.TO", "RCH.TO", "RDBH.TO", "REAL.TO", "RGQN.TO", "RGQO.TO", "RGQP.TO", "RGQQ.TO", "RGQR.TO", "RGQS.TO", "RID.TO", "RIDH.TO", "RIFI.TO", "RIIN.TO", "RING.TO", "RIRA.TO", "RIT.TO", "RLB.TO", "RMAX.TO", "ROOT.TO", "RPD.TO", "RPDH.TO", "RPF.TO", "RPSB.TO", "RQN.TO", "RQO.TO", "RQP.TO", "RQQ.TO", "RQR.TO", "RQS.TO", "RS.TO", "RSI.TO", "RTG.TO", "RUBH.TO", "RUBY.TO", "RUD.TO", "RUDB.TO", "RUDC.TO", "RUDH.TO", "RUP.TO", "RUQN.TO", "RUQO.TO", "RUQQ.TO", "RUQR.TO", "RUQS.TO", "RUS.TO", "RUSB.TO", "RVX.TO", "RXD.TO", "RY.TO", "S.TO", "SAFE.TO", "SAM.TO", "SAP.TO", "SAU.TO", "SBC.TO", "SBI.TO", "SBT.TO", "SCR.TO", "SCY.TO", "SDE.TO", "SEA.TO", "SEC.TO", "SES.TO", "SFC.TO", "SFD.TO", "SFI.TO", "SFTC.TO", "SGLD.TO", "SGY.TO", "SHLE.TO", "SHOP.TO", "SIA.TO", "SII.TO", "SIL.TO", "SIS.TO", "SJ.TO", "SKE.TO", "SKYY.TO", "SLF.TO", "SLR.TO", "SLS.TO", "SMAX.TO", "SMC.TO", "SMT.TO", "SOBO.TO", "SOIL.TO", "SOLG.TO", "SOY.TO", "SPAY.TO", "SPB.TO", "SPFD.TO", "SPLT.TO", "SPPP.TO", "SSL.TO", "SSRM.TO", "STC.TO", "STCK.TO", "STEP.TO", "STGO.TO", "STLR.TO", "STN.TO", "STPL.TO", "SU.TO", "SVA.TO", "SVB.TO", "SVI.TO", "SVM.TO", "SVR.TO", "SWP.TO", "SXI.TO", "SXP.TO", "SYLD.TO", "SYZ.TO", "T.TO", "TA.TO", "TAL.TO", "TBAL.TO", "TBCE.TO", "TBCF.TO", "TBCG.TO", "TBIL.TO", "TBL.TO", "TBNK.TO", "TC.TO", "TCBN.TO", "TCLB.TO", "TCLV.TO", "TCON.TO", "TCS.TO", "TCSB.TO", "TCSH.TO", "TCW.TO", "TD.TO", "TDB.TO", "TDOC.TO", "TEC.TO", "TECH.TO", "TECI.TO", "TECX.TO", "TERM.TO", "TF.TO", "TFII.TO", "TFPM.TO", "TGAF.TO", "TGED.TO", "TGFI.TO", "TGGR.TO", "TGO.TO", "TGRE.TO", "TGRO.TO", "TH.TO", "The.TO", "THNC.TO", "THU.TO", "TI.TO", "TIH.TO", "TILV.TO", "TINF.TO", "TIPS.TO", "TIXT.TO", "TKN.TO", "TKO.TO", "TLF.TO", "TLG.TO", "TLO.TO", "TLRY.TO", "TLV.TO", "TMQ.TO", "TNZ.TO", "TOT.TO", "TOU.TO", "TOWR.TO", "TOY.TO", "TPE.TO", "TPRF.TO", "TPU.TO", "TPZ.TO", "TQCD.TO", "TQGD.TO", "TQGM.TO", "TQSM.TO", "TRI.TO", "TRP.TO", "TRVI.TO", "TRVL.TO", "TRX.TO", "TRZ.TO", "TSAT.TO", "TSK.TO", "TSL.TO", "TSND.TO", "TSU.TO", "TTNM.TO", "TTP.TO", "TTTX.TO", "TUED.TO", "TUEX.TO", "TUHY.TO", "TULB.TO", "TULV.TO", "TUSB.TO", "TVE.TO", "TVK.TO", "TWC.TO", "TWM.TO", "TXF.TO", "TXG.TO", "TXP.TO", "UDA.TO", "UDIV.TO", "UMAX.TO", "UMI.TO", "UNC.TO", "UNI.TO", "URB.TO", "URC.TO", "URE.TO", "USA.TO", "USCC.TO", "USCL.TO", "USSL.TO", "USSX.TO", "UTES.TO", "UTIL.TO", "VA.TO", "VAB.TO", "VALT.TO", "VBAL.TO", "VBNK.TO", "VCB.TO", "VCE.TO", "VCIP.TO", "VCM.TO", "VCN.TO", "VCNS.TO", "VDU.TO", "VDY.TO", "VE.TO", "VEE.TO", "VEF.TO", "VEQT.TO", "VET.TO", "VFV.TO", "VGG.TO", "VGH.TO", "VGRO.TO", "VGV.TO", "VGZ.TO", "VHI.TO", "VI.TO", "VIDY.TO", "VIU.TO", "VLB.TO", "VLE.TO", "VLN.TO", "VMO.TO", "VNP.TO", "VOXR.TO", "VQS.TO", "VRE.TO", "VRIF.TO", "VRN.TO", "VRTS.TO", "VSB.TO", "VSC.TO", "VSP.TO", "VUN.TO", "VUS.TO", "VVL.TO", "VVO.TO", "VVSG.TO", "VXC.TO", "VXM.TO", "VZLA.TO", "WCN.TO", "WCP.TO", "WDO.TO", "WEED.TO", "WEF.TO", "WELL.TO", "WFC.TO", "WFG.TO", "WGX.TO", "WILD.TO", "WJX.TO", "WLLW.TO", "WM.TO", "WN.TO", "WNDR.TO", "WOMN.TO", "WPK.TO", "WPM.TO", "WPRT.TO", "WRG.TO", "WRN.TO", "WRX.TO", "WSP.TO", "WSRD.TO", "WSRI.TO", "WTE.TO", "WXM.TO", "X.TO", "XAD.TO", "XAGG.TO", "XAGH.TO", "XAM.TO", "XAU.TO", "XAW.TO", "XBAL.TO", "XBB.TO", "XBM.TO", "XCB.TO", "XCBG.TO", "XCBU.TO", "XCD.TO", "XCG.TO", "XCH.TO", "XCHP.TO", "XCLN.TO", "XCNS.TO", "XCS.TO", "XCSR.TO", "XCV.TO", "XDG.TO", "XDGH.TO", "XDIV.TO", "XDNA.TO", "XDRV.TO", "XDSR.TO", "XDU.TO", "XDUH.TO", "XDV.TO", "XEB.TO", "XEC.TO", "XEF.TO", "XEG.TO", "XEH.TO", "XEI.TO", "XEM.TO", "XEMC.TO", "XEN.TO", "XEQT.TO", "XESG.TO", "XETM.TO", "XEU.TO", "XEXP.TO", "XFH.TO", "XFLB.TO", "XFLI.TO", "XFLX.TO", "XFN.TO", "XFR.TO", "XGB.TO", "XGD.TO", "XGI.TO", "XGRO.TO", "XHAK.TO", "XHB.TO", "XHC.TO", "XHD.TO", "XHU.TO", "XHY.TO", "XIC.TO", "XID.TO", "XIG.TO", "XIGS.TO", "XIN.TO", "XINC.TO", "XIT.TO", "XIU.TO", "XLB.TO", "XLY.TO", "XMA.TO", "XMC.TO", "XMD.TO", "XMH.TO", "XMI.TO", "XML.TO", "XMM.TO", "XMS.TO", "XMTM.TO", "XMU.TO", "XMV.TO", "XMW.TO", "XMY.TO", "XPF.TO", "XQB.TO", "XQLT.TO", "XQQ.TO", "XQQU.TO", "XRB.TO", "XRE.TO", "XSAB.TO", "XSB.TO", "XSC.TO", "XSE.TO", "XSEA.TO", "XSEM.TO", "XSH.TO", "XSHG.TO", "XSHU.TO", "XSI.TO", "XSMC.TO", "XSMH.TO", "XSP.TO", "XSPC.TO", "XST.TO", "XSTB.TO", "XSTH.TO", "XSTP.TO", "XSU.TO", "XSUS.TO", "XTC.TO", "XTD.TO", "XTG.TO", "XTLH.TO", "XTLT.TO", "XTR.TO", "XTRA.TO", "XUH.TO", "XUS.TO", "XUSC.TO", "XUSF.TO", "XUSR.TO", "XUT.TO", "XUU.TO", "XVLU.TO", "XWD.TO", "Y.TO", "YCM.TO", "YGR.TO", "YRB.TO", "ZACE.TO", "ZAG.TO", "ZBAL.TO", "ZBBB.TO", "ZBI.TO", "ZBK.TO", "ZCB.TO", "ZCDB.TO", "ZCH.TO", "ZCLN.TO", "ZCM.TO", "ZCN.TO", "ZCON.TO", "ZCPB.TO", "ZCS.TO", "ZDB.TO", "ZDH.TO", "ZDI.TO", "ZDJ.TO", "ZDM.TO", "ZDV.TO", "ZDY.TO", "ZEA.TO", "ZEAT.TO", "ZEB.TO", "ZEF.TO", "ZEM.TO", "ZEO.TO", "ZEQ.TO", "ZEQT.TO", "ZESG.TO", "ZFC.TO", "ZFH.TO", "ZFL.TO", "ZFM.TO", "ZFN.TO", "ZFS.TO", "ZGB.TO", "ZGD.TO", "ZGI.TO", "ZGLD.TO", "ZGLH.TO", "ZGQ.TO", "ZGRN.TO", "ZGRO.TO", "ZGSB.TO", "ZHP.TO", "ZHU.TO", "ZHY.TO", "ZIC.TO", "ZID.TO", "ZIN.TO", "ZIQ.TO", "ZIU.TO", "ZJG.TO", "ZJK.TO", "ZJPN.TO", "ZLB.TO", "ZLC.TO", "ZLD.TO", "ZLE.TO", "ZLH.TO", "ZLI.TO", "ZLSC.TO", "ZLSU.TO", "ZLU.TO", "ZMBS.TO", "ZMI.TO", "ZMID.TO", "ZMMK.TO", "ZMP.TO", "ZMSB.TO", "ZMT.TO", "ZMU.TO", "ZNQ.TO", "ZPAY.TO", "ZPH.TO", "ZPL.TO", "ZPR.TO", "ZPS.TO", "ZPW.TO", "ZQB.TO", "ZQQ.TO", "ZRE.TO", "ZRR.TO", "ZSB.TO", "ZSDB.TO", "ZSML.TO", "ZSP.TO", "ZST.TO", "ZSU.TO", "ZTIP.TO", "ZUAG.TO", "ZUB.TO", "ZUCM.TO", "ZUD.TO", "ZUE.TO", "ZUGE.TO", "ZUH.TO", "ZUP.TO", "ZUQ.TO", "ZUT.TO", "ZVC.TO", "ZVU.TO", "ZWA.TO", "ZWB.TO", "ZWC.TO", "ZWE.TO", "ZWEN.TO", "ZWG.TO", "ZWH.TO", "ZWHC.TO", "ZWK.TO", "ZWP.TO", "ZWQT.TO", "ZWS.TO", "ZWT.TO", "ZWU.TO", "ZXM.TO", "ZZZD.TO"]

print(len(SECOND_SET_TICKERS))

759

In [12]:
import time
import pandas as pd

# Function to fetch data with rate limiting
def fetch_data_with_rate_limiting(start_date, end_date, ticker_list, requests_per_minute=100):
    data = []
    delay = 60 / requests_per_minute  # Calculate delay to respect the limit

    for i, ticker in enumerate(ticker_list):
        try:
            print(f"Fetching data for: {ticker}")
            downloader = YahooDownloader(start_date=start_date, end_date=end_date, ticker_list=[ticker])
            ticker_data = downloader.fetch_data()
            data.append(ticker_data)
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")

        if i < len(ticker_list) - 1:  # Avoid sleeping after the last request
            time.sleep(delay)

    return pd.concat(data, ignore_index=True)

# Fetch data with rate limiting
second_portfolio_raw_df = fetch_data_with_rate_limiting(
    start_date='2004-01-01',
    end_date='2024-12-30',
    ticker_list=SECOND_SET_TICKERS,  # Replace with your list of tickers
    requests_per_minute=100  # Limit to 100 requests per minute
)

second_portfolio_raw_df

Fetching data for: MTAV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (773, 8)
Fetching data for: MTL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MTY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3668, 8)
Fetching data for: MUB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2180, 8)
Fetching data for: MULC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1732, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MULV.TO
Shape of DataFrame:  (141, 8)

Fetching data for: MUMC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1931, 8)
Fetching data for: MUSA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2763, 8)
Fetching data for: MUX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4600, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: MWLV.TO
Shape of DataFrame:  (168, 8)

Fetching data for: MX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: MXG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NALT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1477, 8)
Fetching data for: NANO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NCF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3106, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NDIV.TO

Shape of DataFrame:  (978, 8)
Fetching data for: NDM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NEO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1769, 8)
Fetching data for: NEXT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: NFI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: NG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NGDN.TO
Shape of DataFrame:  (10, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NGEX.TO
Shape of DataFrame:  (1345, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NGPE.TO
Shape of DataFrame:  (1210, 8)

Fetching data for: NGT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1428, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NGUP.TO
Shape of DataFrame:  (15, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NHYB.TO

Shape of DataFrame:  (252, 8)
Fetching data for: NINT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (970, 8)
Fetching data for: NOA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: NPI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NPK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NPRF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1477, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NPS.TO
Shape of DataFrame:  (214, 8)

Fetching data for: NREA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1477, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NRGY.TO
Shape of DataFrame:  (34, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NSCB.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NSCC.TO

Shape of DataFrame:  (966, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NSCE.TO
Shape of DataFrame:  (1208, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NSGE.TO

Shape of DataFrame:  (1210, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NSSB.TO
Shape of DataFrame:  (723, 8)

Fetching data for: NTR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1755, 8)
Fetching data for: NUAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1965, 8)
Fetching data for: NUBF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1301, 8)
Fetching data for: NUMI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1157, 8)
Fetching data for: NUSA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (971, 8)
Fetching data for: NVA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NVDH.TO
Shape of DataFrame:  (88, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: NVHE.TO
Shape of DataFrame:  (88, 8)

Fetching data for: NVO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3648, 8)
Fetching data for: NWC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: NXE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2633, 8)
Fetching data for: NXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2478, 8)
Fetching data for: NXTG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2550, 8)
Fetching data for: OBE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: OGC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: OGD.TO

Shape of DataFrame:  (4122, 8)
Fetching data for: OGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3258, 8)
Fetching data for: OLA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1978, 8)
Fetching data for: OLY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4234, 8)
Fetching data for: ONC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: ONEB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ONEC.TO
Shape of DataFrame:  (981, 8)

Fetching data for: ONEQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2316, 8)
Fetching data for: ONEX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: OPT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3874, 8)
Fetching data for: OR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2523, 8)
Fetching data for: ORA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4623, 8)
Fetching data for: ORE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1622, 8)
Fetching data for: ORV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: OTEX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: OVV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PAAS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PABF.TO
Shape of DataFrame:  (282, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PACF.TO
Shape of DataFrame:  (237, 8)

Fetching data for: PAGF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (297, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PAY.TO
Shape of DataFrame:  (948, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PAYF.TO

Shape of DataFrame:  (1401, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PAYL.TO
Shape of DataFrame:  (23, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PAYM.TO
Shape of DataFrame:  (6, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PAYS.TO
Shape of DataFrame:  (144, 8)

Fetching data for: PBD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2840, 8)
Fetching data for: PBH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: PBI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2677, 8)
Fetching data for: PBL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4123, 8)
Fetching data for: PCOR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1220, 8)
Fetching data for: PD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4756, 8)
Fetching data for: PDC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: PDF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2841, 8)
Fetching data for: PDIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2974, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PDN.TO
Shape of DataFrame:  (1, 8)

Fetching data for: PDV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: PEA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PET.TO
Shape of DataFrame:  (881, 8)

Fetching data for: PEY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PFAA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (662, 8)
Fetching data for: PFAE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1371, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PFCB.TO
Shape of DataFrame:  (536, 8)

Fetching data for: PFIA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1367, 8)
Fetching data for: PFL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2522, 8)
Fetching data for: PFLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1103, 8)
Fetching data for: PFMN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1369, 8)
Fetching data for: PFSS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (865, 8)
Fetching data for: PGIC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: PHR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2677, 8)
Fetching data for: PHX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PHYS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1731, 8)
Fetching data for: PID.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2426, 8)
Fetching data for: PIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4503, 8)
Fetching data for: PIN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2695, 8)
Fetching data for: PINC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1667, 8)
Fetching data for: PKI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PLDI.TO
Shape of DataFrame:  (252, 8)

Fetching data for: PLV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2418, 8)
Fetching data for: PME.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4393, 8)
Fetching data for: PMET.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2594, 8)
Fetching data for: PMIF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1732, 8)
Fetching data for: PMM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2523, 8)
Fetching data for: PMNT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1482, 8)
Fetching data for: PNE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4949, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PNP.TO

Shape of DataFrame:  (5271, 8)
Fetching data for: POU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: POW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PPL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PPLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2624, 8)
Fetching data for: PPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2075, 8)
Fetching data for: PPTA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3373, 8)
Fetching data for: PR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2348, 8)
Fetching data for: PRA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2838, 8)
Fetching data for: PRB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5269, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PREF.TO
Shape of DataFrame:  (123, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PRL.TO
Shape of DataFrame:  (801, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: PRM.TO

Shape of DataFrame:  (1778, 8)
Fetching data for: PRN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1624, 8)
Fetching data for: PRQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2228, 8)
Fetching data for: PRU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3731, 8)
Fetching data for: PRYM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PSA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2789, 8)
Fetching data for: PSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3231, 8)
Fetching data for: PSD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PSI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PSK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2656, 8)
Fetching data for: PSLV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1731, 8)
Fetching data for: PTM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: PWI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (904, 8)
Fetching data for: PXC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3241, 8)
Fetching data for: PXS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2423, 8)
Fetching data for: PXT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: PYF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2242, 8)
Fetching data for: PYR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3112, 8)
Fetching data for: PZA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4811, 8)
Fetching data for: PZW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2414, 8)
Fetching data for: QAH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1725, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QASH.TO

Shape of DataFrame:  (274, 8)
Fetching data for: QBB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1712, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QBTC.TO
Shape of DataFrame:  (1050, 8)

Fetching data for: QBTL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1312, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QCE.TO

Shape of DataFrame:  (1733, 8)
Fetching data for: QCLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2550, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QCN.TO

Shape of DataFrame:  (1732, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QDX.TO

Shape of DataFrame:  (1732, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QDXB.TO
Shape of DataFrame:  (1009, 8)

Fetching data for: QDXH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1736, 8)
Fetching data for: QEBH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1332, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QEBL.TO

Shape of DataFrame:  (1299, 8)
Fetching data for: QEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QEE.TO
Shape of DataFrame:  (725, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QHY.TO

Shape of DataFrame:  (1734, 8)
Fetching data for: QIE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1983, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QINF.TO
Shape of DataFrame:  (252, 8)

Fetching data for: QIPT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1504, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QLB.TO
Shape of DataFrame:  (109, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QMAX.TO
Shape of DataFrame:  (295, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQC.TO
Shape of DataFrame:  (900, 8)

Fetching data for: QQCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQCE.TO
Shape of DataFrame:  (793, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQCI.TO
Shape of DataFrame:  (91, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQCL.TO
Shape of DataFrame:  (306, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQEQ.TO
Shape of DataFrame:  (908, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQJE.TO

Shape of DataFrame:  (793, 8)
Fetching data for: QQJR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (900, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQQL.TO
Shape of DataFrame:  (98, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQQT.TO
Shape of DataFrame:  (368, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQQX.TO
Shape of DataFrame:  (154, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QQQY.TO

Shape of DataFrame:  (307, 8)
Fetching data for: QRC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3112, 8)
Fetching data for: QRET.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1069, 8)
Fetching data for: QSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1721, 8)
Fetching data for: QSR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2519, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QTLT.TO
Shape of DataFrame:  (270, 8)

Fetching data for: QTRH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: QUB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1051, 8)
Fetching data for: QUIG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1712, 8)
Fetching data for: QUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1983, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: QUU.TO

Shape of DataFrame:  (1738, 8)
Fetching data for: QXM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3236, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RAAA.TO
Shape of DataFrame:  (70, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RATE.TO

Shape of DataFrame:  (1773, 8)
Fetching data for: RBA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: RBNK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1803, 8)
Fetching data for: RBO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2747, 8)
Fetching data for: RBOT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1776, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RBY.TO
Shape of DataFrame:  (826, 8)

Fetching data for: RCD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2749, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RCDC.TO
Shape of DataFrame:  (486, 8)

Fetching data for: RCG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: RCH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RDBH.TO

Shape of DataFrame:  (405, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: REAL.TO
Shape of DataFrame:  (1899, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQN.TO

Shape of DataFrame:  (400, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQO.TO

Shape of DataFrame:  (400, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQP.TO

Shape of DataFrame:  (251, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQQ.TO
Shape of DataFrame:  (251, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQR.TO
Shape of DataFrame:  (251, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RGQS.TO
Shape of DataFrame:  (171, 8)

Fetching data for: RID.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2749, 8)
Fetching data for: RIDH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2552, 8)
Fetching data for: RIFI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1239, 8)
Fetching data for: RIIN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1239, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RING.TO
Shape of DataFrame:  (33, 8)

Fetching data for: RIRA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1238, 8)
Fetching data for: RIT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4115, 8)
Fetching data for: RLB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2071, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RMAX.TO
Shape of DataFrame:  (131, 8)

Fetching data for: ROOT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1801, 8)
Fetching data for: RPD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2549, 8)
Fetching data for: RPDH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2538, 8)
Fetching data for: RPF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2075, 8)
Fetching data for: RPSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1798, 8)
Fetching data for: RQN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1480, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RQO.TO
Shape of DataFrame:  (252, 8)

Fetching data for: RQP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RQQ.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RQR.TO
Shape of DataFrame:  (252, 8)

Fetching data for: RQS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (171, 8)
Fetching data for: RS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1030, 8)
Fetching data for: RSI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RTG.TO

Shape of DataFrame:  (3509, 8)
Fetching data for: RUBH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1658, 8)
Fetching data for: RUBY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1662, 8)
Fetching data for: RUD.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'RUD.TO' reason: 'chart'
[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['RUD.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Error fetching data for RUD.TO: no data is fetched.

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUDB.TO

Shape of DataFrame:  (403, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUDC.TO
Shape of DataFrame:  (490, 8)

Fetching data for: RUDH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2556, 8)
Fetching data for: RUP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUQN.TO

Shape of DataFrame:  (171, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUQO.TO
Shape of DataFrame:  (169, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUQQ.TO

Shape of DataFrame:  (171, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUQR.TO

Shape of DataFrame:  (171, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: RUQS.TO
Shape of DataFrame:  (170, 8)

Fetching data for: RUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: RUSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1773, 8)
Fetching data for: RVX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: RXD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2556, 8)
Fetching data for: RY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: S.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SAFE.TO
Shape of DataFrame:  (29, 8)

Fetching data for: SAM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5146, 8)
Fetching data for: SAP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SAU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3605, 8)
Fetching data for: SBC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4798, 8)
Fetching data for: SBI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3450, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SBT.TO
Shape of DataFrame:  (2154, 8)

Fetching data for: SCR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3704, 8)
Fetching data for: SCY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2523, 8)
Fetching data for: SDE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4663, 8)
Fetching data for: SEA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SES.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3691, 8)
Fetching data for: SFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: SFD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4283, 8)
Fetching data for: SFI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4280, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SFTC.TO
Shape of DataFrame:  (901, 8)

Fetching data for: SGLD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: SGY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SHLE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1932, 8)
Fetching data for: SHOP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2411, 8)
Fetching data for: SIA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: SII.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: SIL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1624, 8)
Fetching data for: SIS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SJ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SKE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SKYY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2550, 8)
Fetching data for: SLF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SLR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SLS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1120, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SMAX.TO

Shape of DataFrame:  (295, 8)
Fetching data for: SMC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2606, 8)
Fetching data for: SMT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SOBO.TO
Shape of DataFrame:  (65, 8)

Fetching data for: SOIL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5123, 8)
Fetching data for: SOLG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1562, 8)
Fetching data for: SOY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SPAY.TO
Shape of DataFrame:  (306, 8)

Fetching data for: SPB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SPFD.TO
Shape of DataFrame:  (478, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SPLT.TO
Shape of DataFrame:  (383, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SPPP.TO
Shape of DataFrame:  (1731, 8)

Fetching data for: SSL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4126, 8)
Fetching data for: SSRM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: STC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: STCK.TO
Shape of DataFrame:  (887, 8)

Fetching data for: STEP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1624, 8)
Fetching data for: STGO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1658, 8)
Fetching data for: STLR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: STN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: STPL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1936, 8)
Fetching data for: SU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SVA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SVB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3545, 8)
Fetching data for: SVI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: SVM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SVR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: SWP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SXI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: SXP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4703, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: SYLD.TO
Shape of DataFrame:  (252, 8)

Fetching data for: SYZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5182, 8)
Fetching data for: T.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBAL.TO

Shape of DataFrame:  (1095, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBCE.TO
Shape of DataFrame:  (181, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBCF.TO
Shape of DataFrame:  (181, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBCG.TO
Shape of DataFrame:  (181, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBIL.TO
Shape of DataFrame:  (198, 8)

Fetching data for: TBL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4678, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TBNK.TO

Shape of DataFrame:  (419, 8)
Fetching data for: TC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4857, 8)
Fetching data for: TCBN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (585, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TCLB.TO

Shape of DataFrame:  (252, 8)
Fetching data for: TCLV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1147, 8)
Fetching data for: TCON.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1090, 8)
Fetching data for: TCS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TCSB.TO

Shape of DataFrame:  (1535, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TCSH.TO
Shape of DataFrame:  (213, 8)

Fetching data for: TCW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TDB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2196, 8)
Fetching data for: TDOC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (930, 8)
Fetching data for: TEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1415, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TECH.TO

Shape of DataFrame:  (915, 8)
Fetching data for: TECI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (772, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TECX.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TERM.TO
Shape of DataFrame:  (1026, 8)

Fetching data for: TF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2129, 8)
Fetching data for: TFII.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)
Fetching data for: TFPM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (905, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TGAF.TO
Shape of DataFrame:  (277, 8)

Fetching data for: TGED.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1415, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TGFI.TO

Shape of DataFrame:  (1277, 8)
Fetching data for: TGGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1146, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TGO.TO

Shape of DataFrame:  (4393, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TGRE.TO
Shape of DataFrame:  (252, 8)

Fetching data for: TGRO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1093, 8)
Fetching data for: TH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: The.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2195, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: THNC.TO
Shape of DataFrame:  (922, 8)

Fetching data for: THU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2196, 8)
Fetching data for: TI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1805, 8)
Fetching data for: TIH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TILV.TO
Shape of DataFrame:  (1414, 8)

Fetching data for: TINF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1148, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TIPS.TO
Shape of DataFrame:  (486, 8)

Fetching data for: TIXT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (979, 8)
Fetching data for: TKN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (981, 8)
Fetching data for: TKO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TLF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3244, 8)
Fetching data for: TLG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5269, 8)
Fetching data for: TLO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4948, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TLRY.TO

Shape of DataFrame:  (916, 8)
Fetching data for: TLV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3176, 8)
Fetching data for: TMQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3181, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TNZ.TO
Shape of DataFrame:  (1624, 8)

Fetching data for: TOT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TOU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3537, 8)
Fetching data for: TOWR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (708, 8)
Fetching data for: TOY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2361, 8)
Fetching data for: TPE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2196, 8)
Fetching data for: TPRF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1536, 8)
Fetching data for: TPU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2196, 8)
Fetching data for: TPZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1052, 8)
Fetching data for: TQCD.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'TQCD.TO' reason: 'chart'
[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['TQCD.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Error fetching data for TQCD.TO: no data is fetched.
Fetching data for: TQGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1277, 8)
Fetching data for: TQGM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TQSM.TO
Shape of DataFrame:  (252, 8)

Fetching data for: TRI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4157, 8)
Fetching data for: TRP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TRVI.TO

Shape of DataFrame:  (431, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TRVL.TO
Shape of DataFrame:  (993, 8)

Fetching data for: TRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TRZ.TO

Shape of DataFrame:  (3994, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TSAT.TO
Shape of DataFrame:  (774, 8)

Fetching data for: TSK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5280, 8)
Fetching data for: TSL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TSND.TO
Shape of DataFrame:  (1921, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TSU.TO
Shape of DataFrame:  (1816, 8)

Fetching data for: TTNM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2432, 8)
Fetching data for: TTP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2195, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TTTX.TO
Shape of DataFrame:  (154, 8)

Fetching data for: TUED.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1147, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TUEX.TO
Shape of DataFrame:  (425, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TUHY.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TULB.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: TULV.TO
Shape of DataFrame:  (1147, 8)

Fetching data for: TUSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1534, 8)
Fetching data for: TVE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4230, 8)
Fetching data for: TVK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2733, 8)
Fetching data for: TWC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: TWM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2383, 8)
Fetching data for: TXF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: TXG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: TXP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UDA.TO

Shape of DataFrame:  (1200, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UDIV.TO
Shape of DataFrame:  (1026, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UMAX.TO
Shape of DataFrame:  (386, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UMI.TO

Shape of DataFrame:  (1732, 8)
Fetching data for: UNC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: UNI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4762, 8)
Fetching data for: URB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4509, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: URC.TO

Shape of DataFrame:  (1266, 8)
Fetching data for: URE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4755, 8)
Fetching data for: USA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: USCC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2745, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: USCL.TO
Shape of DataFrame:  (372, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: USSL.TO

Shape of DataFrame:  (103, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: USSX.TO

Shape of DataFrame:  (155, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UTES.TO
Shape of DataFrame:  (80, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: UTIL.TO
Shape of DataFrame:  (252, 8)

Fetching data for: VA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2628, 8)
Fetching data for: VAB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: VALT.TO
Shape of DataFrame:  (995, 8)

Fetching data for: VBAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1733, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: VBNK.TO

Shape of DataFrame:  (2842, 8)
Fetching data for: VCB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1978, 8)
Fetching data for: VCE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: VCIP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1480, 8)
Fetching data for: VCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4535, 8)
Fetching data for: VCN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2855, 8)
Fetching data for: VCNS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1733, 8)
Fetching data for: VDU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2856, 8)
Fetching data for: VDY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3045, 8)
Fetching data for: VE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2628, 8)
Fetching data for: VEE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: VEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: VEQT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1480, 8)
Fetching data for: VET.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: VFV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3045, 8)
Fetching data for: VGG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2856, 8)
Fetching data for: VGH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2853, 8)
Fetching data for: VGRO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1733, 8)
Fetching data for: VGV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1978, 8)
Fetching data for: VGZ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: VHI.TO
Shape of DataFrame:  (819, 8)

Fetching data for: VI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2272, 8)
Fetching data for: VIDY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: VIU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2272, 8)
Fetching data for: VLB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1978, 8)
Fetching data for: VLE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: VLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: VMO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2135, 8)
Fetching data for: VNP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4270, 8)
Fetching data for: VOXR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1154, 8)
Fetching data for: VQS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: VRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3045, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: VRIF.TO
Shape of DataFrame:  (1075, 8)

Fetching data for: VRN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: VRTS.TO

Shape of DataFrame:  (913, 8)
Fetching data for: VSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: VSC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3045, 8)
Fetching data for: VSP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3045, 8)
Fetching data for: VUN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2856, 8)
Fetching data for: VUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: VVL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2137, 8)
Fetching data for: VVO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2136, 8)
Fetching data for: VVSG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (74, 8)
Fetching data for: VXC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2628, 8)
Fetching data for: VXM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2533, 8)
Fetching data for: VZLA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1565, 8)
Fetching data for: WCN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WCP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WDO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WEED.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3605, 8)
Fetching data for: WEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4310, 8)
Fetching data for: WELL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3002, 8)
Fetching data for: WFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WFG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WGX.TO
Shape of DataFrame:  (100, 8)

Fetching data for: WILD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4659, 8)
Fetching data for: WJX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5268, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WLLW.TO
Shape of DataFrame:  (973, 8)

Fetching data for: WM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WNDR.TO
Shape of DataFrame:  (835, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WOMN.TO
Shape of DataFrame:  (252, 8)

Fetching data for: WPK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WPM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5039, 8)
Fetching data for: WPRT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WRG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: WRN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4671, 8)
Fetching data for: WRX.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4122, 8)
Fetching data for: WSP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2755, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WSRD.TO
Shape of DataFrame:  (1137, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: WSRI.TO

Shape of DataFrame:  (1137, 8)
Fetching data for: WTE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5270, 8)
Fetching data for: WXM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3229, 8)
Fetching data for: X.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XAD.TO

Shape of DataFrame:  (235, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XAGG.TO
Shape of DataFrame:  (145, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XAGH.TO
Shape of DataFrame:  (853, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XAM.TO
Shape of DataFrame:  (1546, 8)

Fetching data for: XAU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2415, 8)
Fetching data for: XAW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2473, 8)
Fetching data for: XBAL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4396, 8)
Fetching data for: XBB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XBM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: XCB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4550, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XCBG.TO

Shape of DataFrame:  (853, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XCBU.TO
Shape of DataFrame:  (79, 8)

Fetching data for: XCD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2943, 8)
Fetching data for: XCG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4550, 8)
Fetching data for: XCH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3744, 8)
Fetching data for: XCHP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (266, 8)
Fetching data for: XCLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (666, 8)
Fetching data for: XCNS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1342, 8)
Fetching data for: XCS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4419, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XCSR.TO
Shape of DataFrame:  (1175, 8)

Fetching data for: XCV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4550, 8)
Fetching data for: XDG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: XDGH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1816, 8)
Fetching data for: XDIV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1891, 8)
Fetching data for: XDNA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (666, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XDRV.TO
Shape of DataFrame:  (252, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XDSR.TO

Shape of DataFrame:  (1167, 8)
Fetching data for: XDU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1891, 8)
Fetching data for: XDUH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: XDV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4770, 8)
Fetching data for: XEB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: XEC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2938, 8)
Fetching data for: XEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2938, 8)
Fetching data for: XEG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XEH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2680, 8)
Fetching data for: XEI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: XEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XEMC.TO
Shape of DataFrame:  (252, 8)

Fetching data for: XEN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4419, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XEQT.TO

Shape of DataFrame:  (1349, 8)
Fetching data for: XESG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1439, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XETM.TO
Shape of DataFrame:  (100, 8)

Fetching data for: XEU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2681, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XEXP.TO
Shape of DataFrame:  (648, 8)

Fetching data for: XFH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2473, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XFLB.TO
Shape of DataFrame:  (475, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XFLI.TO

Shape of DataFrame:  (64, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XFLX.TO
Shape of DataFrame:  (36, 8)

Fetching data for: XFN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XFR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3272, 8)
Fetching data for: XGB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4550, 8)
Fetching data for: XGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2943, 8)
Fetching data for: XGRO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4396, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XHAK.TO

Shape of DataFrame:  (252, 8)
Fetching data for: XHB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3545, 8)
Fetching data for: XHC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: XHD.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'XHD.TO' reason: 'chart'
[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['XHD.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Error fetching data for XHD.TO: no data is fetched.
Fetching data for: XHU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2473, 8)
Fetching data for: XHY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3744, 8)
Fetching data for: XIC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XID.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3744, 8)
Fetching data for: XIG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3744, 8)
Fetching data for: XIGS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (870, 8)
Fetching data for: XIN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XINC.TO

Shape of DataFrame:  (1349, 8)
Fetching data for: XIT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XIU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XLB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4550, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XLY.TO

Shape of DataFrame:  (1645, 8)
Fetching data for: XMA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4770, 8)
Fetching data for: XMC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2356, 8)
Fetching data for: XMD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XMH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2355, 8)
Fetching data for: XMI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3102, 8)
Fetching data for: XML.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2188, 8)
Fetching data for: XMM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3103, 8)
Fetching data for: XMS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2188, 8)
Fetching data for: XMTM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1326, 8)
Fetching data for: XMU.TO

ERROR:yfinance:Could not get exchangeTimezoneName for ticker 'XMU.TO' reason: 'chart'
[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['XMU.TO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Error fetching data for XMU.TO: no data is fetched.
Fetching data for: XMV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3111, 8)
Fetching data for: XMW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3106, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XMY.TO

Shape of DataFrame:  (2143, 8)
Fetching data for: XPF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3538, 8)
Fetching data for: XQB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: XQLT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1329, 8)
Fetching data for: XQQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3422, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XQQU.TO
Shape of DataFrame:  (299, 8)

Fetching data for: XRB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4770, 8)
Fetching data for: XRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XSAB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1439, 8)
Fetching data for: XSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XSC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2326, 8)
Fetching data for: XSE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2071, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XSEA.TO
Shape of DataFrame:  (252, 8)

Fetching data for: XSEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1448, 8)
Fetching data for: XSH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3330, 8)
Fetching data for: XSHG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (853, 8)
Fetching data for: XSHU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (874, 8)
Fetching data for: XSI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2485, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XSMC.TO

Shape of DataFrame:  (1329, 8)
Fetching data for: XSMH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1329, 8)
Fetching data for: XSP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XSPC.TO

Shape of DataFrame:  (111, 8)
Fetching data for: XST.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XSTB.TO

Shape of DataFrame:  (1435, 8)
Fetching data for: XSTH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (868, 8)
Fetching data for: XSTP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (731, 8)
Fetching data for: XSU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4419, 8)
Fetching data for: XSUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1448, 8)
Fetching data for: XTC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: XTD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4346, 8)
Fetching data for: XTG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3537, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XTLH.TO
Shape of DataFrame:  (252, 8)

Fetching data for: XTLT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (471, 8)
Fetching data for: XTR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4770, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XTRA.TO
Shape of DataFrame:  (1624, 8)

Fetching data for: XUH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2473, 8)
Fetching data for: XUS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2938, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XUSC.TO
Shape of DataFrame:  (112, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: XUSF.TO
Shape of DataFrame:  (330, 8)

Fetching data for: XUSR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1175, 8)
Fetching data for: XUT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: XUU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2473, 8)
Fetching data for: XVLU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1329, 8)
Fetching data for: XWD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3805, 8)
Fetching data for: Y.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3015, 8)
Fetching data for: YCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3545, 8)
Fetching data for: YGR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)
Fetching data for: YRB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (5271, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZACE.TO
Shape of DataFrame:

 (891, 8)
Fetching data for: ZAG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZBAL.TO

Shape of DataFrame:  (1472, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZBBB.TO

Shape of DataFrame:  (1229, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZBI.TO

Shape of DataFrame:  (722, 8)
Fetching data for: ZBK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZCB.TO

Shape of DataFrame:  (1696, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZCDB.TO
Shape of DataFrame:  (736, 8)

Fetching data for: ZCH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZCLN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (985, 8)
Fetching data for: ZCM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZCN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3668, 8)
Fetching data for: ZCON.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZCPB.TO

Shape of DataFrame:  (1651, 8)
Fetching data for: ZCS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZDB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2726, 8)
Fetching data for: ZDH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2335, 8)
Fetching data for: ZDI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2541, 8)
Fetching data for: ZDJ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZDM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZDV.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: ZDY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2943, 8)
Fetching data for: ZEA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZEAT.TO

Shape of DataFrame:  (486, 8)
Fetching data for: ZEB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZEF.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)
Fetching data for: ZEM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZEO.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZEQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)
Fetching data for: ZEQT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (724, 8)
Fetching data for: ZESG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1238, 8)
Fetching data for: ZFC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1517, 8)
Fetching data for: ZFH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)
Fetching data for: ZFL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)
Fetching data for: ZFM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)

[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ZFN.TO']: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))

Fetching data for: ZFN.TO
Error fetching data for ZFN.TO: no data is fetched.
Fetching data for: ZFS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3668, 8)
Fetching data for: ZGB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1710, 8)
Fetching data for: ZGD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3033, 8)
Fetching data for: ZGI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZGLD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (202, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZGLH.TO

Shape of DataFrame:  (70, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZGQ.TO

Shape of DataFrame:  (2541, 8)
Fetching data for: ZGRN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (733, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZGRO.TO

Shape of DataFrame:  (1472, 8)
Fetching data for: ZGSB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1652, 8)
Fetching data for: ZHP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1973, 8)
Fetching data for: ZHU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1462, 8)
Fetching data for: ZHY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3698, 8)
Fetching data for: ZIC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2950, 8)
Fetching data for: ZID.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZIN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3034, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZIQ.TO
Shape of DataFrame:  (38, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZIU.TO
Shape of DataFrame:  (312, 8)

Fetching data for: ZJG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZJK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: ZJPN.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (733, 8)
Fetching data for: ZLB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: ZLC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZLD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2071, 8)
Fetching data for: ZLE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2162, 8)
Fetching data for: ZLH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2071, 8)
Fetching data for: ZLI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2335, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZLSC.TO
Shape of DataFrame:  (313, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZLSU.TO

Shape of DataFrame:  (313, 8)
Fetching data for: ZLU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2943, 8)
Fetching data for: ZMBS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1215, 8)
Fetching data for: ZMI.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3488, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZMID.TO

Shape of DataFrame:  (1213, 8)
Fetching data for: ZMMK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (770, 8)
Fetching data for: ZMP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2950, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZMSB.TO
Shape of DataFrame:  (1633, 8)

Fetching data for: ZMT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)
Fetching data for: ZMU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2950, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZNQ.TO
Shape of DataFrame:  (252, 8)

Fetching data for: ZPAY.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1239, 8)
Fetching data for: ZPH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1975, 8)
Fetching data for: ZPL.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2943, 8)
Fetching data for: ZPR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3033, 8)
Fetching data for: ZPS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3668, 8)
Fetching data for: ZPW.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2333, 8)
Fetching data for: ZQB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1224, 8)
Fetching data for: ZQQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZRE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)
Fetching data for: ZRR.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZSB.TO

Shape of DataFrame:  (1710, 8)
Fetching data for: ZSDB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (252, 8)
Fetching data for: ZSML.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1216, 8)
Fetching data for: ZSP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3032, 8)
Fetching data for: ZST.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3488, 8)
Fetching data for: ZSU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZTIP.TO

Shape of DataFrame:  (985, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZUAG.TO
Shape of DataFrame:  (476, 8)

Fetching data for: ZUB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZUCM.TO
Shape of DataFrame:  (306, 8)

Fetching data for: ZUD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2950, 8)
Fetching data for: ZUE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3685, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZUGE.TO
Shape of DataFrame:  (382, 8)

Fetching data for: ZUH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3660, 8)
Fetching data for: ZUP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1975, 8)
Fetching data for: ZUQ.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2540, 8)
Fetching data for: ZUT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3746, 8)
Fetching data for: ZVC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1750, 8)
Fetching data for: ZVU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1732, 8)
Fetching data for: ZWA.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: ZWB.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3488, 8)
Fetching data for: ZWC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1975, 8)
Fetching data for: ZWE.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2333, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZWEN.TO
Shape of DataFrame:  (483, 8)

Fetching data for: ZWG.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1239, 8)
Fetching data for: ZWH.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2727, 8)
Fetching data for: ZWHC.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (483, 8)
Fetching data for: ZWK.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1472, 8)
Fetching data for: ZWP.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1710, 8)

[*********************100%***********************]  1 of 1 completed

Fetching data for: ZWQT.TO

Shape of DataFrame:  (376, 8)
Fetching data for: ZWS.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1710, 8)
Fetching data for: ZWT.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (985, 8)
Fetching data for: ZWU.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (3245, 8)
Fetching data for: ZXM.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (2534, 8)
Fetching data for: ZZZD.TO

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (1487, 8)

Price,date,close,high,low,open,volume,tic,day
0,2021-11-29,25.305000,25.379999,25.129999,25.379999,11100,MTAV.TO,0
1,2021-11-30,24.799999,25.299999,24.730000,25.270000,9400,MTAV.TO,1
2,2021-12-01,24.290001,25.219999,24.290001,25.219999,6600,MTAV.TO,2
3,2021-12-02,24.459999,24.500000,24.200001,24.410000,3300,MTAV.TO,3
4,2021-12-03,23.760000,24.330000,23.549999,24.330000,3300,MTAV.TO,4
...,...,...,...,...,...,...,...,...
1899779,2024-12-19,28.246168,28.549999,28.549999,28.549999,300,ZZZD.TO,3
1899780,2024-12-20,28.315426,28.620001,28.620001,28.620001,300,ZZZD.TO,4
1899781,2024-12-23,28.275850,28.590000,28.580000,28.590000,600,ZZZD.TO,0
1899782,2024-12-24,28.355000,28.660000,28.660000,28.660000,0,ZZZD.TO,1
1899783,2024-12-27,27.890001,28.299999,28.190001,28.299999,1300,ZZZD.TO,4

In [13]:

combined_portfolio_df = pd.concat([portfolio_raw_df, second_portfolio_raw_df], axis=0)
combined_portfolio_df

Price,date,close,high,low,open,volume,tic,day
0,2004-01-02,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,4
1,2004-01-05,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,0
2,2004-01-06,0.258670,0.280000,0.280000,0.280000,100,AAB.TO,1
3,2004-01-07,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,2
4,2004-01-08,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,3
...,...,...,...,...,...,...,...,...
1899779,2024-12-19,28.246168,28.549999,28.549999,28.549999,300,ZZZD.TO,3
1899780,2024-12-20,28.315426,28.620001,28.620001,28.620001,300,ZZZD.TO,4
1899781,2024-12-23,28.275850,28.590000,28.580000,28.590000,600,ZZZD.TO,0
1899782,2024-12-24,28.355000,28.660000,28.660000,28.660000,0,ZZZD.TO,1
1899783,2024-12-27,27.890001,28.299999,28.190001,28.299999,1300,ZZZD.TO,4

In [14]:
!pip install xlsxwriter
import pandas as pd
from google.colab import files

# Assuming combined_portfolio_df is already defined

def download_dataframe(df, filename="combined_portfolio.xlsx"):
    """Downloads a Pandas DataFrame to an Excel file.

    Splits the DataFrame into multiple sheets if it exceeds a certain size.

    Args:
        df: The Pandas DataFrame to download.
        filename: The name of the Excel file to create.
    """

    MAX_ROWS_PER_SHEET = 1048576  # Maximum rows per sheet in Excel

    if len(df) <= MAX_ROWS_PER_SHEET:
        df.to_excel(filename, index=False)
        files.download(filename)
    else:
        num_sheets = (len(df) // MAX_ROWS_PER_SHEET) + 1
        with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
            for i in range(num_sheets):
                start_row = i * MAX_ROWS_PER_SHEET
                end_row = min((i + 1) * MAX_ROWS_PER_SHEET, len(df))
                sheet_name = f"Sheet{i+1}"
                df.iloc[start_row:end_row].to_excel(writer, sheet_name=sheet_name, index=False)
        files.download(filename)


download_dataframe(combined_portfolio_df)

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.0-py3-none-any.whl.metadata (2.6 kB)
Downloading XlsxWriter-3.2.0-py3-none-any.whl (159 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 3.4 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.0

In [15]:
grouped= combined_portfolio_df.groupby("tic").count()
grouped

Price    date  close  high   low  open  volume   day
tic
AAB.TO   5271   5271  5271  5271  5271    5271  5271
AAUC.TO   325    325   325   325   325     325   325
AAV.TO   3805   3805  3805  3805  3805    3805  3805
ABX.TO   5271   5271  5271  5271  5271    5271  5271
AC.TO    3699   3699  3699  3699  3699    3699  3699
...       ...    ...   ...   ...   ...     ...   ...
ZWS.TO   1710   1710  1710  1710  1710    1710  1710
ZWT.TO    985    985   985   985   985     985   985
ZWU.TO   3245   3245  3245  3245  3245    3245  3245
ZXM.TO   2534   2534  2534  2534  2534    2534  2534
ZZZD.TO  1487   1487  1487  1487  1487    1487  1487

[1631 rows x 7 columns]

In [16]:
filtered_grouped = grouped[grouped["date"] == 5271]
filtered_grouped

Price   date  close  high   low  open  volume   day
tic
AAB.TO  5271   5271  5271  5271  5271    5271  5271
ABX.TO  5271   5271  5271  5271  5271    5271  5271
ACD.TO  5271   5271  5271  5271  5271    5271  5271
ACX.TO  5271   5271  5271  5271  5271    5271  5271
AEM.TO  5271   5271  5271  5271  5271    5271  5271
...      ...    ...   ...   ...   ...     ...   ...
XSB.TO  5271   5271  5271  5271  5271    5271  5271
XSP.TO  5271   5271  5271  5271  5271    5271  5271
XTC.TO  5271   5271  5271  5271  5271    5271  5271
YGR.TO  5271   5271  5271  5271  5271    5271  5271
YRB.TO  5271   5271  5271  5271  5271    5271  5271

[261 rows x 7 columns]

In [17]:
# Sort the combined_portfolio_df DataFrame
sorted_combined_portfolio_df = combined_portfolio_df.sort_values(by=['date', 'tic'], ascending=[True, True])
sorted_combined_portfolio_df

Price,date,close,high,low,open,volume,tic,day
958764,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3
991346,2004-01-01,1.378000,2.650000,2.650000,2.650000,0,EDT.TO,3
975876,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3
0,2004-01-02,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,4
9401,2004-01-02,22.070272,29.850000,29.320000,29.430000,413000,ABX.TO,4
...,...,...,...,...,...,...,...,...
1891532,2024-12-27,20.340000,20.570000,20.420000,20.570000,3600,ZWS.TO,4
1892517,2024-12-27,53.879997,54.299999,53.529999,54.299999,8500,ZWT.TO,4
1895762,2024-12-27,10.530001,10.640000,10.560000,10.620000,303500,ZWU.TO,4
1898296,2024-12-27,42.889999,42.889999,42.889999,42.889999,500,ZXM.TO,4
1899783,2024-12-27,27.890001,28.299999,28.190001,28.299999,1300,ZZZD.TO,4

In [18]:
# Define the list of stock tickers
tickers = ["AAB.TO", "AAUC.TO", "AAV.TO", "ABX.TO", "AC.TO", "ACAA.TO", "ACB.TO", "ACD.TO", "ACQ.TO", "ACX.TO", "ADCO.TO", "ADEN.TO", "ADIV.TO", "ADN.TO", "AEG.TO", "AEM.TO", "AFN.TO", "AG.TO", "AGG.TO", "AGI.TO", "AI.TO", "AIDX.TO", "AIF.TO", "AIGO.TO", "AII.TO", "AIM.TO", "ALA.TO", "ALC.TO", "ALS.TO", "ALYA.TO", "AMAX.TO", "AMC.TO", "AMHE.TO", "AMM.TO", "AMZH.TO", "AND.TO", "ANRG.TO", "AOI.TO", "AOT.TO", "APLI.TO", "APM.TO", "APS.TO", "AQN.TO", "ARA.TO", "ARB.TO", "ARE.TO", "ARG.TO", "ARIS.TO", "ARTI.TO", "ARX.TO", "ASCU.TO", "ASM.TO", "ASND.TO", "ASTL.TO", "ATCU.TO", "ATD.TO", "ATH.TO", "ATRL.TO", "ATS.TO", "ATSX.TO", "ATZ.TO", "AUMN.TO", "AVCN.TO", "AVL.TO", "AVNT.TO", "AW.TO", "AYA.TO", "BABY.TO", "BAM.TO", "BANK.TO", "BASE.TO", "BB.TO", "BBUC.TO", "BCE.TO", "BCHT.TO", "BCT.TO", "BDGI.TO", "BDI.TO", "BDIV.TO", "BDT.TO", "BEPC.TO", "BEPR.TO", "BESG.TO", "BFIN.TO", "BGC.TO", "BGU.TO", "BHC.TO", "BIPC.TO", "BIR.TO", "BITF.TO", "BITI.TO", "BK.TO", "BKCC.TO", "BKCL.TO", "BKI.TO", "BLCO.TO", "BLDP.TO", "BLN.TO", "BLOV.TO", "BLX.TO", "BMAX.TO", "BMO.TO", "BN.TO", "BNC.TO", "BND.TO", "BNE.TO", "BNG.TO", "BNK.TO", "BNKL.TO", "BNS.TO", "BNT.TO", "BOND.TO", "BOS.TO", "BPRF.TO", "BR.TO", "BRAG.TO", "BRE.TO", "BREA.TO", "BRMI.TO", "BRY.TO", "BSKT.TO", "BSX.TO", "BTCC.TO", "BTCQ.TO", "BTCY.TO", "BTE.TO", "BTO.TO", "BU.TO", "BUI.TO", "BXF.TO", "BYD.TO", "BYL.TO", "CACB.TO", "CAE.TO", "CAFR.TO", "CAGG.TO", "CAGS.TO", "CALL.TO", "CANL.TO", "CAPG.TO", "CAPI.TO", "CAPM.TO", "CAPW.TO", "CARB.TO", "CARS.TO", "CAS.TO", "CASH.TO", "CBAL.TO", "CBCX.TO", "CBGR.TO", "CBH.TO", "CBIL.TO", "CBIN.TO", "CBL.TO", "CBND.TO", "CBNK.TO", "CBO.TO", "CBUG.TO", "CCA.TO", "CCBI.TO", "CCEI.TO", "CCM.TO", "CCNS.TO", "CCNV.TO", "CCO.TO", "CCOM.TO", "CCRE.TO", "CDEF.TO", "CDIV.TO", "CDLB.TO", "CDNA.TO", "CDR.TO", "CDZ.TO", "CEF.TO", "CEMI.TO", "CEMX.TO", "CEQT.TO", "CEU.TO", "CEW.TO", "CF.TO", "CFF.TO", "CFLX.TO", "CFP.TO", "CFRT.TO", "CFW.TO", "CFX.TO", "CG.TO", "CGAA.TO", "CGBI.TO", "CGDV.TO", "CGG.TO", "CGHY.TO", "CGI.TO", "CGIN.TO", "CGL.TO", "CGLO.TO", "CGO.TO", "CGR.TO", "CGRA.TO", "CGRE.TO", "CGRN.TO", "CGRO.TO", "CGX.TO", "CGXF.TO", "CGY.TO", "CHPS.TO", "CHR.TO", "CIA.TO", "CIAI.TO", "CIBR.TO", "CIC.TO", "CIEH.TO", "CIEI.TO", "CIEM.TO", "CIF.TO", "CIGI.TO", "CINF.TO", "CINT.TO", "CINV.TO", "CIX.TO", "CJ.TO", "CJT.TO", "CKI.TO", "CLF.TO", "CLG.TO", "CLML.TO", "CLS.TO", "CM.TO", "CMAG.TO", "CMAR.TO", "CMDO.TO", "CMG.TO", "CMGG.TO", "CMNY.TO", "CMOM.TO", "CMR.TO", "CMVX.TO", "CNCC.TO", "CNCL.TO", "CNDX.TO", "CNE.TO", "CNL.TO", "CNQ.TO", "CNR.TO", "CNT.TO", "CNV.TO", "COG.TO", "COMM.TO", "COPP.TO", "COPR.TO", "CORE.TO", "COW.TO", "CP.TO", "CPD.TO", "CPH.TO", "CPLS.TO", "CPX.TO", "CRDL.TO", "CRED.TO", "CRON.TO", "CROP.TO", "CRP.TO", "CRRX.TO", "CRWN.TO", "CS.TO", "CSAV.TO", "CSBI.TO", "CSCI.TO", "CSU.TO", "CTC.TO", "CTS.TO", "CTX.TO", "CU.TO", "CUBD.TO", "CUD.TO", "CUDV.TO", "CUEH.TO", "CUEI.TO", "CURA.TO", "CUTL.TO", "CVD.TO", "CVE.TO", "CVG.TO", "CVLU.TO", "CVO.TO", "CWB.TO", "CWEB.TO", "CWL.TO", "CWW.TO", "CXB.TO", "CXF.TO", "CXI.TO", "CYB.TO", "CYBR.TO", "CYH.TO", "DAMG.TO", "DANC.TO", "DATA.TO", "DAY.TO", "DBM.TO", "DBO.TO", "DCBC.TO", "DCBO.TO", "DCC.TO", "DCG.TO", "DCM.TO", "DCP.TO", "DCS.TO", "DCU.TO", "DF.TO", "DFN.TO", "DFY.TO", "DGR.TO", "DGRC.TO", "DGS.TO", "DIAM.TO", "DISC.TO", "DIV.TO", "DIVS.TO", "DLCG.TO", "DLR.TO", "DMEC.TO", "DMEI.TO", "DMEU.TO", "DML.TO", "DND.TO", "DNG.TO", "DNTL.TO", "DOL.TO", "DOO.TO", "DPM.TO", "DR.TO", "DRCU.TO", "DRFC.TO", "DRFD.TO", "DRFE.TO", "DRFG.TO", "DRFU.TO", "DRM.TO", "DRMC.TO", "DRMD.TO", "DRME.TO", "DRMU.TO", "DRT.TO", "DRX.TO", "DS.TO", "DSAE.TO", "DSG.TO", "DSV.TO", "DTOL.TO", "DXAU.TO", "DXB.TO", "DXBB.TO", "DXBC.TO", "DXBG.TO", "DXBU.TO", "DXC.TO", "DXCB.TO", "DXCO.TO", "DXCP.TO", "DXDB.TO", "DXEM.TO", "DXET.TO", "DXF.TO", "DXG.TO", "DXGE.TO", "DXIF.TO", "DXMO.TO", "DXN.TO", "DXO.TO", "DXP.TO", "DXQ.TO", "DXR.TO", "DXT.TO", "DXU.TO", "DXUS.TO", "DXV.TO", "DXW.TO", "DXZ.TO", "DYA.TO", "E.TO", "EAGR.TO", "EARN.TO", "EBIT.TO", "EBNK.TO", "ECN.TO", "ECO.TO", "ECOR.TO", "EDGE.TO", "EDGF.TO", "EDR.TO", "EDT.TO", "EDV.TO", "EFN.TO", "EFR.TO", "EFX.TO", "EGLX.TO", "EIF.TO", "ELD.TO", "ELEF.TO", "ELF.TO", "ELO.TO", "ELR.TO", "ELVA.TO", "EMA.TO", "EMAX.TO", "ENB.TO", "ENCC.TO", "ENCL.TO", "ENGH.TO", "ENS.TO", "EPRX.TO", "EQB.TO", "EQCC.TO", "EQCL.TO", "EQL.TO", "EQLI.TO", "EQX.TO", "ERD.TO", "ERO.TO", "ESG.TO", "ESGA.TO", "ESGB.TO", "ESGC.TO", "ESGE.TO", "ESGF.TO", "ESGG.TO", "ESGH.TO", "ESGY.TO", "ESI.TO", "ESM.TO", "ESP.TO", "ESPX.TO", "ET.TO", "ETC.TO", "ETG.TO", "ETHH.TO", "ETHI.TO", "ETHQ.TO", "ETHR.TO", "ETHY.TO", "ETP.TO", "ETSX.TO", "EVO.TO", "EVT.TO", "EXE.TO", "EXN.TO", "EXRO.TO", "FAP.TO", "FAR.TO", "FBGO.TO", "FBT.TO", "FBTC.TO", "FC.TO", "FCCD.TO", "FCCQ.TO", "FCCV.TO", "FCEM.TO", "FCGI.TO", "FCID.TO", "FCII.TO", "FCIQ.TO", "FCIV.TO", "FCMI.TO", "FCQH.TO", "FCRR.TO", "FCUD.TO", "FCUH.TO", "FCUQ.TO", "FCUV.TO", "FCVH.TO", "FDL.TO", "FDN.TO", "FDY.TO", "FEC.TO", "FETH.TO", "FF.TO", "FFH.TO", "FFM.TO", "FFN.TO", "FGB.TO", "FGEB.TO", "FGEP.TO", "FGGE.TO", "FGO.TO", "FGOV.TO", "FGRW.TO", "FHG.TO", "FHH.TO", "FHI.TO", "FHIS.TO", "FHQ.TO", "FIE.TO", "FIG.TO", "FIL.TO", "FINC.TO", "FINE.TO", "FINO.TO", "FLCI.TO", "FLCP.TO", "FLGA.TO", "FLI.TO", "FLNT.TO", "FLOW.TO", "FLSD.TO", "FLUS.TO", "FLX.TO", "FM.TO", "FMAX.TO", "FN.TO", "FNV.TO", "FOM.TO", "FOOD.TO", "FORA.TO", "FOUR.TO", "FPR.TO", "FRU.TO", "FRX.TO", "FSB.TO", "FSF.TO", "FSL.TO", "FST.TO", "FSV.TO", "FSY.TO", "FSZ.TO", "FT.TO", "FTG.TO", "FTHI.TO", "FTN.TO", "FTS.TO", "FTT.TO", "FTU.TO", "FURY.TO", "FVI.TO", "FVL.TO", "FXM.TO", "G.TO", "GATO.TO", "GAU.TO", "GBAL.TO", "GBT.TO", "GCBD.TO", "GCFE.TO", "GCG.TO", "GCL.TO", "GCNS.TO", "GCSC.TO", "GCTB.TO", "GCU.TO", "GDC.TO", "GDEP.TO", "GDI.TO", "GDL.TO", "GDPY.TO", "GDV.TO", "GEC.TO", "GEI.TO", "GENM.TO", "GEO.TO", "GEQT.TO", "GFL.TO", "GFP.TO", "GFR.TO", "GGD.TO", "GGRO.TO", "GH.TO", "GIGC.TO", "GIL.TO", "GIQG.TO", "GIQU.TO", "GLCC.TO", "GLDX.TO", "GLO.TO", "GLXY.TO", "GMIN.TO", "GMTN.TO", "GMX.TO", "GOLD.TO", "GOOS.TO", "GPMD.TO", "GRA.TO", "GRC.TO", "GRCC.TO", "GRGD.TO", "GRID.TO", "GRN.TO", "GRNI.TO", "GRO.TO", "GSY.TO", "GTE.TO", "GTWO.TO", "GUD.TO", "GURU.TO", "GVC.TO", "GWO.TO", "GXE.TO", "H.TO", "HAB.TO", "HAC.TO", "HAD.TO", "HAF.TO", "HAI.TO", "HAL.TO", "HAZ.TO", "HBA.TO", "HBAL.TO", "HBB.TO", "HBD.TO", "HBF.TO", "HBGD.TO", "HBIE.TO", "HBIG.TO", "HBIL.TO", "HBKD.TO", "HBKU.TO", "HBLK.TO", "HBM.TO", "HBND.TO", "HBNK.TO", "HBP.TO", "HBU.TO", "HBUG.TO", "HCA.TO", "HCAL.TO", "HCLN.TO", "HCON.TO", "HCRE.TO", "HDGE.TO", "HDIF.TO", "HDIV.TO", "HEB.TO", "HED.TO", "HEQL.TO", "HEQT.TO", "HERO.TO", "HEU.TO", "HEWB.TO", "HFD.TO", "HFG.TO", "HFIN.TO", "HFR.TO", "HFU.TO", "HGD.TO", "HGGG.TO", "HGR.TO", "HGRW.TO", "HGU.TO", "HGY.TO", "HHL.TO", "HHLE.TO", "HIG.TO", "HIND.TO", "HIU.TO", "HIX.TO", "HLF.TO", "HLIF.TO", "HLIT.TO", "HLPR.TO", "HLS.TO", "HMAX.TO", "HMMJ.TO", "HMP.TO", "HND.TO", "HNU.TO", "HOD.TO", "HOU.TO", "HPF.TO", "HPR.TO", "HPYM.TO", "HPYT.TO", "HQD.TO", "HQU.TO", "HRAA.TO", "HRED.TO", "HREU.TO", "HRIF.TO", "HRX.TO", "HSAV.TO", "HSD.TO", "HSH.TO", "HSU.TO", "HTA.TO","HTAE.TO", "HTB.TO", "HUBL.TO", "HUC.TO", "HUG.TO", "HULC.TO", "HUM.TO", "HUN.TO", "HURA.TO", "HUT.TO", "HUTE.TO", "HUTL.TO", "HUTS.TO", "HUV.TO", "HUZ.TO", "HWO.TO", "HWX.TO", "HXCN.TO", "HXD.TO", "HXDM.TO", "HXE.TO", "HXEM.TO", "HXF.TO", "HXH.TO", "HXQ.TO", "HXS.TO", "HXT.TO", "HXU.TO", "HXX.TO", "HYBR.TO", "HYLD.TO", "HZD.TO", "HZU.TO", "IAG.TO", "IAU.TO", "ICAE.TO", "ICE.TO", "ICPB.TO", "ICTE.TO", "IE.TO", "IFA.TO", "IFC.TO", "IFP.TO", "IFRF.TO", "IGAF.TO", "IGB.TO", "IGEO.TO", "IGET.TO", "IGM.TO", "IIAE.TO", "IICE.TO", "III.TO", "IIMF.TO", "IITE.TO", "ILGB.TO", "ILLM.TO", "IMG.TO", "IMO.TO", "IMP.TO", "INAI.TO", "INCM.TO", "INE.TO", "INOC.TO", "IPCO.TO", "IPO.TO", "IQD.TO", "IS.TO", "ISC.TO", "ISCB.TO", "ISO.TO", "ISTE.TO", "ITH.TO", "IUAE.TO", "IUCE.TO", "IUMF.TO", "IUTE.TO", "IVN.TO", "IVQ.TO", "IWBE.TO", "IXTE.TO", "JAG.TO", "JAPN.TO", "JEPI.TO", "JEPQ.TO", "JOY.TO", "JWEL.TO", "K.TO", "KBL.TO", "KEC.TO", "KEI.TO", "KEL.TO", "KEY.TO", "KILO.TO", "KITS.TO", "KLS.TO", "KNGC.TO", "KNGU.TO", "KNGX.TO", "KNT.TO", "KPT.TO", "KRN.TO", "KSI.TO", "KXS.TO", "L.TO", "LAAC.TO", "LABS.TO", "LAC.TO", "LAM.TO", "LB.TO", "LBS.TO", "LCFS.TO", "LCS.TO", "LEAD.TO", "LFE.TO", "LGD.TO", "LGO.TO", "LIF.TO", "LIFE.TO", "LIRC.TO", "LLHE.TO", "LLYH.TO", "LMAX.TO", "LN.TO", "LNF.TO", "LNR.TO", "LPAY.TO", "LSPD.TO", "LSPK.TO", "LUC.TO", "LUG.TO", "LUN.TO", "LYCT.TO", "LYFR.TO", "MAG.TO", "MAL.TO", "MARI.TO", "MART.TO", "MATR.TO", "MBAL.TO", "MBX.TO", "MCAD.TO", "MCB.TO", "MCLC.TO", "MCLV.TO", "MCON.TO", "MCSB.TO", "MCSM.TO", "MDA.TO", "MDI.TO", "MDIV.TO", "MDNA.TO", "MDP.TO", "MDVD.TO", "MEG.TO", "MEQ.TO", "MEQT.TO", "MFC.TO", "MFI.TO", "MFT.TO", "MG.TO", "MGA.TO", "MGAB.TO", "MGB.TO", "MGDV.TO", "MGQE.TO", "MGRW.TO", "MHCD.TO", "MINF.TO", "MINN.TO", "MINT.TO", "MIQE.TO", "MIVG.TO", "MKB.TO", "MKP.TO", "MND.TO", "MNO.TO", "MNS.TO", "MNT.TO", "MNXT.TO", "MNY.TO", "MOGO.TO", "MORE.TO", "MPAY.TO", "MPC.TO", "MPVD.TO", "MPY.TO", "MRC.TO", "MRD.TO", "MRE.TO", "MREL.TO", "MRU.TO", "MSA.TO", "MSCL.TO", "MSFH.TO", "MSHE.TO", "MSV.TO", "MTAV.TO", "MTL.TO", "MTY.TO", "MUB.TO", "MULC.TO", "MULV.TO", "MUMC.TO", "MUSA.TO", "MUX.TO", "MWLV.TO", "MX.TO", "MXG.TO", "NA.TO", "NALT.TO", "NANO.TO", "NCF.TO", "NDIV.TO", "NDM.TO", "NEO.TO", "NEXT.TO", "NFI.TO", "NG.TO", "NGD.TO", "NGDN.TO", "NGEX.TO", "NGPE.TO", "NGT.TO", "NGUP.TO", "NHYB.TO", "NINT.TO", "NOA.TO", "NPI.TO", "NPK.TO", "NPRF.TO", "NPS.TO", "NREA.TO", "NRGY.TO", "NSCB.TO", "NSCC.TO", "NSCE.TO", "NSGE.TO", "NSSB.TO", "NTR.TO", "NUAG.TO", "NUBF.TO", "NUMI.TO", "NUSA.TO", "NVA.TO", "NVDH.TO", "NVHE.TO", "NVO.TO", "NWC.TO", "NXE.TO", "NXF.TO", "NXTG.TO", "OBE.TO", "OGC.TO", "OGD.TO", "OGI.TO", "OLA.TO", "OLY.TO", "ONC.TO", "ONEB.TO", "ONEC.TO", "ONEQ.TO", "ONEX.TO", "OPT.TO", "OR.TO", "ORA.TO", "ORE.TO", "ORV.TO", "OTEX.TO", "OVV.TO", "PAAS.TO", "PABF.TO", "PACF.TO", "PAGF.TO", "PAY.TO", "PAYF.TO", "PAYL.TO", "PAYM.TO", "PAYS.TO", "PBD.TO", "PBH.TO", "PBI.TO", "PBL.TO", "PCOR.TO", "PD.TO", "PDC.TO", "PDF.TO", "PDIV.TO", "PDN.TO", "PDV.TO", "PEA.TO", "PET.TO", "PEY.TO", "PFAA.TO", "PFAE.TO", "PFCB.TO", "PFIA.TO", "PFL.TO", "PFLS.TO", "PFMN.TO", "PFSS.TO", "PGIC.TO", "PHR.TO", "PHX.TO", "PHYS.TO", "PID.TO", "PIF.TO", "PIN.TO", "PINC.TO", "PKI.TO", "PLDI.TO", "PLV.TO", "PME.TO", "PMET.TO", "PMIF.TO", "PMM.TO", "PMNT.TO", "PNE.TO", "PNP.TO", "POU.TO", "POW.TO", "PPL.TO", "PPLN.TO", "PPR.TO", "PPTA.TO", "PR.TO", "PRA.TO", "PRB.TO", "PREF.TO", "PRL.TO", "PRM.TO", "PRN.TO", "PRQ.TO", "PRU.TO", "PRYM.TO", "PSA.TO", "PSB.TO", "PSD.TO", "PSI.TO", "PSK.TO", "PSLV.TO", "PTM.TO", "PWI.TO", "PXC.TO", "PXS.TO", "PXT.TO", "PYF.TO", "PYR.TO", "PZA.TO", "PZW.TO", "QAH.TO", "QASH.TO", "QBB.TO", "QBTC.TO", "QBTL.TO", "QCE.TO", "QCLN.TO", "QCN.TO", "QDX.TO", "QDXB.TO", "QDXH.TO", "QEBH.TO", "QEBL.TO", "QEC.TO", "QEE.TO", "QHY.TO", "QIE.TO", "QINF.TO", "QIPT.TO", "QLB.TO", "QMAX.TO", "QQC.TO", "QQCC.TO", "QQCE.TO", "QQCI.TO", "QQCL.TO", "QQEQ.TO", "QQJE.TO", "QQJR.TO", "QQQL.TO", "QQQT.TO", "QQQX.TO", "QQQY.TO", "QRC.TO", "QRET.TO", "QSB.TO", "QSR.TO", "QTLT.TO", "QTRH.TO", "QUB.TO", "QUIG.TO", "QUS.TO", "QUU.TO", "QXM.TO", "RAAA.TO", "RATE.TO", "RBA.TO", "RBNK.TO", "RBO.TO", "RBOT.TO", "RBY.TO", "RCD.TO", "RCDC.TO", "RCG.TO", "RCH.TO", "RDBH.TO", "REAL.TO", "RGQN.TO", "RGQO.TO", "RGQP.TO", "RGQQ.TO", "RGQR.TO", "RGQS.TO", "RID.TO", "RIDH.TO", "RIFI.TO", "RIIN.TO", "RING.TO", "RIRA.TO", "RIT.TO", "RLB.TO", "RMAX.TO", "ROOT.TO", "RPD.TO", "RPDH.TO", "RPF.TO", "RPSB.TO", "RQN.TO", "RQO.TO", "RQP.TO", "RQQ.TO", "RQR.TO", "RQS.TO", "RS.TO", "RSI.TO", "RTG.TO", "RUBH.TO", "RUBY.TO", "RUD.TO", "RUDB.TO", "RUDC.TO", "RUDH.TO", "RUP.TO", "RUQN.TO", "RUQO.TO", "RUQQ.TO", "RUQR.TO", "RUQS.TO", "RUS.TO", "RUSB.TO", "RVX.TO", "RXD.TO", "RY.TO", "S.TO", "SAFE.TO", "SAM.TO", "SAP.TO", "SAU.TO", "SBC.TO", "SBI.TO", "SBT.TO", "SCR.TO", "SCY.TO", "SDE.TO", "SEA.TO", "SEC.TO", "SES.TO", "SFC.TO", "SFD.TO", "SFI.TO", "SFTC.TO", "SGLD.TO", "SGY.TO", "SHLE.TO", "SHOP.TO", "SIA.TO", "SII.TO", "SIL.TO", "SIS.TO", "SJ.TO", "SKE.TO", "SKYY.TO", "SLF.TO", "SLR.TO", "SLS.TO", "SMAX.TO", "SMC.TO", "SMT.TO", "SOBO.TO", "SOIL.TO", "SOLG.TO", "SOY.TO", "SPAY.TO", "SPB.TO", "SPFD.TO", "SPLT.TO", "SPPP.TO", "SSL.TO", "SSRM.TO", "STC.TO", "STCK.TO", "STEP.TO", "STGO.TO", "STLR.TO", "STN.TO", "STPL.TO", "SU.TO", "SVA.TO", "SVB.TO", "SVI.TO", "SVM.TO", "SVR.TO", "SWP.TO", "SXI.TO", "SXP.TO", "SYLD.TO", "SYZ.TO", "T.TO", "TA.TO", "TAL.TO", "TBAL.TO", "TBCE.TO", "TBCF.TO", "TBCG.TO", "TBIL.TO", "TBL.TO", "TBNK.TO", "TC.TO", "TCBN.TO", "TCLB.TO", "TCLV.TO", "TCON.TO", "TCS.TO", "TCSB.TO", "TCSH.TO", "TCW.TO", "TD.TO", "TDB.TO", "TDOC.TO", "TEC.TO", "TECH.TO", "TECI.TO", "TECX.TO", "TERM.TO", "TF.TO", "TFII.TO", "TFPM.TO", "TGAF.TO", "TGED.TO", "TGFI.TO", "TGGR.TO", "TGO.TO", "TGRE.TO", "TGRO.TO", "TH.TO", "The.TO", "THNC.TO", "THU.TO", "TI.TO", "TIH.TO", "TILV.TO", "TINF.TO", "TIPS.TO", "TIXT.TO", "TKN.TO", "TKO.TO", "TLF.TO", "TLG.TO", "TLO.TO", "TLRY.TO", "TLV.TO", "TMQ.TO", "TNZ.TO", "TOT.TO", "TOU.TO", "TOWR.TO", "TOY.TO", "TPE.TO", "TPRF.TO", "TPU.TO", "TPZ.TO", "TQCD.TO", "TQGD.TO", "TQGM.TO", "TQSM.TO", "TRI.TO", "TRP.TO", "TRVI.TO", "TRVL.TO", "TRX.TO", "TRZ.TO", "TSAT.TO", "TSK.TO", "TSL.TO", "TSND.TO", "TSU.TO", "TTNM.TO", "TTP.TO", "TTTX.TO", "TUED.TO", "TUEX.TO", "TUHY.TO", "TULB.TO", "TULV.TO", "TUSB.TO", "TVE.TO", "TVK.TO", "TWC.TO", "TWM.TO", "TXF.TO", "TXG.TO", "TXP.TO", "UDA.TO", "UDIV.TO", "UMAX.TO", "UMI.TO", "UNC.TO", "UNI.TO", "URB.TO", "URC.TO", "URE.TO", "USA.TO", "USCC.TO", "USCL.TO", "USSL.TO", "USSX.TO", "UTES.TO", "UTIL.TO", "VA.TO", "VAB.TO", "VALT.TO", "VBAL.TO", "VBNK.TO", "VCB.TO", "VCE.TO", "VCIP.TO", "VCM.TO", "VCN.TO", "VCNS.TO", "VDU.TO", "VDY.TO", "VE.TO", "VEE.TO", "VEF.TO", "VEQT.TO", "VET.TO", "VFV.TO", "VGG.TO", "VGH.TO", "VGRO.TO", "VGV.TO", "VGZ.TO", "VHI.TO", "VI.TO", "VIDY.TO", "VIU.TO", "VLB.TO", "VLE.TO", "VLN.TO", "VMO.TO", "VNP.TO", "VOXR.TO", "VQS.TO", "VRE.TO", "VRIF.TO", "VRN.TO", "VRTS.TO", "VSB.TO", "VSC.TO", "VSP.TO", "VUN.TO", "VUS.TO", "VVL.TO", "VVO.TO", "VVSG.TO", "VXC.TO", "VXM.TO", "VZLA.TO", "WCN.TO", "WCP.TO", "WDO.TO", "WEED.TO", "WEF.TO", "WELL.TO", "WFC.TO", "WFG.TO", "WGX.TO", "WILD.TO", "WJX.TO", "WLLW.TO", "WM.TO", "WN.TO", "WNDR.TO", "WOMN.TO", "WPK.TO", "WPM.TO", "WPRT.TO", "WRG.TO", "WRN.TO", "WRX.TO", "WSP.TO", "WSRD.TO", "WSRI.TO", "WTE.TO", "WXM.TO", "X.TO", "XAD.TO", "XAGG.TO", "XAGH.TO", "XAM.TO", "XAU.TO", "XAW.TO", "XBAL.TO", "XBB.TO", "XBM.TO", "XCB.TO", "XCBG.TO", "XCBU.TO", "XCD.TO", "XCG.TO", "XCH.TO", "XCHP.TO", "XCLN.TO", "XCNS.TO", "XCS.TO", "XCSR.TO", "XCV.TO", "XDG.TO", "XDGH.TO", "XDIV.TO", "XDNA.TO", "XDRV.TO", "XDSR.TO", "XDU.TO", "XDUH.TO", "XDV.TO", "XEB.TO", "XEC.TO", "XEF.TO", "XEG.TO", "XEH.TO", "XEI.TO", "XEM.TO", "XEMC.TO", "XEN.TO", "XEQT.TO", "XESG.TO", "XETM.TO", "XEU.TO", "XEXP.TO", "XFH.TO", "XFLB.TO", "XFLI.TO", "XFLX.TO", "XFN.TO", "XFR.TO", "XGB.TO", "XGD.TO", "XGI.TO", "XGRO.TO", "XHAK.TO", "XHB.TO", "XHC.TO", "XHD.TO", "XHU.TO", "XHY.TO", "XIC.TO", "XID.TO", "XIG.TO", "XIGS.TO", "XIN.TO", "XINC.TO", "XIT.TO", "XIU.TO", "XLB.TO", "XLY.TO", "XMA.TO", "XMC.TO", "XMD.TO", "XMH.TO", "XMI.TO", "XML.TO", "XMM.TO", "XMS.TO", "XMTM.TO", "XMU.TO", "XMV.TO", "XMW.TO", "XMY.TO", "XPF.TO", "XQB.TO", "XQLT.TO", "XQQ.TO", "XQQU.TO", "XRB.TO", "XRE.TO", "XSAB.TO", "XSB.TO", "XSC.TO", "XSE.TO", "XSEA.TO", "XSEM.TO", "XSH.TO", "XSHG.TO", "XSHU.TO", "XSI.TO", "XSMC.TO", "XSMH.TO", "XSP.TO", "XSPC.TO", "XST.TO", "XSTB.TO", "XSTH.TO", "XSTP.TO", "XSU.TO", "XSUS.TO", "XTC.TO", "XTD.TO", "XTG.TO", "XTLH.TO", "XTLT.TO", "XTR.TO", "XTRA.TO", "XUH.TO", "XUS.TO", "XUSC.TO", "XUSF.TO", "XUSR.TO", "XUT.TO", "XUU.TO", "XVLU.TO", "XWD.TO", "Y.TO", "YCM.TO", "YGR.TO", "YRB.TO", "ZACE.TO", "ZAG.TO", "ZBAL.TO", "ZBBB.TO", "ZBI.TO", "ZBK.TO", "ZCB.TO", "ZCDB.TO", "ZCH.TO", "ZCLN.TO", "ZCM.TO", "ZCN.TO", "ZCON.TO", "ZCPB.TO", "ZCS.TO", "ZDB.TO", "ZDH.TO", "ZDI.TO", "ZDJ.TO", "ZDM.TO", "ZDV.TO", "ZDY.TO", "ZEA.TO", "ZEAT.TO", "ZEB.TO", "ZEF.TO", "ZEM.TO", "ZEO.TO", "ZEQ.TO", "ZEQT.TO", "ZESG.TO", "ZFC.TO", "ZFH.TO", "ZFL.TO", "ZFM.TO", "ZFN.TO", "ZFS.TO", "ZGB.TO", "ZGD.TO", "ZGI.TO", "ZGLD.TO", "ZGLH.TO", "ZGQ.TO", "ZGRN.TO", "ZGRO.TO", "ZGSB.TO", "ZHP.TO", "ZHU.TO", "ZHY.TO", "ZIC.TO", "ZID.TO", "ZIN.TO", "ZIQ.TO", "ZIU.TO", "ZJG.TO", "ZJK.TO", "ZJPN.TO", "ZLB.TO", "ZLC.TO", "ZLD.TO", "ZLE.TO", "ZLH.TO", "ZLI.TO", "ZLSC.TO", "ZLSU.TO", "ZLU.TO", "ZMBS.TO", "ZMI.TO", "ZMID.TO", "ZMMK.TO", "ZMP.TO", "ZMSB.TO", "ZMT.TO", "ZMU.TO", "ZNQ.TO", "ZPAY.TO", "ZPH.TO", "ZPL.TO", "ZPR.TO", "ZPS.TO", "ZPW.TO", "ZQB.TO", "ZQQ.TO", "ZRE.TO", "ZRR.TO", "ZSB.TO", "ZSDB.TO", "ZSML.TO", "ZSP.TO", "ZST.TO", "ZSU.TO", "ZTIP.TO", "ZUAG.TO", "ZUB.TO", "ZUCM.TO", "ZUD.TO", "ZUE.TO", "ZUGE.TO", "ZUH.TO", "ZUP.TO", "ZUQ.TO", "ZUT.TO", "ZVC.TO", "ZVU.TO", "ZWA.TO", "ZWB.TO", "ZWC.TO", "ZWE.TO", "ZWEN.TO", "ZWG.TO", "ZWH.TO", "ZWHC.TO", "ZWK.TO", "ZWP.TO", "ZWQT.TO", "ZWS.TO", "ZWT.TO", "ZWU.TO", "ZXM.TO", "ZZZD.TO"]  # Replace with your desired tickers

# Desired fields to extract
desired_fields = [
    "symbol", "sector", "industry", "longName", "shortName", "exchange", "country",
    "state", "city", "currency", "sharesOutstanding", "trailingPE",
    "forwardPE", "pegRatio", "grossProfits", "profitMargins"
]

# Initialize an empty list to store the stock information
stock_data = []

# Fetch information for each ticker
for ticker_symbol in tickers:
    ticker = yf.Ticker(ticker_symbol)
    stock_info = ticker.info
    # Extract only the desired fields
    filtered_info = {key: stock_info.get(key, None) for key in desired_fields}
    stock_data.append(filtered_info)

    # Delay of 1 second between requests to avoid hitting rate limit
    time.sleep(1)

# Create a DataFrame from the collected stock data
filtered_info_df = pd.DataFrame(stock_data)

# Display the DataFrame with gridlines using tabulate
print(tabulate(filtered_info_df, headers="keys", tablefmt="grid"))

+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|      | symbol   | sector                 | industry                                 | longName                                                                       | shortName                       | exchange   | country                | state   | city                   | currency   |   sharesOutstanding | trailingPE   | forwardPE    | pegRatio   |      grossProfits |   profitMargins |
+======+==========+========================+==========================================+================================================================================+=================================+============+========================+=========+========================+============+=====================+==============+==============+============+===================+=================+
|    0 | AAB.TO   | Financial Services     | Asset Management                         | Aberdeen International Inc.                                                    | ABERDEEN INTERNATIONAL INC.     | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.59187e+08 |              |              |            |      -8.89676e+06 |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    1 | AAUC.TO  | Basic Materials        | Gold                                     | Allied Gold Corporation                                                        | ALLIED GOLD CORPORATION         | TOR        | Canada                 | ON      | Toronto                | CAD        |         3.28888e+08 |              | 5.0948887    |            |       2.40241e+08 |        -0.13515 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    2 | AAV.TO   | Energy                 | Oil & Gas E&P                            | Advantage Energy Ltd.                                                          | ADVANTAGE ENERGY LTD            | TOR        | Canada                 | AB      | Calgary                | CAD        |         1.66972e+08 | 37.37037     | 8.773913     |            |       2.77729e+08 |         0.09331 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    3 | ABX.TO   | Basic Materials        | Gold                                     | Barrick Gold Corporation                                                       | BARRICK GOLD CORPORATION        | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.74805e+09 | 17.530302    | 12.569529    |            |       4.242e+09   |         0.13189 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    4 | AC.TO    | Industrials            | Airlines                                 | Air Canada                                                                     | AIR CANADA                      | TOR        | Canada                 | QC      | Saint-Laurent          | CAD        |         3.58493e+08 | 3.0705707    | 8.314496     |            |       6.865e+09   |         0.11568 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    5 | ACAA.TO  |                        |                                          | Arrow Long/Short Alternative Fund ETF                                          | ARROW LONG SHORT ALTERNATIVE FU | TOR        |                        |         |                        | CAD        |       nan           | 13.669558    |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    6 | ACB.TO   | Healthcare             | Drug Manufacturers - Specialty & Generic | Aurora Cannabis Inc.                                                           | AURORA CANNABIS INC             | TOR        | Canada                 | AB      | Edmonton               | CAD        |         5.48772e+07 |              | -16.848484   |            |       1.5775e+08  |        -0.14708 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    7 | ACD.TO   | Financial Services     | Credit Services                          | Accord Financial Corp.                                                         | ACCORD FINANCIAL                | TOR        | Canada                 | ON      | Toronto                | CAD        |         8.55891e+06 |              | 6.491803     |            |       4.1942e+07  |        -0.21136 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    8 | ACQ.TO   | Consumer Cyclical      | Auto & Truck Dealerships                 | AutoCanada Inc.                                                                | AUTOCANADA INC                  | TOR        | Canada                 | AB      | Edmonton               | CAD        |         2.31417e+07 |              | 13.514329    |            |       1.02707e+09 |        -0.00593 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|    9 | ACX.TO   | Energy                 | Oil & Gas Drilling                       | ACT Energy Technologies Ltd.                                                   | ACT ENERGY TECHNOLOGIES LTD     | TOR        | Canada                 | AB      | Calgary                | CAD        |         3.48764e+07 | 6.0          | 4.0116277    |            |       1.65468e+08 |         0.07601 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   10 | ADCO.TO  | Technology             | Software - Application                   | Adcore Inc.                                                                    | ADCORE INC                      | TOR        | Canada                 | ON      | Toronto                | CAD        |         6.04856e+07 |              |              |            |       9.568e+06   |        -0.03921 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   11 | ADEN.TO  | Industrials            | Industrial Distribution                  | ADENTRA Inc.                                                                   | ADENTRA INC                     | TOR        | Canada                 | BC      | Langley                | CAD        |         2.50189e+07 | 12.354167    | 10.846471    |            |       4.67112e+08 |         0.02074 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   12 | ADIV.TO  |                        |                                          | Arrow EC Equity Advantage Alternative Fund Series ETF                          | ARROW EC EQ ADVTG ALTERNATV FND | TOR        |                        |         |                        | CAD        |       nan           |              |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   13 | ADN.TO   | Basic Materials        | Lumber & Wood Production                 | Acadian Timber Corp.                                                           | ACADIAN TIMBER CORP             | TOR        | Canada                 | NB      | Edmundston             | CAD        |         1.75368e+07 | 10.73125     | 16.509617    |            |       3.759e+07   |         0.23165 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   14 | AEG.TO   | Consumer Cyclical      | Restaurants                              | Aegis Brands Inc.                                                              | AEGIS BRANDS INC                | TOR        | Canada                 | ON      | Toronto                | CAD        |         8.52872e+07 |              |              |            |       1.5222e+07  |        -0.27739 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   15 | AEM.TO   | Basic Materials        | Gold                                     | Agnico Eagle Mines Limited                                                     | AGNICO EAGLE MINES LIMITED      | TOR        | Canada                 | ON      | Toronto                | CAD        |         5.01517e+08 | 43.038464    | 24.2244      |            |       4.73119e+09 |         0.12947 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   16 | AFN.TO   | Industrials            | Farm & Heavy Construction Machinery      | Ag Growth International Inc.                                                   | AG GROWTH INTERNATIONAL INC.    | TOR        | Canada                 | MB      | Winnipeg               | CAD        |         1.90749e+07 | 33.08943     | 8.723815     |            |       4.49629e+08 |         0.01706 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   17 | AG.TO    | Basic Materials        | Silver                                   | First Majestic Silver Corp.                                                    | FIRST MAJESTIC SILVER CORP      | TOR        | Canada                 | BC      | Vancouver              | CAD        |         4.79012e+08 |              | 18.252594    |            |       1.55028e+08 |        -0.14885 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   18 | AGG.TO   |                        |                                          | Evolve Canadian Aggregate Bond Enhanced Yield Fund ETF                         | EVOLVE CDN AGGRGT BOND ENHD YLD | TOR        |                        |         |                        | CAD        |       nan           |              |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   19 | AGI.TO   | Basic Materials        | Gold                                     | Alamos Gold Inc.                                                               | ALAMOS GOLD INC CLS A           | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.20282e+08 | 32.82558     | 22.725443    |            |       7.195e+08   |         0.19891 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   20 | AI.TO    | Financial Services     | Mortgage Finance                         | Atrium Mortgage Investment Corporation                                         | ATRIUM MORTGAGE INVESTMENT CORP | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.71161e+07 | 10.266666    | 10.315789    |            |       4.8158e+07  |         0.81768 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   21 | AIDX.TO  | Healthcare             | Medical Care Facilities                  | Healwell AI Inc.                                                               | HEALWELL AI INC                 | TOR        | Canada                 | ON      | Toronto                | CAD        |         1.6588e+08  |              | -23.125      |            |       1.0999e+07  |        -0.79138 |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   22 | AIF.TO   | Real Estate            | Real Estate Services                     | Altus Group Limited                                                            | ALTUS GROUP LIMITED             | TOR        | Canada                 | ON      | Toronto                | CAD        |         4.58946e+07 | 214.8077     | 34.85092     |            |       2.99311e+08 |         0.0034  |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+
|   23 | AIGO.TO  |                        |                                          | Global X Artificial Intelligence & Technology Index ETF                        | GLOBAL X ARTIFCL INTELLIG TECH  | TOR        |                        |         |                        | CAD        |       nan           | 32.605583    |              |            |     nan           |       nan       |
+------+----------+------------------------+------------------------------------------+--------------------------------------------------------------------------------+---------------------------------+------------+------------------------+---------+------------------------+------------+---------------------+--------------+--------------+------------+-------------------+-----------------+

In [19]:
merged_df = pd.merge(sorted_combined_portfolio_df, filtered_info_df, left_on='tic', right_on='symbol', how='left')
merged_df

,date,close,high,low,open,volume,tic,day,symbol,sector,...,country,state,city,currency,sharesOutstanding,trailingPE,forwardPE,pegRatio,grossProfits,profitMargins
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,DYA.TO,Industrials,...,Canada,ON,Toronto,CAD,4.406790e+08,None,None,None,-1.865161e+06,NaN
1,2004-01-01,1.378000,2.650000,2.650000,2.650000,0,EDT.TO,3,EDT.TO,Healthcare,...,Canada,ON,Toronto,CAD,2.828150e+08,None,-10.0,None,7.160000e+05,NaN
2,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,TSK.TO,Basic Materials,...,Canada,ON,Toronto,CAD,9.830170e+07,None,2.1875,None,-1.162254e+06,NaN
3,2004-01-02,0.489625,0.530000,0.530000,0.530000,0,AAB.TO,4,AAB.TO,Financial Services,...,Canada,ON,Toronto,CAD,1.591870e+08,None,None,None,-8.896760e+06,NaN
4,2004-01-02,22.070272,29.850000,29.320000,29.430000,413000,ABX.TO,4,ABX.TO,Basic Materials,...,Canada,ON,Toronto,CAD,1.748050e+09,17.530302,12.569529,None,4.242000e+09,0.13189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4067554,2024-12-27,20.340000,20.570000,20.420000,20.570000,3600,ZWS.TO,4,ZWS.TO,None,...,None,None,None,CAD,NaN,None,None,None,NaN,NaN
4067555,2024-12-27,53.879997,54.299999,53.529999,54.299999,8500,ZWT.TO,4,ZWT.TO,None,...,None,None,None,CAD,NaN,None,None,None,NaN,NaN
4067556,2024-12-27,10.530001,10.640000,10.560000,10.620000,303500,ZWU.TO,4,ZWU.TO,None,...,None,None,None,CAD,NaN,None,None,None,NaN,NaN
4067557,2024-12-27,42.889999,42.889999,42.889999,42.889999,500,ZXM.TO,4,ZXM.TO,None,...,None,None,None,CAD,NaN,12.068125,None,None,NaN,NaN
4067558,2024-12-27,27.890001,28.299999,28.190001,28.299999,1300,ZZZD.TO,4,ZZZD.TO,None,...,None,None,None,CAD,NaN,15.39612,None,None,NaN,NaN

In [ ]:
import yfinance as yf
import pandas as pd
from tabulate import tabulate
import time
import warnings
import logging
import torch
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from google.colab import files

# Assuming merged_df is already defined as in your example
# merged_df = pd.merge(sorted_combined_portfolio_df, filtered_info_df, left_on='tic', right_on='symbol', how='left')

def download_df_as_excel(df, filename="merged_data.xlsx", chunksize=100000):
    """Downloads a Pandas DataFrame as an Excel file, splitting into sheets if too large.

    Args:
      df: The DataFrame to download.
      filename: The name of the Excel file to create.
      chunksize: The maximum number of rows per sheet.
    """
    if len(df) <= chunksize:
      df.to_excel(filename, index=False)
      files.download(filename)
      return

    with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
        for i in range(0, len(df), chunksize):
            chunk = df[i:i + chunksize]
            sheet_name = f"Sheet{i // chunksize + 1}"
            chunk.to_excel(writer, sheet_name=sheet_name, index=False)
    files.download(filename)

# Example usage with your merged_df:
download_df_as_excel(merged_df)